### ISSUE TITLE
Changing Cell Properties (Colour) Remove/Replace Existing Styling

### ISSUE THREAD

**Issue by rkarina** [ckeditor/ckeditor-dev#3142] opened 2019-05-30 00:54 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a table with a few cells. 
2. Change the width of a column (the last column in this case).
3. Change the background colour of a cell from that column and press ok.

Notes:
- I noticed the RowSpan and ColSpan values did not prime on the Cell Properties dialog (which could be the real issue here).
- I've attached the HTML source which has this issue and images of steps on how to reproduce.

### Expected result

Should retain previous column/cell styling.

### Actual result

Removes previous column/cell styling.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.11.3
* Installed CKEditor plugins: {
		'a11yhelp' : 1,
		'autolink' : 1,
		'backgrounds' : 1,
		'base64image' : 1,
		'basicstyles' : 1,
		'bgimage' : 1,
		'blockquote' : 1,
		'chart' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'contextmenu' : 1,
		'docprops' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'footnotes' : 1,
		'format' : 1,
		'forms' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'image' : 1,
		'imagepaste' : 1,
		'imageresize' : 1,
		'imagerotate' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'language' : 1,
		'lineheight' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'maxheight' : 1,
		'pagebreak' : 1,
		'panelbutton' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'pbckcode' : 1,
		'print' : 1,
		'quicktable' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'scayt' : 1,
		'showblocks' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'stylesheetparser' : 1,
		'tab' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tabletools' : 1,
		'textsignature' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'uploadimage' : 1,
		'wordcount' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'zoom' : 1
	}

![Cell Properties 3](https://user-images.githubusercontent.com/19806920/58600490-235edb80-82c8-11e9-96a8-0750891fda01.jpg)
![Cell Properties 2](https://user-images.githubusercontent.com/19806920/58600491-235edb80-82c8-11e9-9d80-63afa3a2db64.jpg)
![Cell Properties 1](https://user-images.githubusercontent.com/19806920/58600492-23f77200-82c8-11e9-8d99-9710b2714812.jpg)
[TableSource.txt](https://github.com/ckeditor/ckeditor-dev/files/3234994/TableSource.txt)

**Comment by jacekbogdanski** [comment] 2019-06-03 06:54
I cannot reproduce the issue with the given reproduction steps:

![cellstyles](https://user-images.githubusercontent.com/10279586/58781160-6e843180-85db-11e9-8f10-e45d8f0e0bf9.gif)

I see that you are using row span and col span attributes which takes precedence over `width` style, but it's native behavior which works as expected (you can still change e.g. background style). Could you provide more information on how to reproduce the issue?

**Comment by rkarina** [comment] 2019-06-03 06:59
It's the same issue as https://github.com/ckeditor/ckeditor-dev/issues/3143#issuecomment-497218642 . Please see the comments, screenshots and screen cast.

**Comment by f1ames** [comment] 2019-07-08 11:04
Closing as duplicates as @rkarina mentioned in [the comment above](https://github.com/ckeditor/ckeditor-dev/issues/3142#issuecomment-498136295):

> It's the same issue as https://github.com/ckeditor/ckeditor-dev/issues/3143#issuecomment-497218642 . Please see the comments, screenshots and screen cast.

**Closed by f1ames** 2019-07-08 11:04 UTC
Labels: status:pending, type:bug
