### ISSUE TITLE
Tabbing through two inline editors throws TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by bradbalfour** [ckeditor/ckeditor-dev#585] opened 2017-06-29 20:43 UTC
## Are you reporting a feature or a bug?

Bug

https://dev.ckeditor.com/ticket/17028

## Provide detailed reproduction steps (if any)

1. Create a page with 2 inline CKEditors
2. change text in the first editor
3. tab out of the first editor and into the second editor
4. tab out of the second editor

### Expected result

CKEditor works with no errors

### Actual result

```
Uncaught TypeError: Cannot read property 'contains' of null
    at c.getContext (ckeditor.js:696)
    at c.<anonymous> (ckeditor.js:701)
    at a.h (ckeditor.js:10)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js:11)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.keystrokeHandler.f (ckeditor.js:227)
    at g.h (ckeditor.js:10)
    at g.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js:11)
    at HTMLDivElement.<anonymous> (ckeditor.js:57)
```

## Other details

* Browser: Version 58.0.3029.110 (64-bit)
* OS: Mac OS X v10.12.5 (Sierra)
* CKEditor version: 4.6.2
* Installed CKEditor plugins:

**Comment by mlewand** [comment] 2017-06-29 21:18
Duplicate of #424.

This has been fixed  in 4.7.1.

**Closed by mlewand** 2017-06-29 21:18 UTC
