### ISSUE TITLE
CKFinder Quickupload integration got broken due to latest changes in CKEditor 4.9.0

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1835] opened 2018-03-23 13:43 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Download CKFinder 3.4.2 for PHP or ASP.NET and install it on a server
2. Open `ckfinder/samples/ckeditor.html` and change editor version from 4.5.10 to 4.9.0
3. Upload a file through upload tab

### Expected result

The request should look more or less like below and upload should finish with success:
`http://test.dev/ckfinder-aspnet-342/connector?command=QuickUpload&type=Files&CKEditor=editor1&CKEditorFuncNum=0&langCode=pl`

### Actual result

The request looks like below and CKFinder returns `109 Invalid Request` error what results in HTTP 400 being returned:
`http://test.dev/ckfinder-aspnet-342/connector?command=QuickUpload&type=Files`

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.9.0
* Installed CKEditor plugins: filebrowser

CKEditor 4.9.0
![cke49](https://user-images.githubusercontent.com/5314687/37832291-730eed20-2ea8-11e8-9a6c-65a5c5a1579b.png)

CKEditor 4.8.0
![cke48](https://user-images.githubusercontent.com/5314687/37832294-752f1d82-2ea8-11e8-8766-1ce72eb8fdd5.png)

**Comment by AnnaTomanek** [comment] 2018-03-23 14:04
Can confirm, something's wrong, can be reproduced on the SDK samples as well. When trying to upload files through the Upload tab, an error is returned.
![screen shot 2018-03-23 at 15 01 30](https://user-images.githubusercontent.com/538321/37833296-3acb46fe-2eab-11e8-80a5-c61e04baa9c1.png)
The console:
![screen shot 2018-03-23 at 15 03 39](https://user-images.githubusercontent.com/538321/37833371-6806c62a-2eab-11e8-8c1a-4615812d415b.png)

**Comment by Comandeer** [comment] 2018-03-24 21:19
It seems that the issue is connected with configuration. Setting config to:

```javascript
config.filebrowserBrowseUrl = '/ckfinder/ckfinder.html';
config.filebrowserUploadUrl = '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json';
```

or to

```javascript
config.filebrowserBrowseUrl = '/ckfinder/ckfinder.html';
config.filebrowserUploadMethod = 'form';
config.filebrowserUploadUrl = '/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files';
```

fixes the issue.

What's more, even when CKEditor shows "Incorrect server response", the upload is done. The only issue is with reading the server's answer due to incorrect format (CKFinder responds with JS code by default and XHR uploader is waiting for JSON).

**Comment by mlewand** [comment] 2018-03-26 15:51
Fixed by #1840.

**Closed by mlewand** 2018-03-26 15:51 UTC
Labels: plugin:filebrowser, regression, status:confirmed, target:minor, type:bug

**Comment by jonnott** [comment] 2018-04-06 20:03
Am I right in thinking this only fixes CKFinder v3.x, and not CKFinder v2.x ?
Doesn't seem to make a different to v2.4 or v2.4.2 - same error 'Incorrect server response' occurs.
Guess there's no responseType query string param in v2.x ?

**Comment by jonnott** [comment] 2018-04-06 21:56
As integration with CKFinder v2.x worked perfectly fine until CKEditor v4.9.x, I'd consider this to be a BC break/regression still, and therefore this merge not a satisfactory resolution, unless there has been a point previously where CKEditor's support for CKFinder v2.x has been officially dropped in a major version release...?

**Comment by jonnott** [comment] 2018-04-06 21:57
@mlewand motioning to re-open the issue ;)
