### ISSUE TITLE
List elements get reversed while pasting from OneNote 

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#853] opened 2017-09-01 10:43 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Create a 3 element list in OneNote page
2. While cursor blinks in second or third element use Ctrl + A twice to select the entire list (The first Ctrl + A selects single list item in OneNote)
3. Press Ctrl + C
4. Paste into CKEditor with Ctrl + V

### Expected result

List gets pasted as it was created in OneNote

### Actual result

List gets pasted with elements in reverse order

## Other details

* Browser: Chrome, Firefox
* OS: Win
* CKEditor version: 4.7.0+ (I could not reproduce this issue in CKEditor 4.6.2 or below)
* Installed CKEditor plugins: N/A

**Comment by jswiderski** [comment] 2017-09-01 10:52
I have tested this issue in OneNote 2010 but the original reporter also had this result in version 2016.

The list pasted from OneNote looks like below:

```
<ul style="margin-left:.2847in;direction:ltr;unicode-bidi:embed;margin-top:
 0in;margin-bottom:0in">
 <ul type="disc" style="margin-left:.375in;direction:ltr;unicode-bidi:embed;
  margin-top:0in;margin-bottom:0in">
  <li style="margin-top:0;margin-bottom:0;vertical-align:middle"><span style="font-family:Calibri;font-size:11.0pt">123</span></li>
  <li style="margin-top:0;margin-bottom:0;vertical-align:middle"><span style="font-family:Calibri;font-size:11.0pt">456</span></li>
  <li style="margin-top:0;margin-bottom:0;vertical-align:middle"><span style="font-family:Calibri;font-size:11.0pt">789</span></li>
 </ul>
</ul>
```

As you can see there is double UL element what results in the editor as list inside the list element. This result can still be observed in IE11 and Edge while it has gone in Chrome and Firefox in version 4.7.0. Maybe it has something to do with reversing the order.

**Comment by jswiderski** [comment] 2017-09-01 10:56
[OneNoteIssue.zip](https://github.com/ckeditor/ckeditor-dev/files/1269978/OneNoteIssue.zip)

Sample screen-cast showing the problem.

**Comment by mlewand** [comment] 2017-09-01 11:30
This is a duplicate of #796, let's open it and see what is going on, and why exactly the markup is wrong.

**Closed by mlewand** 2017-09-01 11:30 UTC
Labels: status:confirmed, support, type:bug
