### ISSUE TITLE
Div getting added to the html source

### ISSUE THREAD

**Issue by tenoriojuann** [ckeditor/ckeditor-dev#2449] opened 2018-10-01 12:53 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Enter html content
2. Click Source to view the Raw HTML

### Expected result

View the raw HTML

### Actual result

I get the raw HTML PLUS
`<div id="level-access-access-assistant-highlight-container"></div>`

## Other details

This seems to be a Chrome issue since when I use safari I do not get this problem.

Is there a way to block certain words/characters from being added?

P.S. We are using the ckeditor within CloudCMS

* Browser: Chrome
* OS: Mac
* CKEditor version: 4.x
* Installed CKEditor plugins: Default and custom plugins

**Comment by mlewand** [comment] 2018-10-01 13:10
Sorry but your report does not contain enough information for us to reproduce the problem. Please provide a step by step reproduction instruction based on [latest CKEditor sample](http://cdn.ckeditor.com/4.10.1/full/samples/).

**Comment by mlewand** [comment] 2018-10-16 07:48
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-10-16 07:48 UTC
Labels: resolution:expired
