### ISSUE TITLE
Enter Mode of BR creates &#8203; zero width character in CKEditor 4.7.1 inline mode

### ISSUE THREAD

**Issue by bpatel331** [ckeditor/ckeditor-dev#713] opened 2017-08-01 18:14 UTC
## Are you reporting a feature request or a bug? Bug

Using CKEditor version 4.7.1 in inline mode with Enter mode set to CKEDITOR.ENTER_BR. Open editor to type text with keyboard and press <Enter>. Examining the source html elements, there are several &#8203; characters inserted. This causes an issue because if you want to delete the last line with a Backspace, you have to click backspace key multiple times to delete all the extra &#8203; characters that were just inserted. This seems to only be an issue with Chrome browser 60.0.3112.78 (64-bit)

## Provide detailed reproduction steps (if any)

1. … Create editor in inline mode with Enter mode set to BR
2. … Type some text and press enter once
3. … Press <backspace> key to delete the previous line

### Expected result

You have to press <backspace> key multiple times to delete the line

### Actual result

Should only have to press <backspace> once to delete the line

## Other details

* Browser: Chrome 64-bit 60.0.3112.78
* OS: Windows 10 64-bit OS Build: 14393.1358
* CKEditor version: 4.7.1
* Installed CKEditor plugins: sourcedialog

**Comment by beatadelura** [comment] 2017-08-02 08:44
@bpatel331 I can't reproduce this issue with CKEditor version 4.7.1. Could you please provide [codepen](https://codepen.io/), [jsbin](https://jsbin.com/?html,output) or [jsfiddle](https://jsfiddle.net/) example with configuration and also check whether this bug occurs [here](http://sdk.ckeditor.com/samples/enterkey.html)?

**Comment by beatadelura** [comment] 2017-08-16 09:26
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by beatadelura** 2017-08-16 09:26 UTC
Labels: status:pending
