### ISSUE TITLE
[Font Size and Family] The default donot work when the style setted text among the selection.

### ISSUE THREAD

**Issue by woody-li** [ckeditor/ckeditor-dev#2864] opened 2019-02-26 08:51 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. set some text font family/size.
2. select text include the text just operated( not at start ).
3. select default option in font family/size combobox.

or
1. set several font family/size in a word.
2. select the word.
3. select the default option.

### Expected result

Font family/size set to default in whole text.

### Actual result

Only reset the text at start.
Nothing happened when the text with font family/size setted donot at start of selection.

## Other details

* Browser: all
* OS: all
* CKEditor version: 4.11.2
* Installed CKEditor plugins: Font Size and Family

**Comment by jacekbogdanski** [comment] 2019-03-21 09:04
Duplicate of #1116, #1186

**Closed by jacekbogdanski** 2019-03-21 09:04 UTC
