### ISSUE TITLE
 The edges of the table cells disappears when using divarea

### ISSUE THREAD

**Issue by juliocorral** [ckeditor/ckeditor-dev#1491] opened 2018-01-24 10:00 UTC
I need to use the DIVAREA plugin because the editor loads after an AJAX call. 
If I don't use that plugin the editor doesn't appear when making the call.

But now when I insert a table the edges of the table cells disappear.

Actual configuration:
CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	// config.uiColor = '#AADC6E';
	
	config.language = 'es';
	config.uiColor = '#cccccc';
	config.extraPlugins = 'divarea';
	// config.entities = false;
	// config.entities_greek = false;
	// config.entities_latin = false;
	config.toolbarGroups = [
		{ name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
		{ name: 'forms', groups: [ 'forms' ] },
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
		{ name: 'links', groups: [ 'links' ] },
		{ name: 'insert', groups: [ 'insert' ] },
		{ name: 'styles', groups: [ 'styles' ] },
		{ name: 'colors', groups: [ 'colors' ] },
		{ name: 'tools', groups: [ 'tools' ] },
		{ name: 'others', groups: [ 'others' ] },
		{ name: 'about', groups: [ 'about' ] }
	];

	config.removeButtons = 'Save,NewPage,Print,Templates,Cut,Copy,Paste,PasteFromWord,SelectAll,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,CopyFormatting,RemoveFormat,Outdent,Indent,CreateDiv,BidiLtr,BidiRtl,Language,Anchor,Image,Flash,Smiley,PageBreak,Iframe,Styles,Format,Font,FontSize,TextColor,BGColor,ShowBlocks,About,Maximize';

CKEditor version: 4.8.0
Installed CKEditor plugins: divarea

**Comment by msamsel** [comment] 2018-01-25 08:53
You can use classic editor with AJAX call, you don't have to use divarea.
In case of divarea, you inheritance CSS from your main page, so most probably reason is that you clear table border with your own CSS.

I test it here and table borders seems to work fine: https://cdn.ckeditor.com/4.8.0/full-all/samples/old/ajax.html

**Comment by juliocorral** [comment] 2018-01-25 10:07
The problem is not the refresh of the content within the editor but the editor itself.

I press a button and the editor loads in a call to a PHP file that loads using AJAX and when I do not use the DIVAREA the editor does not even appear when loading by AJAX its space is blank.

For that we use the DIVAREA so that at least it appears. So when using that plugin we get the editor to appear but then the edges of the table do not work.

If it were possible that in the editor load through AJAX the editor appeared in its space the problem would be solved surely.

**Comment by msamsel** [comment] 2018-01-25 10:48
I'm sorry but I have problem with understanding what exactly bug yo report.
Please provide clear steps (HTML + JS) to reproduce the problem. Please check [issue template](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md).
It would be helpful to provide also example on page such as codepen.io, jsfiddle.net, etc., the code with mentioned problem to fully understand the case.

**Comment by msamsel** [comment] 2018-03-06 08:30
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2018-03-06 08:30 UTC
Labels: status:pending
