### ISSUE TITLE
Cannot copy paste in chrome using only ckeditor ( no plugin)

### ISSUE THREAD

**Issue by rupeeright** [ckeditor/ckeditor-dev#1292] opened 2017-11-30 16:09 UTC
BUG
## Provide detailed reproduction steps (if any)

1. Install plain vanilla CKEditor and add that to one HTML page.
2. Go to chrome browser. 
3. Copy some image in clipboard try to paste it in CKEditor using Ctrl +v. Nothing happens
4. Copy some image in clipboard try to paste it in CKEditor using Ctrl +v.  One message appears ( wordings may be wrong)  that your browser does not allow to copy this way. Please use Ctrl + v. When use Ctrl +V nothing happens. 

### Expected result

The image will be copy pasted from clipboard

### Actual result

Image is not pasted in the editor.

## Other details

* Browser: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
* OS: Windows 7
* CKEditor version: 4.4.4
* Installed CKEditor plugins:  No extra plugin

**Comment by msamsel** [comment] 2017-12-14 08:57
Hi,
I'd like to follow your instruction but I have some trouble.
What kind of image do you copy to clipboard? From where you copy it and how?
Can you also check if this behaviour is possible to reproduce in current version of editor? https://cdn.ckeditor.com/4.8.0/full-all/samples/

**Comment by mlewand** [comment] 2017-12-28 11:35
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2017-12-28 11:35 UTC
Labels: status:pending
