### ISSUE TITLE
CKEditor removes CRLF

### ISSUE THREAD

**Issue by ezawadzki** [ckeditor/ckeditor-dev#908] opened 2017-09-13 15:51 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Create Django application (1.9.11)
2. Install this package django-ckeditor latest (5.3.0): Install pip install django-ckeditor
3. Create Model with RichTextField like so :

```
from django.db import models
from ckeditor.fields import RichTextField

class Article(models.Model):

    name = models.CharField('name', max_length=512)
    description = RichTextField('description', blank=True)
```

4. Run migrations

5. Register into admin.py:
`admin.site.register(Article)
`
6. Create an Article

7. Replace in database the content by some markdown text with CRLF

### Expected result
Excepted result : the RichTextField has to keep CRLF in preview mode. 
In an existant project, I have sometimes Markdown contents, sometimes HTML. 
I need to support Markdown content, at least not removing CRLF. I just need that.

### Actual result
Everything goes on one line. CRLF are removed.
If you have a tips to keep them, a property to set, a config...
I tried to print the result of `editor.getSnapshot()` and the raw text keeps CRLF. In configuration, I printed too property `lineBreakChars` from writer object, and it is a CRLF char.
I also already tested to delete all `\r\n` or `0D0A` regex in ckeditor library, but it does not work.

## Other details

* Browser: Chrome 60.0.3112.78
* OS: Debian Stretch
* CKEditor version: 4.7 (wrapped with Django CKEditor)
* Installed CKEditor plugins: No Plugins
 
I already asked my question on stackoverflow :
https://stackoverflow.com/questions/46152913/ckeditor-removes-crlf

**Comment by msamsel** [comment] 2017-09-21 08:04
Hi @ezawadzki,

There is no official integration between CKEditor and Django, that's why I cannot help you with case related strictly to Django issue.
In case that problem exists in CKEditor, please provide reproduction steps, which requires JS + HTML only.

**Comment by msamsel** [comment] 2017-10-17 07:42
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-10-17 07:42 UTC
Labels: status:pending
