### ISSUE TITLE
Pasting text in a SPAN tag, in an A tag

### ISSUE THREAD

**Issue by Utar94** [ckeditor/ckeditor-dev#2024] opened 2018-05-28 17:35 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. You need an anchor tag with a SPAN tag inside, with text inside the SPAN tag.
2. Select some text in the SPAN tag and paste text into it.

### Expected result

The selected text gets replaced by the pasted text.

### Actual result

The anchor structure gets duplicated. There is one anchor containing a SPAN containing the text before my selection. Another anchor gets created, sibling to the first one. This new anchor contains two SPAN ; one contains the pasted text, and the other contains the text after my selection.

## Other details

* Browser: Google Chrome 66.0.3359.181 64-bits
* OS: Windows 10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: basicstyles, clipboard, contextmenu, dialog, enterkey, entities, fakeobjects, find, floatingspace, floating-tools, floatpanel, font, fontawesome, format, htmlwriter, imageresize, imagerotate, indent, indentblock, indentlist, justify, list, listblock, liststyle, menu, menubutton, nbsp, onchange, panel, pastefromword, pastetext, popup, quicktable, removeformat, resize, richcombo, showblocks, showborders, stylescombo, stylesheetparser, tab, table, tabletools, toolbar, undo, wysiwygarea

**Comment by msamsel** [comment] 2018-05-29 07:44
I'm not able to reproduce any duplication. Here is my test sample: https://codepen.io/msamsel/pen/xzxxPr?editors=1010
Please provide more details how to reproduce the issue.

**Comment by Utar94** [comment] 2018-05-31 18:45
I am not able to reproduce the issue in the link you provided me. However, I may be able to reproduce it on [https://ckeditor.com/ckeditor-4/#article](https://ckeditor.com/ckeditor-4/#article).
More details incoming.

**Comment by mlewand** [comment] 2018-07-26 09:52
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-07-26 09:52 UTC
Labels: status:pending
