### ISSUE TITLE
It is not possible to add new list items under an item containing block element

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2205] opened 2018-07-05 13:08 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open editor sample and clean editor contents - https://sdk.ckeditor.com/samples/fullpreset.html.
2. Insert list.
3. Type text in first list item e.g. "test" and press Enter.
4. Insert table in second list item, move below the table using arrows and press Enter.

Please see attached video to get a visual representation of what I’m describing.
[table.zip](https://github.com/ckeditor/ckeditor-dev/files/2166667/table.zip)

### Expected result

Third list item gets created.

### Actual result

Second item together with table is being removed.

## Other details

Problem with removing list item together with a table can be reproduced from CKEditor 4.4.3 however first problems started occurring in version 4.3.0 where it was no longer possible to create new list item but instead new lines were added to second item of the list.

* Browser: Any
* OS: Any
* CKEditor version: 4.4.3+
* Installed CKEditor plugins: table

**Comment by jacekbogdanski** [comment] 2018-10-22 11:59
This issue applies to any block element e.g. tables, forms etc. It's caused by `enterkey` plugin which incorrectly handles opening new line for block elements: https://github.com/ckeditor/ckeditor-dev/blob/major/core/editable.js#L395-L398

**Comment by Comandeer** [comment] 2019-01-02 12:41
Fix was merged into 4.11.2 release.

**Closed by Comandeer** 2019-01-02 12:41 UTC
Labels: status:confirmed, support:1, target:minor, type:bug
