### ISSUE TITLE
Ckeditor 4 editor.getSelection().getRanges()[ 0 ] incorrect result in Internet Explorer

### ISSUE THREAD

**Issue by emersis** [ckeditor/ckeditor-dev#633] opened 2017-07-10 14:51 UTC
Hi!
I have been looking into this issue for a few days now and I really can't find any way to fix  :(.
The ckeditor version which is used in the application i am working on, is CKEditor 4.5.9.
When i try to get the current selection, the following code snippet returns different result in firefox and internet explorer:

```
var range = editor.getSelection() && editor.getSelection().getRanges() && editor.getSelection().getRanges()[ 0 ],
              startNode = (range ? range.startContainer : null), result = {};
```

For example the user is typing the following string in the editor "br
 20" and as result we have startNode.textContent = "br 20" in 
firefox(v.54.0.1), but the same scenario done in IE(v IE 11) has as result 
startNode.textContent = "20". Can somebody give an advise how can be 
fixed this difference in IE? The correct value in IE should be "br 20". 
Thank you in advance!
Firefox:
![ckeditor firefox](https://user-images.githubusercontent.com/15948005/28024005-324cc516-6598-11e7-9966-b00a4c9b332c.png)
IE:
![ckeditor ie](https://user-images.githubusercontent.com/15948005/28024006-3278c4f4-6598-11e7-87f3-564a40a4bc6a.png)

**Comment by wojtekw92** [comment] 2017-07-11 08:29
Hi, 
Did you try to reproduce issue on the last version of CKEditor(4.7.1)?

**Comment by emersis** [comment] 2017-07-11 13:52
Hi wojtekw92!
Yes, i did test it with the last version of CKEditor(4.7.1) but unfortunately the result is the same :( :
**FireFox:**
![firefox](https://user-images.githubusercontent.com/15948005/28071616-1ce7c088-6659-11e7-903e-f07e38a5758c.JPG)
**IE:**
![internet explorer](https://user-images.githubusercontent.com/15948005/28071615-1cdc81a0-6659-11e7-8fcd-8f13b74e3c07.png)

**Comment by wojtekw92** [comment] 2017-07-12 09:28
Hi, unfortunately I was not able to reproduce this issue on IE11. Can you check what is previous sibling of your selected node. Maybe your text node is just splitted in IE and you have to normalize this text nodes.

**Comment by beatadelura** [comment] 2017-07-26 14:17
@emersis It's been a while since we asked you for more information. Because there is no answer, I'm closing this issue.

**Closed by beatadelura** 2017-07-26 14:17 UTC
Labels: status:pending
