### ISSUE TITLE
CKEDITOR.dtd do not allow on keeping `div` element inside `a` element.

### ISSUE THREAD

**Issue by kdy0210** [ckeditor/ckeditor-dev#610] opened 2017-07-05 17:10 UTC
## Description:
As a CKEditor User, I would like to have possibility to use HTML5 structure which allows on Block-level links. This will allow me on keeping `div` elements inside `a` elements. https://stackoverflow.com/questions/6061869/are-block-level-elements-allowed-inside-inline-level-elements-in-html5

## Are you reporting a feature or a bug?
Feature

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. try to save html &lt;a href="google.ca"&gt;&lt;div class="test"&gt;google&lt;div&gt;&lt;/a&gt; which respects HTML5 specification.

### Expected result
&lt;a href="google.ca"&gt;&lt;div class="test"&gt;google&lt;div&gt;&lt;/a&gt;

### Actual result
&lt;div class="test"&gt;&lt;a href="google.ca"&gt;google&lt;/a&gt;&lt;div&gt;

## Other details

* Browser: all browsers
* OS:Win
* CKEditor version:4.6.1
* Installed CKEditor plugins: …

**Comment by msamsel** [comment] 2017-07-06 07:36
Hi,

your problem is not related to ACF. ACF filter out unwanted elements, here is just reordered structure. Responsible for such behave is DTD: http://docs.ckeditor.com/#!/api/CKEDITOR.dtd which prevents of having block type element inside inline elements.
Your request is more like feature request which will change this behave. You can also try to ask community on StackOverflow, maybe someone already had such situation and was able to fix it.

**Comment by msamsel** [comment] 2017-07-06 08:29
I've made some updates of description, to reflect more properly given situation.

**Comment by mlewand** [comment] 2017-07-27 08:50
Duplicate of #514.

**Closed by mlewand** 2017-07-27 08:50 UTC
Labels: status:confirmed, type:feature
