### ISSUE TITLE
Table selection behave wrongly when tfoot is located before tbody

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1664] opened 2018-02-13 09:01 UTC
## Are you reporting a feature request or a bug?

bug

## Provide detailed reproduction steps (if any)

1. Open our sample page
2. Insert table where `<tfoot>` is placed before `<tbody>`:
```
<table border="1">
	<tfoot>
		<tr>
			<th scope="col">Column 1</th>
			<th scope="col">Column 2</th>
			<th scope="col">Column 3</th>
			<th scope="col">Column 4</th>
		</tr>
	</tfoot>
	<tbody>
		<tr>
			<td>Cell 1.1</td>
			<td>Cell 1.2</td>
			<td>Cell 1.3</td>
			<td>Cell 1.4</td>
		</tr>
		<tr>
			<td>Cell 2.1</td>
			<td>Cell 2.2</td>
			<td>Cell 2.3</td>
			<td>Cell 2.4</td>
		</tr>
		<tr>
			<td>Cell 3.1</td>
			<td>Cell 3.2</td>
			<td>Cell 3.3</td>
			<td>Cell 3.4</td>
		</tr>
		<tr>
			<td>Cell 4.1</td>
			<td>Cell 4.2</td>
			<td>Cell 4.3</td>
			<td>Cell 4.4</td>
		</tr>
		<tr>
			<td>Cell 5.1</td>
			<td>Cell 5.2</td>
			<td>Cell 5.3</td>
			<td>Cell 5.4</td>
		</tr>
	</tbody>
</table>
```
3. Use `tableselection` to select cells containing `<tfoot>`
![feb-13-2018 09-55-57](https://user-images.githubusercontent.com/9017322/36141300-7ede97e4-10a4-11e8-92c4-d29f018332b5.gif)

### Expected result

Table is selected properly

### Actual result

Selection is trimmed to tfoot and one additional row.

## Other details

* Browser: Tested on Chrome, Safari
* OS: MacOS
* CKEditor version: 4.9.0
* Installed CKEditor plugins: tableselection

**Comment by Comandeer** [comment] 2018-06-25 13:18
Seems like duplicate of #465.

**Closed by Comandeer** 2018-06-25 13:18 UTC
Labels: plugin:tableselection, status:confirmed, type:bug
