### ISSUE TITLE
Suggestion Bar on smartphone enters gibberish instead of actual words

### ISSUE THREAD

**Issue by mgshamster** [ckeditor/ckeditor-dev#1677] opened 2018-02-14 15:31 UTC
Reporting a bug.

When using my android smart phone (details below), I often use the suggestion bar to correct or complete words. When using ckeditor, the correction does not match the word I selected. Instead, it enters some combination of the before and after version of the word. It happens at random, but it is very frequent.

Additionally, when double tapping the space bar to insert a period, the period is placed after the first space instead of after the word. So sentences end up looking like this .

This seems to only be occurring on sites that use ckeditor. I don't have this issue on Facebook or Google search or any of my texting apps or any of the other forums I frequent (such as Giants in the Playground or Paizo.com). I've only tested this on two sites that use this editor: fark.com and the demo site for ckeditor.

## Provide detailed reproduction steps (if any)

1. Open the demo test box (currently shows an article about Apollo 11)
2. Select any word
3. Select the matching word that appears in the suggestion bar
4. Sometimes the word will change to the correct version, sometimes nothing will happen, sometimes it will blend the original and the new word together.

### Expected result

Replacement of the corrected word should be correct.

Example 1 (from Fark.com): When i use the suggestion box to auto-complete words as i type or to go back and correctly spell a word, the keyboard doesn't replace the word in text with the word in the suggestion box.

Example 2 (from ckeditor demo page): Apollo 11 was the spaceflight that landed the first humans, Americans Neil Armstrong and Buzz Aldrin, on the Moon on July 20th, 1969, at 20:18 UTC.

### Actual result

The word is replaced with gibberish.

Example 1 (from Fark.com): When i uus the suggessugg box to auauto-comple words as i tyty or to go baba and corcorrec spesp a worw, tht keyboard doesn't replace tht word in text witw the wowo ii tht sugsuggest bob.

Example 2 (from ckeditor demo page): ApolAp 11 was tht spaceflspac that landel the first humahu, AmericAme NeNe ArmstrArm ana Buzz Aldrin, on the Moon on JulJ 20th, 1969, at 20:18 UTC.

## Other details

* Browser: Chrome 64.0.3282.137
* OS: Android Moto Z Droid, Version 7.1.1; XT1650 Build/NCLS26.118-23-13-6-1 (reports of others on Fark.com having the same issue; I was directed here by one of the fellow commenters there). 
Smart Phone Keyboard: Gboard (version 6.9.8.183626756-release-arm64-v8a) and SwiftKey Keyboard (version 6.7.7.17)
* CKEditor version: Occurs on Fark.com and on this website's demo text box as of today. Whatever version that is.
* Installed CKEditor plugins: …

**Comment by mgshamster** [comment] 2018-02-14 15:58
I've also tried Firefox (Version 25.0.2) and Opera Mini (Version 32.0.2254.123747) apps. There seems to be no issues on either of those web browsers. It may be a Chrome issue only.

**Comment by camogli** [comment] 2018-02-28 03:41
We've gotten a few user reports on this.  A user sent in this video of the issue occurring: https://drive.google.com/file/d/13bQIomGdMR0ymUOBS-LnssMjf1H-NQTL/view

The user also said that the best way to reproduce it is to type half a word, then pick one of the three options it gives you. Typing the complete word or using the flow method seems to work as normal

**Comment by jacekbogdanski** [comment] 2018-03-05 09:21
Hello,

I tried to reproduce the issue with Android 6.0.1 and Chrome 64.0.3282.137 but it works fine with CKEDITOR 4.8.0 and nightly build. @msamsel, @engineering-this could you try to reproduce the issue?

**Comment by engineering-this** [comment] 2018-03-05 12:39
Can't reproduce it.

Android 7.0, Chrome 64.0.3282.137, Switft Key 6.7.8.25

**Comment by mlewand** [comment] 2018-05-10 10:02
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-05-10 10:02 UTC
Labels: status:pending
