### ISSUE TITLE
empty list/array brackets gets removed by Ckeditor

### ISSUE THREAD

**Issue by metulburr** [ckeditor/ckeditor-dev#1102] opened 2017-10-29 14:06 UTC
for example when using the editor with python in the codebox

```
lst = []
for i in range(5):
    lst.append(i)
 
print(lst)
```

This will get turned into this by Ckeditor

```
lst = 
for i in range(5):
    lst.append(i)
 
print(lst)
```

**Comment by msamsel** [comment] 2017-10-31 10:25
If you understand as `codebox` plugin `codesnippet`, then I'm not able to reproduce it.
Tested here: https://cdn.ckeditor.com/4.7.3/full-all/samples/old/codesnippet/codesnippet.html.

please provide reproduction steps according to our bug report template: https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md

**Comment by msamsel** [comment] 2017-11-09 08:53
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-11-09 08:53 UTC
Labels: status:pending
