### ISSUE TITLE
Enhanced Image plugin bug

### ISSUE THREAD

**Issue by ngybnc** [ckeditor/ckeditor-dev#2586] opened 2018-11-07 13:42 UTC
There is a small bug with the "Enhanced Image plugin"

1. Insert an image, in my case I have inserted one with (16x16px)
2. Enlarge it with "Click and drag to resize", 
3. Double click and check the size, let say now the new size is: 200x200px
4. Shrink it with the same technique 
5. double click to image and the decreased image properties shows the previous enlarged size (200x200px)

For better a understanding I can send a screen video.

Expected result

After shrinking  the image the image properties must update also.

Actual result

After shrinking the image the image properties does not update.

Not OS and browser dependent.

**Comment by jacekbogdanski** [comment] 2018-11-09 09:58
Hello,

I'm not able to reproduce the issue. You can see how I tested it on enclosed gif:
![enlargeimage](https://user-images.githubusercontent.com/10279586/48255896-48642d80-e40e-11e8-9b67-2ae652670e2f.gif)
Could you provide more information about the issue?

**Comment by ngybnc** [comment] 2018-11-09 10:52
Hello,

Thank you very much for the quick feedback. Unfortunately I can still reproduce the issue with your demo. Attached is my screen video. 
[CKEditor Enahnced img problem.zip](https://github.com/ckeditor/ckeditor-dev/files/2565553/CKEditor.Enahnced.img.problem.zip)

**Comment by jacekbogdanski** [comment] 2018-11-09 12:46
What CKEditor version do you use? Can you reproduce the issue with the latest CKEditor (currently 4.11.1)?

**Comment by jacekbogdanski** [comment] 2018-11-23 11:51
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-11-23 11:51 UTC
Labels: resolution:expired

**Comment by ngybnc** [comment] 2018-12-05 10:53
Hello sorry for late response.
The problem still exists with you latest demo :( 
As the screen video shows you can reproduce here: https://sdk.ckeditor.com/samples/image2.html
Unfortunately I have to reopen the issue :(.

Thank you very much!
