### ISSUE TITLE
Bug with unicode characters

### ISSUE THREAD

**Issue by daniel-geiselhart** [ckeditor/ckeditor-dev#2123] opened 2018-06-20 17:46 UTC
Bug

i have been able to reproduce this a few times without external copy and paste
it has been difficult and non-reliable though. mainly i type a whole bunch then highlight copy and paste it below with a lot of line breaks
turns out that we are getting special unicode characters sometimes in the ckeditor sent up to the server
specifically, we are getting U+0080 and U+008B  which is control + partial line forward

Reproduction Steps:

1. …
2. …
3. …

### Expected result

That there isn't unicode characters saved into the editor.

### Actual result

There are unicode characters sporadically in the ckeditor. (very rare)

## Other details

* Browser: all
* OS: windows
* CKEditor version:  4.5.11

**Comment by jacekbogdanski** [comment] 2018-06-21 07:51
Hello,

As I understand you are able to verify that additional Unicode characters have been added by investigating a bunch of data on your backend server?

Are you able to reproduce this issue using our latest CKEditor without external plugins not created by CKSource? It's very hard to verify your issue thus we don't have sample data to reproduce it.

The first step is updating CKEditor to the latest version, please give us information if it helped.

**Comment by jacekbogdanski** [comment] 2018-07-09 08:05
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-07-09 08:05 UTC
Labels: resolution:expired
