### ISSUE TITLE
ckeditor reloads page if there is image in data

### ISSUE THREAD

**Issue by prashant-saxena** [ckeditor/ckeditor-dev#2442] opened 2018-09-28 02:54 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Loading ckeditor from cdn.
2. Html data is loaded from database.
3. If there is an img tag in data, ckeditor is refreshing the page.
4. If there is no img tag in data, there is no reload.
5. In case if img is missing (wrong url), usual black boundary box appears. Clicking on the box open the 'Image Properties' model, which again gives 4 page refresh. 
6. On the very top of my index.php, I have added this:
`file_put_contents('url.txt', $_SERVER['REQUEST_URI'], FILE_APPEND);`
7. Here are the contents of url.txt at the very first time when data is loaded:

> /admin/index.php?page=article&edit=513
/img/burma.jpg

When I click on the missing image box in editor, image properties model opens and the contents of url.txt

> /admin/index.php?page=article&edit=513
/img/burma.jpg
/img/burma.jpg
/img/burma.jpg
/img/burma.jpg
/img/burma.jpg

No idea why it's happening?

 

### Expected result

Stop reloading/refreshing of page.

## Other details

* Browser: Firefox 62.0.2
* OS: Win 7
* CKEditor version: 4.10.1
* Installed CKEditor plugins:

**Comment by msamsel** [comment] 2018-10-01 07:34
Hi @prashant-saxena,

I'm not able to reproduce your case. I prepare simple page with an image, but I don't see any additional reloads. https://codepen.io/msamsel/pen/rqVmWZ
Please provide more details how to reproduce the issue.

**Comment by mlewand** [comment] 2018-10-16 07:47
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-10-16 07:47 UTC
Labels: status:pending
