### ISSUE TITLE
Paste from Word strips "mailto" links in IE11

### ISSUE THREAD

**Issue by trgreen17** [ckeditor/ckeditor-dev#1357] opened 2017-12-18 18:12 UTC
Bug

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Go to ckeditor.com demo using **IE11** 
2. Paste from a Word .docx file that contains an href link and a mailto: link

### Expected result

I expect both links to paste correctly.

### Actual result

 The href link pastes fine, but the mailto: link is stripped, and all that remains is `<a>email link</a>`.

## Other details

* Browser: IE 11
* OS: Windows 10
* CKEditor version: 4.8.0 standard
* Installed CKEditor plugins: pastefromword

**Comment by mlewand** [comment] 2017-12-19 17:11
Hi @trgreen17 I have just tried to paste an example email link from Word document to CKE4 demo and it worked just fine:

![image](https://user-images.githubusercontent.com/5353898/34169364-6ff93ace-e4e7-11e7-817d-be58ba61fdf1.png)

Could you tell us a bit more about your setup?

What MS Word version are you using? Ideally if you could create a sample `.docx` file which contains an example (dummy mail) that can not be copy and pasted into CKEditor.

Exact Edge version would be useful too. For me it's:

```
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299
```

**Comment by mlewand** [comment] 2018-01-05 08:51
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by Maxiweb** [comment] 2019-02-04 11:16
I am also getting this issue,

See attached test doc
[testdoc.docx](https://github.com/ckeditor/ckeditor-dev/files/2827660/testdoc.docx)

**Comment by jacekbogdanski** [comment] 2019-02-04 12:37
I'm able to reproduce the issue but only on IE11. Additionally, it seems like if you add the following link, the broken one gets fixed.

**Comment by jacekbogdanski** [comment] 2019-02-04 13:13
OK, after some testing I see that native IE auto-link feature also is not able to fix the issue in clean `contenteditable` element.

You can create your own plugin which will detect this IE11 upstream, however, from our point of view, it's the browser issue, not CKEditor itself.

**Closed** 2019-02-04 13:14 UTC
Labels: browser:ie11, resolution:upstream

**Comment by Maxiweb** [comment] 2019-02-06 12:57
Hey @jacekbogdanski , i will have a look at doing that. Thank you for your time :).
