### ISSUE TITLE
Easy Image sample crashes after reloading

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#1549] opened 2018-01-31 11:39 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open the sample with Easy Image plugin.
2. Press <kbd>Ctrl</kbd> + <kbd>R</kbd> (few times if needed).

### Expected result

Editor loads properly.

### Actual result

Editor loads with the exception in the console.

## Other details

**Error**
```
 SCRIPT5007: Unable to get property '$' of undefined or null reference
```

**GIF**

![bug_cke4](https://user-images.githubusercontent.com/20988892/35620922-f49712da-0682-11e8-80cb-0144700d896f.gif)

* Browser: Edge 16.16299
* OS: Windows 10

**Comment by engineering-this** [comment] 2018-02-05 13:56
Edge occasionally doesn't create body inside document for iframe when loading page. In my opinion that is caused by browser bug not our software, hence I am closing this issue, as upstream.

[Edge issue tracker](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15740284/)

**Closed by engineering-this** 2018-02-05 13:56 UTC
Labels: browser:edge, plugin:easyimage, resolution:upstream, status:confirmed, type:bug
