### ISSUE TITLE
Failing test tests/plugins/easyimage/uploadintegrations

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#2593] opened 2018-11-08 13:59 UTC
## Type of report

Failing test

## Provide description

The test fails on iOS using built version. It's working fine on development.

CKEdtior version: 4.11.1 (not a regression from 4.11.0).

**Comment by jacekbogdanski** [comment] 2018-12-06 10:06
I can no longer reproduce the issue :thinking:

**Comment by engineering-this** [comment] 2018-12-06 10:11
I can't reproduce it on IPad ether. Closing for now, if this test fails again during another release we should either hotfix it or just don't bother with at all.

**Closed by engineering-this** 2018-12-06 10:11 UTC
Labels: browser:ios, status:confirmed, target:minor, type:failingtest
