### ISSUE TITLE
Bullets and number list skips after ENTER key pressed

### ISSUE THREAD

**Issue by biswas-supriyo** [ckeditor/ckeditor-dev#912] opened 2017-09-14 14:33 UTC
## First bug?
**Steps to Replicate** : 
Step 1: Open CK Editor [as a child component for a DataView EXTJS 4.2.1].
Step 2: Switch ON the Number List . Type the sentence. And click ENTER.
Step 3: Number 2 will skipped and 3 will get the focus.

**Error Log** : 
Uncaught TypeError: Cannot read property 'equals' of undefined
    at CKEDITOR.dom.element.getEditor (ckeditor.js:116)
    at CKEDITOR.dom.element.scrollIntoParent (ckeditor.js:111)
    at CKEDITOR.dom.element.scrollIntoView (ckeditor.js:109)
    at CKEDITOR.dom.range.scrollIntoView (ckeditor.js:175)
    at enterBlock (ckeditor.js:791)
    at enterBr (ckeditor.js:793)
    at q (ckeditor.js:784)
    at CKEDITOR.command.exec (ckeditor.js:785)
    at CKEDITOR.command.exec (ckeditor.js:189)
    at a.execCommand (ckeditor.js:259)

**Correction Found** :
**Present cheditor.js:116 line**
f=b[c],f.element.equals(this)&&f.elementMode!=CKEDITOR.ELEMENT_MODE_APPENDTO||!a&&(d=f.editable(),d.equals(this)||d.contains(this))

**Correction**:
f=b[c],f.element.equals(this)&&(d=f.editable(),d.equals(this)||d.contains(this)&&f.elementMode!=CKEDITOR.ELEMENT_MODE_APPENDTO

Can we apply this fix? Any impact?

**Comment by wojtekw92** [comment] 2017-09-15 09:19
Hi,
are you able to reproduce this issue on http://cdn.ckeditor.com/4.7.2/full-all/samples/?

**Comment by biswas-supriyo** [comment] 2017-09-15 14:02
Hi,

As mentioned in the post, by default its working. But when the mentioned steps in the bug post are followed, issue can be replicated.

Even with the correcting bug can be fixed. But not sure about the impacts of it.

**Comment by msamsel** [comment] 2018-01-04 08:13
Hi,
your description points that issue is related with integration CKEditor with some sort of 3rd party software. If bug is related directly to CKEditor, then could you provide reproduction steps with clear JS + HTML, without using any 3rd party software? It could be great, if you could provide an example page (jsfiddle.net, codepen.io, etc.).

**Comment by jacekbogdanski** [comment] 2018-01-19 08:32
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed** 2018-01-19 08:32 UTC
Labels: resolution:expired
