### ISSUE TITLE
Add SCAYT and WSC changelog entry

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#2109] opened 2018-06-19 14:42 UTC
## Type of report

Task

## Provide description of the task

Add SCAYT and WSC changelog entry

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by mlewand** [comment] 2018-06-19 14:48
Duplicate of #2050 😜.

**Closed** 2018-06-19 14:48 UTC
Labels: resolution:duplicate
