### ISSUE TITLE
Cell Properties Does Not Prime RowSpan and ColSpan Values

### ISSUE THREAD

**Issue by rkarina** [ckeditor/ckeditor-dev#3143] opened 2019-05-30 01:56 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a 3 x 3 table.
2. Right click on a cell and merge it with the next cell.
3. Right click on that same cell and merge with the row above/below.
4. Right click on that same cell and naviagte to Cell Properties.

### Expected result

Cell Properties dialog opens up with the RowSpan and ColSpan attribute values primed.

### Actual result

Cell Properties dialog opens up with the RowSpan and ColSpan attribute values not displaying correctly (empty input fields).

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.11.3
* Installed CKEditor plugins: Default plugins, tabletools, tableresize, etc.

**Comment by f1ames** [comment] 2019-05-30 06:21
Hello @rkarina,

thanks for reporting. I have some issue with the 3rd step in your description, from what I see two merged cells cannot be merged to row above/below if the number of cells in these rows is different:

![image](https://user-images.githubusercontent.com/1061942/58612633-8abe6080-82b3-11e9-8c06-fb94819a78a1.png)

Checked on full preset - https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html.

**Comment by rkarina** [comment] 2019-05-30 06:23
Hey mate, 

Thanks for the reply. Right, sorry can you also merge the bottom two cells for this instance?

**Comment by f1ames** [comment] 2019-05-30 06:28
> can you also merge the bottom two cells for this instance?

Yes, but then `Span`s values are correct 🤔Maybe you have some specific/complex HTML which causes this issue?

![image](https://user-images.githubusercontent.com/1061942/58612997-b3932580-82b4-11e9-8337-c00b29629466.png)

**Comment by rkarina** [comment] 2019-05-30 06:29
Interesting. Complex file? Yes indeed. 
[TableSource.txt](https://github.com/ckeditor/ckeditor-dev/files/3235701/TableSource.txt)
Please see attached source and have a play with this if you can.

**Comment by rkarina** [comment] 2019-05-30 06:32
I think this is also related to issue https://github.com/ckeditor/ckeditor-dev/issues/3142. Due to the RowSpan and ColSpan values not being primed, when changing the colour of the cell background after clicking "Ok", the width changes.

**Comment by rkarina** [comment] 2019-05-31 00:06
Was there any luck with this issue @f1ames ?

**Comment by f1ames** [comment] 2019-05-31 10:32
Hello @rkarina,
I tried to reproduce the issue with HTML you provided with no luck (on full preset here - https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html). Maybe you could provide some detailed step by step description or a .gif which will show the whole reproduction scenario?

**Comment by rkarina** [comment] 2019-06-03 01:29
Hello @f1ames ,

I've opened the chrome browser inspector to show you the step that's causing this problem. It occurs on the 'onLoad" event handler after clicking on the "Cell Properties" button. Please see images attached. As you can see, one of the items does not register "getAttributes" as a function, which seems to be the underlying cause of this issue.

![CellPropError#2](https://user-images.githubusercontent.com/19806920/58770477-87e4a800-85f2-11e9-90a7-55242b397534.PNG)
![CellPropError#1](https://user-images.githubusercontent.com/19806920/58770478-887d3e80-85f2-11e9-8ca7-2bf840093dda.PNG)

**Comment by rkarina** [comment] 2019-06-03 02:09
See attached link for a screencast of the issue: https://www.screencast.com/t/ajJeSccSEO4m

**Comment by rkarina** [comment] 2019-06-05 23:23
Is there a follow up to this issue @f1ames ? Please let me know at your most convenience.

**Comment by f1ames** [comment] 2019-06-10 10:10
Hello @rkarina,
would it be possible to provide the screencast in a different format than `.swf` or make it downloadable (I don't see any option to download it TBH)? I'm not able to watch it in a browser and also can't download it to use a desktop app to play it, which makes it impossible to watch for me.

**Comment by f1ames** [comment] 2019-07-08 11:34
@rkarina I checked the screencast and tried to reproduce the issue on [Full Preset](https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html) and editor with [ACF off](https://ckeditor.com/docs/ckeditor4/latest/examples/acf.html) still with no luck.

Can you check if you can reproduce it there (so on `4.12.1` version) and also if it's reproducible on editor instance without any 3rd-party plugins (in your case looking at the config from https://github.com/ckeditor/ckeditor-dev/issues/3142#issue-450080696 I see there are around 10 3rd-part plugins)?

**Comment by Dumluregn** [comment] 2019-07-23 17:06
Hi @rkarina, it's been a while since we last heard from you. We're closing this issue for now. Still, feel free to provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2019-07-23 17:06 UTC
Labels: status:pending, type:bug
