### ISSUE TITLE
Emoji dropdown icons are not centered

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#2572] opened 2018-11-05 12:57 UTC
## Type of report

Bug/task

## Provide detailed reproduction steps (if any)

1. Open test:
`/tests/plugins/emoji/manual/dropdown/dropdownfiltering`

2. Open emoji dropdown.

3. Press <kbd>left arrow</kbd> to focus category icons. Inspect each of them.

## Actual:

Category icons are not centered, below is how they look when focused. I propose to adjust their positioning so each of them is centered horizontally and vertically. Currently they are aligned top which doesn't look good especially with smaller icons.

![screenshot 2018-11-05 at 13 46 16](https://user-images.githubusercontent.com/23366849/47999018-76412d80-e101-11e8-9bec-616792881ef8.png)

## Second case:

4. Hover an emoji to show preview.

## Actual:

Emoji preview icon is positioned too high and almost touches top border. See below:

![screenshot 2018-11-05 at 12 46 48](https://user-images.githubusercontent.com/23366849/47999111-ccae6c00-e101-11e8-9d79-9d0cb318ca6a.png)

I propose to add some `margin-top` to this icon to position it better.

Note: currently there is `padding-top` on parent element, preview text has additional `margin-top:3px`. I think same value would be ideal for icon.

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment] 2018-11-08 14:23
There is also a small issue with gab between emoji panel input border and outline, which could be fixed altogether with this one:

![image](https://user-images.githubusercontent.com/10279586/48204490-37fa7700-e36a-11e8-92e0-f9ab2b39b343.png)

It occurs on Chrome.

**Comment by msamsel** [comment] 2018-12-11 14:55
@jacekbogdanski I cannot reproduce this case. I looked on Chrome under Windows and MacOS and this situation doesn't occur for me. Maybe you have set some zoom or made some customisation in browsers, which result with this visual glitch?

**Comment by mlewand** [comment] 2019-02-13 14:59
Fixed with #2670.

**Closed by mlewand** 2019-02-13 14:59 UTC
Labels: easy, plugin:emoji, status:confirmed, target:minor, type:bug
