### ISSUE TITLE
Undo event slow in CKeditor

### ISSUE THREAD

**Issue by sakthisudhan82** [ckeditor/ckeditor-dev#567] opened 2017-06-27 04:44 UTC
I have faced in CKEditor slow response when we triggered undo event, if more than 1000 paragraphs in mozilla firefox browser

**Comment by f1ames** [comment] 2017-06-27 06:36
Hello @sakthisudhan82,
could you provide more detailed reproduction steps and information about your environment as asked in the issue template?

**Comment by beatadelura** [comment] 2017-07-11 07:22
It's been a long time since @sakthisudhan82 created this issue. Because there is no answer, I'm closing it.

**Closed by beatadelura** 2017-07-11 07:22 UTC
