### ISSUE TITLE
IE11 crash on Windows10 when using ckeditor with ATOK-IME

### ISSUE THREAD

**Issue by khi-oku** [ckeditor/ckeditor-dev#1381] opened 2017-12-27 09:00 UTC
## Are you reporting a feature request or a bug?
type:bug

## Provide detailed reproduction steps (if any)
1. Type a character in the CKEditor  
2. Drag all entered characters and choose Cut from right click menu  
3. Move the focus outside the text area  
4. Return focus to the text area (click bottom of textarea)  
5. Type a character  

### Expected result
*What is the expected result of the above steps?*
No crash is exepcted result.

### Actual result
*What is the actual result of the above steps?*
IE crash message is displayed.
I have reproduced it on the official demo site of ckeditor.
![reproduce](https://user-images.githubusercontent.com/34855370/34376478-446e30aa-eb2f-11e7-9660-052b9628f20e.gif)

## Other details
* Browser:IE11
* OS:Windows10 Pro 64bit (Japanese)
* CKEditor version:4.8 (demo site)
* Installed CKEditor plugins: full (demo site)
* IME: ATOK

**Comment by msamsel** [comment] 2018-01-10 09:08
Hi,
I suspect that problem is related to IME. Could you provide information how to configure this IME under Windows and duplicate your environment? I wasn't able to reproduce this bug with standard keyboard.

**Comment by engineering-this** [comment] 2018-01-24 08:21
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by engineering-this** 2018-01-24 08:21 UTC
Labels: status:pending
