### ISSUE TITLE
It's not posible to resize the height of a table with table resize in chrome

### ISSUE THREAD

**Issue by PHP-GLOBE** [ckeditor/ckeditor-dev#2754] opened 2019-01-15 13:57 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a table
2. resize with drag and drop (it is only possible to alter the with, not the height

### Expected result

*What is the expected result of the above steps?*
It should be possible to adjust height of a table by drag and drop (works in Firefox)

### Actual result

*What is the actual result of the above steps?*
It's not possible to resize the height of the table

## Other details

* Browser: Chrome
* OS: Ubuntu/Windows 10
* CKEditor version: 4.11.2
* Installed CKEditor plugins: (it's does not work in the demo as well)

**Comment by Comandeer** [comment] 2019-01-15 14:06
Table Resize plugin is dedicated for changing only width of columns. The fact that rows can be resized in Firefox is connected with the fact that Firefox has its own native controls for resizing tables. Therefore it's not really a bug, as plugin works as intended. I'll mark this ticket as feature request.

**Comment by Comandeer** [comment] 2019-01-15 14:07
In fact this ticket is a duplicate of #737.

**Closed by Comandeer** 2019-01-15 14:07 UTC
