### ISSUE TITLE
[Edge browser] Image (img elements) with display:block inline style adds <br /> automatically after I select it and then click outside of ckeditor

### ISSUE THREAD

**Issue by vunguyen2712** [ckeditor/ckeditor-dev#2835] opened 2019-02-20 22:28 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open Ckeditor on Edge browser
2. Insert an image, find that `img` element using Inspect Element
3. Select the `img` element that you just inserted and add `display:block` as a new inline style
4. Left Click to select the image on the page
5. Left Click outside of ckeditor

### Expected result
`<br />` should not be added before the `img` automatically

### Actual result
`<br />` is added before the `img` automatically every time I select and then click outside of the editor

### Gif on how to reproduce
![img-adds-breaks-edge](https://user-images.githubusercontent.com/6036771/53129305-1178da00-351c-11e9-965d-8c9cb018765b.gif)

## Other details

* Browser:  Microsoft Edge 42.17134.1.0 (It does not occur on Chrome, Firefox, IE)
* OS: Windows 10
* CKEditor version: 4.11.1 (Inline Editor)
* Installed CKEditor plugins: image

**Comment by jacekbogdanski** [comment] 2019-02-26 08:40
Hello,

I would like to learn more about the issue you are trying to solve by modifying image styles. Could you provide more information about the context of the CSS style change? Direct `display` property change may create some issues but it also may be the reason why it's not set as a block by default, which qualifies this issue as `by design` rather than a bug.

**Comment by vunguyen2712** [comment] 2019-02-26 21:51
Hi @jacekbogdanski ,
Thanks for responding. In my app, I use ckeditor to allow user to edit html templates. An html template in my app could come with an `img` tag which has `display:block` as its inline style. Thus, this issue happens (on Edge browser only)

I tried reproduce this issue on a cke4 demo which has Source plugin (https://ckeditor.com/docs/ckeditor4/latest/examples/sourcearea.html) but Source plugin does not allow adding inline styles. Therefore, I tried to reproduce it by editing directly in devMode.

**Comment by jacekbogdanski** [comment] 2019-04-24 08:40
I'm no longer able to reproduce the issue using CKEditor 4.11.4. Could you give a try the latest CKEditor version?

**Comment by vunguyen2712** [comment] 2019-05-24 21:28
Hi @jacekbogdanski ,
Thanks for helping. I apologize for my late response. I'm still able to reproduce the issue on this demo page (Edge browser only). The demo page is using CKE 4.11.4
https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html

**Comment by jacekbogdanski** [comment] 2019-06-11 08:26
I see that `float:left` style is required to reproduce the issue, so as an example the issue is reproducible with:

```html
<img src="https://via.placeholder.com/100" style="display:block; float: left" />
```
using inline editor. 

Nevertheless, the issue doesn't seem to cause any visual issue and `br` tags are removed when retrieving HTML from an editor (using e.g. `editor.getData` function). I'm closing this issue as it doesn't create any real problem from my perspective, however, if you still have any issue with internal `br` tag, feel free to comment so we can reopen this ticket.

**Closed by jacekbogdanski** 2019-06-11 08:26 UTC
Labels: status:pending
