### ISSUE TITLE
In article mode, 'Outdent','Indent' button only works on the list

### ISSUE THREAD

**Issue by yaphot** [ckeditor/ckeditor-dev#3341] opened 2019-08-16 11:03 UTC
https://ckeditor.com/ckeditor-4/demo/#article
article editor In article mode, 'Outdent','Indent' button only works on the list;
but other mode,'Outdent','Indent' button always works

**Comment by Dumluregn** [comment] 2019-08-16 15:23
Thank you for bringing our attention to this. As a matter of fact it's not a bug - just the plugin [Indent Block](https://ckeditor.com/cke4/addon/indentblock) is currently not included in Article Mode. However as it appears in other modes, we decided that it makes sense to unify this behaviour on our webpage, which makes your issue rather a task than bug.

**Comment by f1ames** [comment] 2019-08-19 12:23
Moved this issue to websites repository, closing this one.

**Closed by f1ames** 2019-08-19 12:23 UTC
Labels: status:confirmed, type:task, website

**Comment by yaphot** [comment] 2019-08-21 01:54
How can I modify it, it can be same In article mode, because now this problem is treated as a bug.
