### ISSUE TITLE
Got "Uncaught DOMException: Failed to execute 'setEnd' on 'Range'" when operating on a mention

### ISSUE THREAD

**Issue by dennisjsq** [ckeditor/ckeditor-dev#2256] opened 2018-07-25 01:04 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://sdk.ckeditor.com/samples/mentions.html.
2. Make sure that the developer console is open.
3. Mention one of the users, say, "@ ajames" (without the space).
4. Delete the mention added in step 3 one character at a time. 

May need to repeat steps 3 and 4 multiple times for the Exception to happen.

### Expected result

No errors in developer console.

### Actual result

Got the following errors:

Uncaught DOMException: Failed to execute 'setEnd' on 'Range': The offset 6 is larger than the node's length (5).
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.range.getClientRects (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/ckeditor.js:187:3)
    at getViewPosition (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/plugins/autocomplete/plugin.js?t=I6D6:14:470)
    at g.updatePosition (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/plugins/autocomplete/plugin.js?t=I6D6:18:76)
    at f.viewRepositionListener (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/plugins/autocomplete/plugin.js?t=I6D6:11:217)
    at f.<anonymous> (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/plugins/autocomplete/plugin.js?t=I6D6:9:107)
    at a.h (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/ckeditor.js:10:70)
    at a.<anonymous> (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/ckeditor.js:11:433)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fire (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/ckeditor.js:13:97)
    at CKEDITOR.plugins.undo.UndoManager.type (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/ckeditor.js:1079:373)
    at CKEDITOR.plugins.undo.NativeEditingHandler.onKeyup (https://sdk.ckeditor.com/vendor/ckeditor/4.10.0/ckeditor.js:1090:121)

## Other details

* Browser: Chrome, Safari

**Comment by mlewand** [comment] 2018-07-25 09:00
As described it does not reproduce all the time, for me I was able to repro it when I had the inserted mention phrase in the middle of the plain text.

Looks like an issue with our webkit filling characters.

**Comment by jacekbogdanski** [comment] 2018-07-25 09:09
I'm also able to reproduce the issue. It seems like it occurs more often when you start deleting adjacent text node.
![mentionsrangeissue](https://user-images.githubusercontent.com/10279586/43191252-182d6468-8ffb-11e8-892c-a545c416072d.gif)

**Comment by pupi1985** [comment] 2018-08-18 21:53
I can also reproduce this issue. I also faced another one which I randomly get while trying to reproduce this one. Not sure if it is related:
```
plugin.js?t=I6D6:7 Uncaught TypeError: Cannot read property 'element' of null
    at Object.CKEDITOR.plugins.textMatch.getRangeInText (plugin.js?t=I6D6:7)
    at Object.CKEDITOR.plugins.textMatch.match (plugin.js?t=I6D6:6)
    at b.callback (plugin.js?t=I6D6:6)
    at b.<anonymous> (plugin.js?t=I6D6:5)
    at c (ckeditor.js:27)
```

**Comment by engineering-this** [comment] 2018-09-27 12:00
@dennisjsq @pupi1985 thanks for reporting the issue, but I'm closing it as duplicate of #2194. Further discussion should be hold there or in PR #2370 which holds the fix.

**Closed by engineering-this** 2018-09-27 12:00 UTC
Labels: browser:chrome, browser:safari, plugin:mentions, status:confirmed, target:minor, type:bug
