### ISSUE TITLE
BUG : Enter key scroll down the page

### ISSUE THREAD

**Issue by scorpionSaw** [ckeditor/ckeditor-dev#550] opened 2017-06-22 08:00 UTC
Hi,

When I press enter key, the page scroll down. I use ckeditor 4.6.2.

This is my config : 

	 config.enterMode = CKEDITOR.ENTER_BR; 

This bug occurs when there is a scroll on the page.

I don't want to scroll when press enter key...

Can you have a look on it ?

Regards

**Comment by mlewand** [comment] 2017-06-22 08:04
Could  you clarify? It does not scroll on enter, see https://codepen.io/mlewand/pen/dRRVxy

Prepare step by step instruction just as requested in the issue template.

**Comment by scorpionSaw** [comment] 2017-06-22 08:12
You have to have a scroll on the page. Not on the editor.
![2017-06-22 10_12_15-notes test mediweb 310884p 888403016](https://user-images.githubusercontent.com/29623563/27423836-4886e9f6-5733-11e7-8302-b59bad8dd463.png)

**Comment by scorpionSaw** [comment] 2017-06-22 08:17
https://codepen.io/mlewand/pen/dRRVxy

I do not have the problem on codepen.io... Do you have an idea of the source of my problem?

**Comment by scorpionSaw** [comment] 2017-06-22 15:16
Someone has an idea of the problem? :(

**Comment by beatadelura** [comment] 2017-07-20 07:31
@scorpionSaw Unfortunately, I can't reproduce this issue. 

I tried to do it in followed steps:

1. Download and unzip file: [test.zip](https://github.com/ckeditor/ckeditor-dev/files/1161458/test.zip)
2. Open `index.html` in your browser
3. Click somewhere outside the editors
4. Press `Enter` key

Tested on Chrome 59, Firefox 54, Safari, IE11, Edge.

Could you please check attached file and whether my steps are overlapping with yours? If not, please prepare exact step to reproduce and give an information what kind of browser do you use.

**Comment by beatadelura** [comment] 2017-08-03 06:45
@scorpionSaw It's been a while since we asked you for more information. Because there is no answer, I'm closing this issue.

**Closed by beatadelura** 2017-08-03 06:45 UTC
Labels: status:pending

**Comment by monocc** [comment] 2019-08-13 09:17
css 
html and body height do not set 100%
