### ISSUE TITLE
editor window lost focus on enter and navigator scrolls down

### ISSUE THREAD

**Issue by Guanche** [ckeditor/ckeditor-dev#1808] opened 2018-03-17 05:36 UTC
## Are you reporting a feature request or a bug?
Bug

### Expected result

When you type enter at the editor window it should insert a line break and thats all, with the editor focused and no navigator scroll or nothing.

### Actual result

1. Typing enter at the editor window while typing any text causes the navigator window scroll down.
2. The navigator scrollbar get focus and the navigator window does a page scroll down.
3. If you just continue typing it works. No need to scroll up. The editor window get the text and simply the navigator scrolls up and the editor still has focus.

## Other details

* Browser: Chrome.
* OS: Windows 7.
* CKEditor version: CKEDITOR 4.
* Installed CKEditor plugins: many.

**Comment by jacekbogdanski** [comment] 2018-03-19 08:16
Hello,

I couldn't reproduce your issue using our latest stable CKEditor. Could you provide more information about the issue? It's important to provide full CKEditor version (with major and minor release version e.g. 4.8.0) and a minimal editor configuration which you are able to reproduce the issue ( like used plugins, custom changes). 

Are you able to reproduce the issue using our online [CKEditor sample](https://ckeditor.com/latest/samples/)?

**Comment by Vnkdsh** [comment] 2018-03-23 02:44
Hi,

check your css file if your css file have both html and body width & height is 100% . This problem will rise. when you hit enter ck editor consider the whole page height ,so it scrolls down. change your styles to html and body height is auto. like below. It will filx.

body , height {width:auto !important; height:auto !important; }

Thanks

**Comment by jacekbogdanski** [comment] 2018-03-23 07:38
@Vnkdsh thanks for the response! 
@Guanche could you check if @Vnkdsh fix works for you? If so please let me know so I will be sure I can close this issue.

If you still experience the issue it would be great if you could give us some sample with reproduced issue using e.g. [Codepen](https://codepen.io).

**Comment by jacekbogdanski** [comment] 2018-04-06 11:27
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-04-06 11:27 UTC
Labels: resolution:expired
