### ISSUE TITLE
The drag and drop functionality does not work correctly when you drag widgets into a table.

### ISSUE THREAD

**Issue by haroldo-ok** [ckeditor/ckeditor-dev#1695] opened 2018-02-20 11:54 UTC
## Are you reporting a feature request or a bug?

bug

Similarly to issue 520, in version 4.8, the drag and drop functionality does not work correctly when you drag widgets to a table. It only works if you drag it to the very bottom; anywhere else, and it fails.

https://github.com/ckeditor/ckeditor-dev/issues/520

## Provide detailed reproduction steps (if any)

Try dragging any widget to the insides of a table.

### Expected result

It should drop correctly.

### Actual result

It does not allow you to drop anything inside, unless it is at the very bottom of the table.

## Other details

* Browser: Firefox 58.0.2 (64-bit)
* OS: Windows 10
* CKEditor version: 4.8
* Installed CKEditor plugins: justify,table,tabletools,tableresize

**Comment by jacekbogdanski** [comment] 2018-02-21 10:56
Duplicate of #1648.

**Closed by jacekbogdanski** 2018-02-21 10:56 UTC
Labels: resolution:duplicate
