### ISSUE TITLE
table  Inline Editor

### ISSUE THREAD

**Issue by ZengYongMiaoMiao** [ckeditor/ckeditor-dev#1039] opened 2017-10-12 06:20 UTC
table Inline Editor ==> Style Change

## Provide detailed reproduction steps (if any)

1.`< td class="outtd">
< table>
    < tr>< td>title< /td>< /tr>
< /table>
< div id="testckeditor" contenteditable="true">
    test test test test test test test test test test 
< /div>
< script>
    CKEDITOR.disableAutoInline = true;
    CKEDITOR.inline('testckeditor');
< /script>
< /td>`

2.Select Text , Bold
3.< td class="outtd"> ==>  < td class="outtd cke_table-faked-selection">  + "cke_table-faked-selection"???
4.Style Change

## Other details

* Browser: ie11
* OS: win10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: …

**Comment by beatadelura** [comment] 2017-10-12 08:05
@ZengYongMiaoMiao I need more clear information what is this issue about. Could you please provide [codepen](https://codepen.io/), [jsbin](https://jsbin.com/?html,output) or [jsfiddle](https://jsfiddle.net/) example with configuration and exact steps to reproduce? Please fill issue template above properly.

**Comment by beatadelura** [comment] 2017-10-30 08:24
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by beatadelura** 2017-10-30 08:24 UTC
Labels: status:pending
