### ISSUE TITLE
When deleting the last line in a bullet-ed list, formatting on the next line is lost and merged into the bullet-ed list

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#3119] opened 2019-05-20 19:04 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Add a bullet-ed or numbered list of items
2. Add a heading below that list and start a new section
4. highlight the last # or bullet (by double clicking it)
5. click delete
7. notice the following header has now been merged into the list?
8. expected, the line is deleted.

### Expected result

The bulleted line gets deleted

### Actual result

The headings gets merged into the list.

## Other details

* Browser: All
* OS: All
* CKEditor version: 4.11..4
* Installed CKEditor plugins: not relevant

**Comment by jacekbogdanski** [comment] 2019-05-21 07:29
I'm not able to reproduce the issue about pressing `delete` key with the selection at the end of the list. Header gets merged when using `delete` key with empty list item which is visible on the attached gif, although it's expected behavior. Delete key deletes forward, in contrast to `backspace` key which will delete list item instead.

Could you give more information about reproduction steps, your CKEditor configuration and attach some gif showing the issue?

![deletelist](https://user-images.githubusercontent.com/10279586/58076370-53acc880-7baa-11e9-9261-9afc51154b63.gif)

**Comment by zoarif** [comment] 2019-05-22 18:41
@jacekbogdanski try this:

1. Add a bullet-ed or numbered list of items
2. Add a heading below that list and start a new section
3. highlight the last # or bullet (**by clicking three times**)
4. click delete
5. notice the following header has now been merged into the list?
6. expected, the line is deleted.

**Comment by zoarif** [comment] 2019-05-22 22:14
The issue is that CKeditor does not return the right selection when you click three times.

**Comment by jacekbogdanski** [comment] 2019-05-23 08:09
It's the standard behavior of the browser. When you are doing triple-click selection, the selection is ending at the following element, not selected text node. Although, I see it rather as a feature, not an upstream bug. You will have the same behavior for any element, not only list item. During triple-click, the whole line gets selected, not only clicked text.

You can reproduce this behavior also with native contenteditable: https://codepen.io/jacekbogdanski/pen/zQRBYW

**Closed by jacekbogdanski** 2019-05-23 08:09 UTC
Labels: status:pending, type:bug
