### ISSUE TITLE
Move Functionality Overview from Guides to a new Features section

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor-dev#3084] opened 2019-05-07 06:49 UTC
## Type of report

Docs

## Provide a description of requested docs changes

As mentioned in the ["Make integrations more visible"](https://github.com/ckeditor/ckeditor-dev/issues/2990#issuecomment-477130953) discussion, when expanding all our docs under one Umberto engine and porting the SDK to docs, we also planned to move the "Functionality Overview" section to a separate tab, namely "Features". This hasn't happened so far, though.

This would give us a few benefits:
- The Guides category would get less crowded, it's now next to impossible to find something there by glancing at the TOC/sidebar.
- The documentation structure would become similar to CKEditor 5 and thus it would be easier to compare the features that both versions have.
- It would make it easier to send users/customers who are trying to understand the features that we have to one section without overwhelming them with all the other documentation content that we have.

WDYT?

**Comment by f1ames** [comment] 2019-05-14 12:12
Actually, this is a duplicate of #2992, so I'll close this.

**Closed by f1ames** 2019-05-14 12:12 UTC
Labels: type:docs, type:task
