### ISSUE TITLE
Failing test suite: tests/plugins/easyimage/uploadintegrations

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1619] opened 2018-02-08 10:53 UTC
## Are you reporting a feature request or a bug?

bug: failing tests

## Provide detailed reproduction steps (if any)

1. Run test suite on Firefox `tests/plugins/easyimage/uploadintegrations#`. You need to refresh test suite with <kbd>Shift</kbd> button, to skip cache. Problem occurs on developer version also.

![screen shot 2018-02-08 at 11 48 25](https://user-images.githubusercontent.com/9017322/35969208-65116580-0cc6-11e8-94aa-8e502e29b832.png)

### Expected result

test pass

### Actual result

test fails

## Other details

* Browser: Firefox 58.0.2
* OS: MacOS
* CKEditor version: 4.9.0
* Installed CKEditor plugins: full-all

**Comment by mlewand** [comment] 2018-02-08 10:57
Duplicate of #1571.

**Comment by msamsel** [comment] 2018-02-09 10:37
@mlewand It seems to be not duplicated. Fails still occur.

**Comment by mlewand** [comment] 2018-02-09 11:54
I'm seeing only 2 failing tests on major branch:
* `test handling failed uploads`
* `test copy and paste in progress widget while original was loaded`

Which is different from the original report, @msamsel could you confirm the list of failing tests?

**Comment by Comandeer** [comment] 2018-02-09 11:56
@mlewand all tests that contain HTML assertions (`test paste […]`, `test pasting […]`) also fails due to sync assertions.

**Comment by mlewand** [comment] 2018-02-09 11:59
Weird, for me only 2 above tests are failing *randomly*.

**Comment by Comandeer** [comment] 2018-02-09 12:01
@mlewand did you try to disable cache via devtools or force reload?

**Comment by msamsel** [comment] 2018-02-09 12:03
@mlewand, @Comandeer so there probably is difference in between Windows and MacOS version of FireFox :(

**Comment by mlewand** [comment] 2018-02-09 12:04
I'm making just simple refresh with `f5`. Simple this is a random failing test, let's continue and fix it in 4.9.1. We wasted a lot of time on unit tests today.

**Comment by msamsel** [comment] 2018-02-09 12:08
About specific test which fails it's quite hard to say.
I observe 3 different scenarios how it fails.
1. Cleared cache with settings. And fired single test suite - fails 2 tests.
2. Run this same test suite again - fails 1 test, further refresh all tests pass
3. Refresh with skipping cache (pressed <kbd>Shift</kbd>) 5 test fails.

It's hard to say which exactly test are wrong :( Entire test suit should be analysed.

**Comment by mlewand** [comment] 2018-02-09 12:09
I see, thanks @msamsel for the feedback. For me only two tests were affected by random failures that's why I have propsed them.

With fix for this issue we should be able to drop `setTimeout` added in #1571.

**Closed** 2018-06-22 12:22 UTC
Labels: browser:firefox, changelog:skip, status:confirmed, type:failingtest
