### ISSUE TITLE
Links duplicating href value in list of links

### ISSUE THREAD

**Issue by lkosta** [ckeditor/ckeditor-dev#657] opened 2017-07-18 16:36 UTC
## Are you reporting a feature or a bug?
bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. … In ckeditor, select 'Add Media' and navigate to PDF and upload
2. … Hit enter key and repeat linking to another PDF
3. …Hit enter key and repeat linking to another PDF

### Expected result

*What is the expected result of the above steps?*

The expected result is that I have a list of three links, all linking to different PDFs.

### Actual result
List items 2 and 3 are linking to the URL of the PDF in item 1.

*What is the actual result of the above steps?*
The only way I've been able to fix is to go into Source and manually change the fid # of items 2 and 3.  This doesn't happen all the time. 

## Other details

* Browser: …  chrome and firefox
* OS: …  Windows 7 Enterprise
* CKEditor version: … 3.6.6.2.7696
* Installed CKEditor plugins: …

**Comment by msamsel** [comment] 2017-07-19 07:33
Hi,

please check if the problem is possible to reproduce on 4.7.1, and if yes then provide description with configuration details or example code how to achieve it.

**Comment by beatadelura** [comment] 2017-08-02 06:51
@lkosta It's been a while since we asked you for more information. Because there is no answer, I'm closing this issue.

**Closed by beatadelura** 2017-08-02 06:51 UTC
Labels: status:pending
