### ISSUE TITLE
[PFW]: Pasting list elements with numbers removes some of the numbers

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2183] opened 2018-06-27 14:51 UTC
## Type of report

Bug

1. Create Word document with below content:
```
1.	Test 1.2.3.4.5
2.	Test 
```
### Expected result

```
1.	Test 1.2.3.4.5
2.	Test 
```

### Actual result

```
1.	Test 2.3.4.5
2.	Test 
```
Notice that `1` from `Test 1.2.3.4.5` is gone.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.6.0+
* Installed CKEditor plugins: pastefromword

**Comment by msamsel** [comment] 2019-02-19 14:12
@jswiderski it seems like issue doesn't exists any longer since 4.11.2

Can you confirm and close ticket in such case?

**Comment by Comandeer** [comment] 2019-07-18 10:21
Duplicate of #2690, which was fixed in 4.11.2.

**Closed by Comandeer** 2019-07-18 10:21 UTC
Labels: plugin:pastefromword, regression, status:confirmed, type:bug
