### ISSUE TITLE
Pasting list item with number inside the item, removes that number.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1905] opened 2018-04-19 11:17 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open attached docx file and copy whole list from it with `Ctrl+C` [list test.docx](https://github.com/ckeditor/ckeditor-dev/files/1927844/list.test.docx) 
2. Paste list inside the editor with `Ctrl+V`.

### Expected result

Second list item should look like: `2.	line the contains 2. or 3. numbered items `.

### Actual result

Second list item looks like: `2.	line the contains or 3. numbered items `. The 2. has been removed.

## Other details

THis item is not being removed by the browser but by the editor.

* Browser: FF, Chrome, Edge (works fine in IE11)
* OS: Win10 
* CKEditor version: 4.6.0+
* Installed CKEditor plugins: pastefromword

**Comment by Comandeer** [comment] 2019-07-18 10:24
Duplicate of #2690, which was fixed in 4.11.2.

**Closed by Comandeer** 2019-07-18 10:24 UTC
Labels: browser:chrome, browser:edge, browser:firefox, browser:safari, plugin:pastefromword, status:confirmed, type:bug
