### ISSUE TITLE
Cannot copy image from word to IE

### ISSUE THREAD

**Issue by woody-li** [ckeditor/ckeditor-dev#2986] opened 2019-03-27 07:17 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Insert an online picture into word (It got the same result by using image copied from paint).
2. Copy the image.
3. Paste into editor in IE.

### Expected result

The image shows in editor.

### Actual result

Shows a blank picture with src : file:///C:/Users/admin/AppData/Local/Temp/msohtmlclip1/01/clip_image002.png

## Other details

* Browser: IE
* CKEditor version: 4.11.2
* Installed CKEditor plugins: pastefromword

**Comment by jacekbogdanski** [comment] 2019-03-27 09:37
Duplicate of #2869

**Closed by jacekbogdanski** 2019-03-27 09:37 UTC
Labels: type:bug
