### ISSUE TITLE
Multiple editor instances + setData causing errors, blank CKEditors

### ISSUE THREAD

**Issue by samjhill** [ckeditor/ckeditor-dev#879] opened 2017-09-07 14:35 UTC
## Are you reporting a feature request or a bug?

Bug

We are using https://github.com/jdorn/json-editor to render JSON structures into forms, but substituted CKEditor for WYSIWYG content. 

## Provide detailed reproduction steps (if any)

1. Have multiple CKEditors on one page
2. click moveUp/moveDown button in `json-editor`
![image](https://user-images.githubusercontent.com/1424050/30168650-0ca6bc06-93b8-11e7-8508-906f9b3b8e99.png)

### Expected result

Text inside CKEditors is swapped to correct position per the move up/move down instructions

### Actual result

All CKEditor instances become blank and unresponsive. Upon clicking again, I get this error message:
```
ckeditor.js?ver=1504794180601448:399 Uncaught TypeError: Cannot read property 'getSelection' of undefined
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.selection.getNative (ckeditor.js?ver=1504794180601448:399)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.dom.selection (ckeditor.js?ver=1504794180601448:397)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.getSelection (ckeditor.js?ver=1504794180601448:395)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.plugins.undo.Image (ckeditor.js?ver=1504794180601448:1143)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.plugins.undo.UndoManager.save (ckeditor.js?ver=1504794180601448:1138)
    at a.<anonymous> (ckeditor.js?ver=1504794180601448:1134)
    at a.d (ckeditor.js?ver=1504794180601448:10)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.event.CKEDITOR.event.fire (ckeditor.js?ver=1504794180601448:11)
    at a.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js?ver=1504794180601448:13)
    at a.setData (ckeditor.js?ver=1504794180601448:241)
```

## Other details
When I prevent CKEditor from rendering, and instead allow `json-editor` to use a plain textarea, moving them around works fine.

* Browser: Chrome
* OS: mac OS Sierra
* CKEditor version: 4.5.11, also tried 4.7.1
* Installed CKEditor plugins: 
![image](https://user-images.githubusercontent.com/1424050/30168482-8939262e-93b7-11e7-9ddf-a11edf620001.png)

**Comment by msamsel** [comment] 2017-09-11 11:12
Hi,

situation seems to be similar to problem described [here](https://stackoverflow.com/questions/28613526/issue-when-i-move-ckeditor-form) or here #667. And I think your problem also is caused by the same reason.
If it's not, then please prepare some simplified example where problem will be possible to analyse (The best would be some page like: codepen.io, jsfiddle.net, etc.).

**Comment by mlewand** [comment] 2017-09-25 08:03
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2017-09-25 08:03 UTC
Labels: status:pending
