### ISSUE TITLE
CKEditor - Copy/Paste duplicate text

### ISSUE THREAD

**Issue by Kheon** [ckeditor/ckeditor-dev#1495] opened 2018-01-24 16:21 UTC
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

Some closed ticket but still having the problem

## Provide detailed reproduction steps (if any)
the bug is hard to reproduce but happens on Firefox ESR
We are using CKEDITOR 4.7.3 in classic mode

In our application we can select some subscribers and leave them a comment (edited with CKEDITOR)
Each times we select a subscriber, we call the CKEDITOR.instances['comment'].setData(data); function.

After a few clicks, when we pasta some text, it's duplicated. We switch again and it's now pasted 4 times, then 6 and so on.

1. call the setData() function several times on the same page.
2. paste some text

### Expected result

Paste the text you've copied

### Actual result

The text is pasted 4 times, then 6 and so on.

## Other details

* Browser: FireFox ESR 52.6.0 (64-bit)
* OS: Tested on Ubuntu 16.04 / Win10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: 'imagebase64,tablestyle'

After some (long) digging in the Ckeditor code, I think I've found the reason :

Sometimes the clearListeners from "core/editable.js" fails because removeListener fails and as the try is around the while, other listeners aren't removed. So when the setup is executed again, it adds new listeners on top of that uncleared array. And as the catch does nothing, it was hard to find out. 
It would be better to put the try bloc into the while loop.

```js
			/**
			 * Remove all event listeners registered from {@link #attachListener}.
			 */
			clearListeners: function() {
				var listeners = this._.listeners;
				// Don't get broken by this.
				try {
					while ( listeners.length )
						listeners.pop().removeListener();
				} catch ( e ) {}
}

```
Secondly, why is the function removeListener() failing ?

This method is in `core/event.js` L149 :
```js
function removeListener() {
	me.removeListener( eventName, listenerFunction );
}
```
or the var "me" is declared in the if statement few lines later (L167), so if the condition is false, then me is never defined. 

I managed to fix the problem by declaring the "var me = this;" before the function.

It seems the bug was introduced by https://github.com/ckeditor/ckeditor-dev/commit/f3e78849a1972f034bb54943d297310f50a929c8

Can you fix it, please ?

**Comment by mlewand** [comment] 2018-01-29 09:24
Thanks for digging in @Kheon. Have you verified that it happens _only on Firefox_? And is it only FF ESR?

Secondly it we would need some kind of a setup where one could reproduce the issue with 100% cases. It would be nice if you could prepare some sort of codepen/jsfiddle snippet, where there are multiple instances of CKEditors, with having `setData()` called on them, so that the issue that you're describing occurs there.

**Comment by Kheon** [comment] 2018-02-13 10:55
Hi, 

Sorry, i didn't manage to find out which listener failed to remove and why. 
It works fine when you didn't have an error with a listener, but, imho the problem i've pointed in the code is still obvious.

**Comment by tjanasiewicz** [comment] 2019-01-07 07:43
Hi @mlewand do we have any news here?
Could you please provide information about release version in which this issue will be fixed?
Thank you.

**Comment by jacekbogdanski** [comment] 2019-07-08 10:40
Hello, I didn't manage to reproduce the issue. @Kheon , @tjanasiewicz could you provide more precise reproduction steps, so we can understand the issue?

**Comment by engineering-this** [comment] 2019-07-23 09:10
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by engineering-this** 2019-07-23 09:10 UTC
Labels: status:pending, type:bug

**Comment by arturo1212** [comment] 2020-01-15 16:36
Just in case someone's facing the same issue, I was able to reproduce/fix the issue just realizing that
**IF** you have multiple editor divs with the same ID like

>`<div name='editor1' id='editor1' contenteditable='true'></div>`
>`<div name='editor1' id='editor1' contenteditable='true'></div>`

Using `CKEDITOR.inline('editor1', CKEDITOR.config)` will reproduce the issue, while  `CKEDITOR.replace('editor1', CKEDITOR.config)` will work as expected.
So, if you really need multiple editors with the same ID (idk why) you should consider using replace(). If you don't, maybe checking for this in your code could help.
**Note:** I'm referencing the library from https://cdn.ckeditor.com/4.13.0/full-all/ckeditor.js
