### ISSUE TITLE
InsertHTML with class or Mathjax insert Fails

### ISSUE THREAD

**Issue by sarankup** [ckeditor/ckeditor-dev#2218] opened 2018-07-11 23:25 UTC
## Type of report

Bug

Here is my configuration.
```
CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	// config.uiColor = '#AADC6E';
	config.language = 'en';
	config.mathJaxLib = '//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS_HTML';
	config.mathJaxClass = 'my-math';
	config.extraPlugins = ['htmlcomments','htmlcitations','mathjax'];	
	//https://stackoverflow.com/questions/15659390/ckeditor-automatically-strips-classes-from-div
	config.allowedContent = true;
	config.stylesSet = 'my_styles';
	config.removePlugins = ['a11ychecker','balloonpanel','div','divarea','texzilla','format','contents','balloontoolbar','autosave','letterspacing','newpage','codesnippet','toc','stylesheetparser','mathedit','footnotes','crossreference','codeTag','mathedit'];
	config.extraAllowedContent = '*{*}(*)';
};

```
If I insert content like `editor.insertHtml('<span data-cool="foo">new tet</span>');` this works fine. But, if I add @class attribute like  `editor.insertHtml('<span class="foo">new tet</span>');`  I got the following error. The same error appears even when I insert MathJax equations.
```
ckeditor.js:2036 Uncaught TypeError: f is not a function
    at D (ckeditor.js:2036)
    at ckeditor.js:2036
    at Array.forEach (<anonymous>)
    at C (ckeditor.js:2036)
    at L._onPaste (ckeditor.js:2067)
    at a.n (ckeditor.js:10)
    at a.<anonymous> (ckeditor.js:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at a.insertHtml (ckeditor.js:286)
    at <anonymous>:1:14
D @ ckeditor.js:2036
(anonymous) @ ckeditor.js:2036
C @ ckeditor.js:2036
_onPaste @ ckeditor.js:2067
n @ ckeditor.js:10
(anonymous) @ ckeditor.js:12
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13
insertHtml @ ckeditor.js:286
(anonymous) @ VM3736:1
```

### Expected result

`<span class="foo">new tet</span>`

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome
* OS: Macintosh
* CKEditor version:4
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment] 2018-07-17 08:31
Hello,

I wasn't able to reproduce your issue with the latest `4.10.0` CKEditor version. Could you check if the issue exists with CKEditor `4.10.0` and with minimal editor configuration e.g. without external plugins? The issue could be caused by third-party add-ons.

**Comment by jacekbogdanski** [comment] 2018-08-06 07:39
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-08-06 07:39 UTC
Labels: resolution:expired
