### ISSUE TITLE
Throttling function

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-dev#1993] opened 2018-05-21 13:39 UTC
## Type of report

Feature request

## Provide description of the new feature

Throttling function is required to implement #1972 feature. We need a throttling function that can accept, and pass arguments in the throttled function.

Note that the function should work the same way as [eventBuffer](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_tools.html#method-eventsBuffer) does in terms of being called, so, say you have a throttling set to 100 ms and you have following calls:

call no. | time offset (relative to first call)
---------|----------
 1 | 0ms
 2 | 20ms
 3 | 40ms
 4 | 120ms

The throttled function should be executed thee times with following offsets:

 time offset |
---------- |
 0ms |
 100ms |
 200ms |

Please see https://github.com/ckeditor/ckeditor-dev/pull/1983#issuecomment-390646788 discussion for more information about requirements.

**Comment by mlewand** [comment] 2018-06-01 12:58
Pull request has been merged to the Autocomplete feature branch (#1751). It will automatically get merged with it.

**Comment by mlewand** [comment] 2018-06-19 12:13
Fixed in #1751.

**Closed by mlewand** 2018-06-19 12:13 UTC
Labels: changelog:api, status:confirmed, target:major, type:feature

**Comment by f4h4m** [comment] 2019-12-01 21:03
plugin.js?t=H4PG:160 Uncaught TypeError: CKEDITOR.tools.throttle is not a function
    at new TextWatcher (plugin.js?t=H4PG:160)
    at Autocomplete.getTextWatcher (plugin.js?t=H4PG:413)
    at new Autocomplete (plugin.js?t=H4PG:200)
    at new Mentions (plugin.js?t=H4PG:125)
    at plugin.js?t=H4PG:26
    at Object.forEach (ckeditor.js:48)
    at a.<anonymous> (plugin.js?t=H4PG:25)
    at a.n (ckeditor.js:10)
    at a.<anonymous> (ckeditor.js:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)

**Comment by skuchibhotla** [comment] 2020-12-14 23:33
I am also getting the very same error what @fahamjv had mentioned in his last post. Is there a known resolution to this issue? I don't see a throttle() function in CKEDITOR.tools. Or, am I missing something? 
<img width="726" alt="Screen Shot 2020-12-14 at 3 32 42 PM" src="https://user-images.githubusercontent.com/23178583/102148650-b5362700-3e21-11eb-903b-c1af31cd848d.png">

**Comment by Dumluregn** [comment] 2020-12-15 08:20
Hello, you can find the `CKEDITOR.tools.throttle()` method in both [API docs](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools.html#method-throttle) and [code](https://github.com/ckeditor/ckeditor4/blob/1aa21195bda3e4cfb4f19fa70d5a285b56965d70/core/tools.js#L584-L587), so I don't understand the problem here. As for the error, we need the reproduction steps and demo that lead to it - without it we are not able to tell anything. Please, create a new issue and follow the issue template you'll encounter.

**Comment by skuchibhotla** [comment] 2020-12-16 00:37
@Dumluregn Thank you for such a prompt reply. It was a mistake at my end. After going through the documentation, realized I needed to upgrade my CKEditor to a later version to have the throttle() function since it was introduced in 4.11.0. Thank you once again :)
