### ISSUE TITLE
stylesheetparser randomly does not flood the styles combo with classes

### ISSUE THREAD

**Issue by clarumedia** [ckeditor/ckeditor-dev#2122] opened 2018-06-20 15:28 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Use stylesheetparser to pull in a CSS file via contentsCss 

### Expected result
Styles combo always populated with valid styles from CSS file

### Actual result
Sometimes the styles combo is correctly populated, sometimes not. Keep reloading the page until it works. (Never works with cache disabled)

## Other details
I put an Alert into the LoadStylesCSS function of stylesheetparser/plugin.js  and realized there was a race condition going on.

* Browser: …Firefox 60
* OS: …Ununtu 17.10
* CKEditor version: …4.9.2
* Installed CKEditor plugins: showprotected,stylesheetparser, dialogui,dialog,dialogadvtab,basicstyles,bidi,blockquote,clipboard,button,panelbutton,panel,floatpanel,colorbutton,colordialog,menu,contextmenu,div,resize,toolbar,elementspath,enterkey,entities,popup,filebrowser,find,fakeobjects,floatingspace,listblock,richcombo,font,format,horizontalrule,htmlwriter,iframe,wysiwygarea,image,indent,indentblock,indentlist,smiley,justify,menubutton,link,list,liststyle,magicline,maximize,pagebreak,pastetext,pastefromword,removeformat,showblocks,showborders,sourcearea,specialchar,scayt,stylescombo,tab,table,tabletools,undo,wsc

**Comment by msamsel** [comment] 2018-06-21 08:35
Unfortunately your description is too brief. Please provide better reproduction steps or demo page, which will allow on easy bug reproduction.

**Comment by jacekbogdanski** [comment] 2018-07-09 08:06
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-07-09 08:06 UTC
Labels: resolution:expired
