### ISSUE TITLE
Pasting content from MS Outlook ->  resulting HTML-structure

### ISSUE THREAD

**Issue by testecos** [ckeditor/ckeditor-dev#2314] opened 2018-08-15 13:57 UTC
## Type of report

Bug  -> according the HMTL- structure after content is past to an editor

* unexpacted / strange HTML structure 
* result contains too many span's and multiple styles

## Provide detailed reproduction steps (if any)

1. open editor
2. implemtenting a text like

`<p><strong>Name 1 </strong> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>`

3. add or replace some of the text with something copied from an outlook e-mail

### Expected result

the implemented text should look like the rest and not have 5-6 nested spans with multiple style definitions

### Actual result

`<p><strong>Name 1 </strong> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting <span style="font-size:11pt"><span style="text-autospace:none"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="font-size:10.0pt" lang="EN-US"><span style="font-family:&quot;Arial&quot;,sans-serif"><span style="color:black">THIS PART WAS COPIED FROM OUTLOOK</span></span></span></span></span></span><br></p>`

## Other details

* Browser: FF 61.0.2  and Chrome 68.0
* OS: Windows 10 
* CKEditor version: 4.9.2
* Installed CKEditor plugins: panel, image, button, floatpanel, listblock, richcombo, format, basicstyles, table, tabletools, tableresize ,autogrow

Can also be tested with 
a) https://sdk.ckeditor.com/samples/pastefromword.html   (get's the bad structure)
b) https://sdk.ckeditor.com/samples/copyformatting.html  (just getting one surrounding span)
c) https://sdk.ckeditor.com/samples/basicstyles.html          (just implementing the text)

**Comment by msamsel** [comment] 2018-08-20 08:29
Hi @testecos,

I've tried to reproduce reported situation with MS Outlook 2013 but won't appear there.
Please also notice that we support [pasting from Word](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_pastefromword.html) and [pasting from Excel](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_pastefromexcel.html), more details you can read in linked articles.

As content pasted from Outlook might be similar to Word, there is a chance that paste from Word filters will remove unnecessary tags from its content also. You can manipulate what content is preserved in editor by defining proper filter rules in [ACF](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_content_filter.html)

You can check what kind of content is in clipboard before it's pasted to editor on [this page](https://codepen.io/mlewand/pen/xqwRJb). This might give you an overview what is copied from Outlook and what kind of markup is provided by this application.

If you still want to have support for outlook, then please provide more details about your environment. Especially about outlook version, which might produce different markup. And I will make feature request from this issue then.

**Comment by msamsel** [comment] 2018-09-03 07:46
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2018-09-03 07:46 UTC
Labels: status:pending
