### ISSUE TITLE
Problem with URLs being garbaged

### ISSUE THREAD

**Issue by stephenl314** [ckeditor/ckeditor-dev#2680] opened 2018-12-15 15:34 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Using $('#ParentageNotes').val( CKEDITOR.instances.ParentageNotes.getData() ); to grab data out of a textarea
2. If textarea has a URL "http ... " is changed to "“http ...”"
3. A new set of those odd-quotes is added every time you exit the editor (and getData is run)
4. It doesn't look like the "odd" quotes are displaying correctly here and I can't get a correct ASCII code using ASC(). They look like the quotes you get when pulling in something from Word. Possibly rdquo and ldquo

### Expected result

A properly formatted URL.

### Actual result

Extra quote marks that look like rdquo and ldquo with new one added each time the textarea is accessed.

## Other details

Happens in every browser
Windows 7
4
link

**Comment by Comandeer** [comment] 2018-12-17 10:16
I can't reproduce it. Can you provide the demo of the issue?

**Comment by Comandeer** [comment] 2019-01-05 13:36
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Comandeer** 2019-01-05 13:36 UTC
Labels: status:pending

**Comment by stephenl314** [comment] 2019-06-26 12:43
I received a notice you’re closing this because you haven’t heard from me. I sent my reply several days ago via gmail. Here it is.

Go to http://basketbasics.com/gen/
You'll see a field with a ? button after it.
Enter      CKEditor         and click the button.
It will come back with just the Entry button showing. Click it.
This will take you the record of Test Case.
Click on General Notes. When you click the Done button on the notes it hides the div (closes the notes) and

  1.  Calls  $('#GeneralNotes').val( CKEDITOR.instances.GeneralNotes.getData() )
  2.  For you, it will then pop up an alert so you can see the value
So, you're in General Notes and it's empty. Add a URL (e.g., copy and paste the address of the page). Look at the source code to verify it's properly formatted. You'll see the popup that shows it's properly formatted.
Click on Parrish, Denver Forrest. This forces a save to the table and, since it's you, brings you right back to Test Case. (If you get a data error, try again. For some reason I'm having issues connecting to the server. If it connects you'll detect the screen clearing and re-formatting.)
Click on General Notes and look at the source. The weird quotes have been added.
Click Done then on Parrish, Denver Forrest again. A second set of weird quotes has been added. New quotes will be added every time you save the record.
