### ISSUE TITLE
Autoembed does not work when valid link pasted into table cell

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-dev#705] opened 2017-08-01 06:35 UTC
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

None.

## Provide detailed reproduction steps (if any)

1. Go to http://sdk.ckeditor.com/samples/mediaembed.html.
2. Replace editor content with simple table, e.g.
```
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<thead>
		<tr>
			<th scope="col">1</th>
			<th scope="col">2</th>
			<th scope="col">3</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>a</td>
			<td>b</td>
			<td>c</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</tbody>
</table>
```
3. Copy and paste one of the sample URLs into an empty or selected table cell.

### Expected result

Pasted link is auto embedded.

### Actual result

Link is pasted as a plain text.

## Other details

**It works only in a scenario when pasted with collapsed selection in non-empty cell. All other cases fails.**

* Browser: Checked on Chrome
* OS: OS X
* CKEditor version: 4.7.1

**Comment by mlewand** [comment] 2017-08-08 21:55
Duplicate of #520.

**Closed by mlewand** 2017-08-08 21:55 UTC
Labels: plugin:tableselection, regression, status:confirmed, type:bug
