### ISSUE TITLE
Many "<p>&nbsp;</p>" will be displayed when use some special html tag.

### ISSUE THREAD

**Issue by no1412** [ckeditor/ckeditor-dev#1379] opened 2017-12-26 10:08 UTC
## **Bug**

**Reproduce Example Link:**
https://codepen.io/code_li/pen/OzWMBB
## Provide detailed reproduction steps (if any)

1. Config a property: **`CKEDITOR.config.allowedContent = true;`**
2. Copy a special Html tag, like
**`<asd>asd</asd>`**, 
**`<p<strong>strong</p<strong>`**, 
**`<mytag>mytag</mytag>`** 
or other unusual html tag with a **line feed**
3. Then past the copied html code to a CKEditor source view.
4. Click source button on CKEditor toolbar to switch to Rich Content View, then switch to Source View.

### Expected result
Display the same html code in source view and no any html tag.
like:
**`<asd>asd</asd>`**, 
**`<p<strong>strong</p<strong>`**, 
**`<mytag>mytag</mytag>`** 
### Actual result
Display the same html code in source view and some `<p>&nbsp;</p>`.
**The number of occurrences of  `<p>&nbsp;</p>` will increase with the number of operations.**

Other Link:
https://docs.ckeditor.com/ckeditor4/docs/#!/guide/plugin_sdk_sample

* Browser: Chrome 63.0.3239.84（x64）
* OS:Windows 7 pro x64
* CKEditor version: 4.7.1

**Comment by no1412** [comment] 2017-12-26 10:15
Reproduce step by image:
1. Setup the config: `CKEDITOR.config.allowedContent = true;`
2. http://prntscr.com/hsderd
3. http://prntscr.com/hsdftf

**Comment by jacekbogdanski** [comment] 2018-01-18 09:34
Hello,

thank you for reporting an error. I can reproduce this issue and it's definitely a bug. We will take care of it as soon as possible.

**Comment by f1ames** [comment] 2018-01-18 10:04
Duplicate of #1410 (@jacekbogdanski please always check for duplicates when confirming issues).

@no1412 please follow #1410 for any updates related to this issue.

**Closed by f1ames** 2018-01-18 10:04 UTC
Labels: status:confirmed, type:bug

**Comment by no1412** [comment] 2018-01-18 11:53
Thanks all.
we found if we add this code under **\plugins\htmlwriter\plugin.js** in method **$: function()**
could resolve this issue:
But don't know if exists other potential problem.
```
           this.setRules('p', { 
                indent: 0,
                breakBeforeOpen: 0,
                breakAfterOpen: 0,
                breakBeforeClose: 0,
                breakAfterClose: 0,
                needsSpace: 0
            }); 
```
