### ISSUE TITLE
Special entities in entities_additional may break escaping

### ISSUE THREAD

**Issue by Deroin** [ckeditor/ckeditor-dev#2448] opened 2018-10-01 12:39 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1) Initialize CKE with `entities_additional` set to `'apos'`
2) Enter text `amp'` into the editor
3) Switch to source view

### Expected result

Source view shows `<p>amp&apos;</p>`

### Actual result

Source view shows `<p>&undefined;&undefined;&undefined;&apos;</p>`

## Other details

* Browser: Firefox, Chrome
* OS: Debian, Windows
* CKEditor version: 4.10.1
* Installed CKEditor plugins: Default plugins as in development version

I pinned this down to be caused by `plugins/entities/plugin.js::buildTable`. During the replacement of `entities` in line 63 any special entity will be removed from the entities list together with the following `,`. If there is no comma (because it is the last value) the resulting ends with a comma.

This causes `entities.split(...)` to create an array with empty string as last value while the `join` then creates a string ending with `&;` which will be replaced by `&amp;;` when reading inner HTML.
Due to this `a`, `m` and `p` will be interpreted as entities by CKE.

**Comment by msamsel** [comment] 2018-10-02 07:47
I was able to reproduce the issue here: https://codepen.io/msamsel/pen/GYpEvv

**Comment by mlewand** [comment] 2018-10-16 07:44
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by mlewand** [comment] 2018-10-16 07:44
_Closed wrong issue, reopening._

**Closed** 2018-10-24 08:50 UTC
Labels: easy, status:confirmed, target:minor, type:bug
