### ISSUE TITLE
Additional styles added to style attribute after adding/removing styles

### ISSUE THREAD

**Issue by beatadelura** [ckeditor/ckeditor-dev#473] opened 2017-06-06 14:45 UTC
## Are you reporting a feature or a bug?

Bug

## Issue is already reported

https://dev.ckeditor.com/ticket/14629

## Provide detailed reproduction steps (if any)

1. Update find_highlight config option to: `config.find_highlight = { element : 'span', styles : { 'background-color' : '#004', 'color' : '#fff', 'border' : '1px solid #004' } };`
2. Open any CKEditor sample and type some text, e.g. test.
3. Open Find & Replace dialog.
4. Click 'Find' button to search for a word, e.g. test.
5. Click 'Cancel' button.
6. Switch to 'Source' view.

### Expected result

`test` word shouldn't be wrapped with span tag: `<span style="border-image: none;">test</span>`

### Actual result

`test` word has been wrapped with span tag: `<span style="border-image: none;">test</span>`

## Other details

* Browser: IE11, Edge
* CKEditor version: 4.7.0

The same issue is reproducible using `CKEDITOR.style` and `removeFromRange` method: (https://jsfiddle.net/gzg23t1v/)

**Comment by beatadelura** [comment] 2017-06-07 08:06
It seems like a bug on Edge and IE11. I created an issue [here](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12263408/). Waiting for the answer.

**Comment by mlewand** [comment] 2017-06-13 08:26
This is caused by bug in IE/Edge style handling, and Microsoft marked it as a won't fix. We could add a ton of hacks in core system for IE/Edge but it's not justifying it.

**Closed by mlewand** 2017-06-13 08:26 UTC
Labels: browser:edge, browser:ie11, status:pending, type:bug
