### ISSUE TITLE
scrollIntoView null or undefined with IE11

### ISSUE THREAD

**Issue by ophian** [ckeditor/ckeditor-dev#761] opened 2017-08-10 18:07 UTC
This is a **bug** (in my eyes).

I came across a bug with Internet Explorer 11, while Firefox and Chrome are working fine.
This was already filed in 2014
https://ckeditor.com/forums/Support/scrollIntoView-throwing-undefined

In my case it is an iframed page redirecting to (calling) a javascript function closing the popup
``` javascript
....
        if (parent.self.opener == undefined) {
            parent.self = window.parent.parent.$.magnificPopup;
            parent.self.opener = window.parent.parent;
        }
        // add to textarea and close
        parent.self.opener.imageSelectorToBody(gallery, textarea);
        parent.self.close();
```

The failing code part:

``` javascript
scrollIntoView:function(){this.type!=CKEDITOR.SELECTION_NONE&&this.getRanges()[0].scrollIntoView()}
```

The solution:

```javascript
scrollIntoView:function(){if(this.type && this.getRanges()[0]){this.type!=CKEDITOR.SELECTION_NONE&&this.getRanges()[0].scrollIntoView()}}
```

IE inserts the items to the textarea, but fails closing the iframe popup page, trowing halt in debugger, even later on it does not close the page.

The translated error message is:
`The "scrollIntoView" property of an undefined or null reference can not be retrieved.`
I have this in CKEditor 4.5.11 as well as in 4.7.1.

The fix mentioned does work with IE11.

Please add this missing check `if(this.type && this.getRanges()[0]){...}`
Thanks

**Comment by beatadelura** [comment] 2017-08-17 09:00
@ophian I can't reproduce this issue with CKEditor version 4.7.1. Could you please provide [codepen](https://codepen.io/), [jsbin](https://jsbin.com/?html,output) or [jsfiddle](https://jsfiddle.net/) example with configuration and exact steps to reproduce?

**Comment by ophian** [comment] 2017-08-17 16:12
@beatadelura Hi. I sadly don't feel being able to **simplify** this down for a reproducible example.
It is so complicated, as 

- being a CKE added gallery toolbar button,
- opening a $.magnific overlay framed Smarty template page,
- playing **ping-pong** with the main administration script,

 to check

 - the gallery images by ID in the framed page,
 - gather and select the checked image data in a $media array and
 - send this assigned as a json_encode($media) js-array to another $.magnific framed page
 - calling the main javascript function, by a simple js redirector script.
 - In there preparing the gallery array by items,
 - calling the parent.self.opener.imageSelectorToBody(gallery, textarea) to insert this bunch to the textarea 
 - and closing  the last calling framed page at the end,

All I know, is that the error is thrown in IE11 and that it can easily be bypassed by the added check.

Thanks.

**Comment by beatadelura** [comment] 2017-08-18 07:21
@ophian I'm not sure but It seems, you are using not official CKEditor plugin for an image gallery. Something like https://ckeditor.com/addon/ckeditor-image-gallery. If so, you should report this issue straight to them.

**Comment by ophian** [comment] 2017-08-18 08:21
@beatadelura No, its not. All build by myself.
CKEditor 4.7.1, full package, 2017-06-28
CKEditor-Plugin: `mediaembed`, v. 0.6+ (https://github.com/frozeman/MediaEmbed, 2016-07-24)
CKEditor-Plugins manually added: `autogrow`, `codesnippet`, `embedbase`, `embed`, `embedsemantic`, `fakeobjects`, `lineutils`, `notification`, `notificationaggregator`, `widget` and `widgetselection` plugins, 2017-07-29)
Some internal added plugins for `help` and `placeholder` and the adhoc added Buttons for `MediaLibrary` and the `Gallery Selection`. All done by custom config. Thats all. This is not using any internal or external image widgets, since that doesn't fit the framework needs. But this is not the problem!

The MediaLibrary is using a very similar step procedure to check and add single image items to the textarea. It mainly misses the second step (ping-pong) page call to the redirector script, ending and closing directly on submit.

**Comment by f1ames** [comment] 2017-08-18 08:29
@ophian Could you provide a step by step reproduction scenario (you can add some screenshots as you have some 3rd party libs there), without it, it is hard to say what is the exact cause of the issue?

**Comment by msamsel** [comment] 2017-09-07 08:32
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-09-07 08:32 UTC
Labels: status:pending
