### ISSUE TITLE
MathML formatting gone when using ACF

### ISSUE THREAD

**Issue by tutotours** [ckeditor/ckeditor-dev#901] opened 2017-09-13 07:20 UTC
Bug

## Provide detailed reproduction steps (if any)

1. Install CKEditor with WIRIS Math & Science Editor (math equations WYSIWYG which inserts math equations as MathML).
2. Add this to config.js to enable ACF with some custom rules : 
     ```javascript CKEDITOR.editorConfig = function( config ) {
        // Add WIRIS to the plugin list
        config.extraPlugins += (config.extraPlugins.length == 0 ? '' : ',') + 'ckeditor_wiris';
        config.allowedContent = {
            $1: {
                // Use the ability to specify elements as an object.
                elements: CKEDITOR.dtd,
                attributes: true,
                styles: true,
               classes: true
            }
        };
        config.disallowedContent = '*{font*}; *{margin*}; *{color*}; span;';
3. Use WIRIS plugin to insert equations into CKEditor. You can see that it works and equations are displayed correctly.
4. Save and refresh.
5. You can see that all MathML formatting is gone.

### Expected result

MathML formatting should remain intact since I followed documentation to allow all elements except span and font, margin and color styles.

## Other details

* Browser: Chrome, Firefox, Edge
* CKEditor version: 4.7.1
* Installed CKEditor plugins: WIRIS Math & Science Editor

**Comment by msamsel** [comment] 2017-09-15 07:51
Hi @tutotours,

This is a third party plugin not maintained by CKEditor team. Please contact with the plugin author to report existing problem. Information about the author you can always find on our addon page: https://ckeditor.com/addon/ckeditorwiris.

You can also try to use our plugin for inserting Math formulas. Example how it works you can find [here](https://sdk.ckeditor.com/samples/mathjax.html).

**Comment by tutotours** [comment] 2017-09-15 08:27
Hi @msamsel,

I don't think it's related to WIRIS but to ACF. That's why I put this issue here. 
When I allow everything except margin, font, color and span, MathML formatting shouldn't be erased by ACF. The problem is not only with this plugin but also with all MathML I give to the editor.

**Comment by msamsel** [comment] 2017-09-15 08:41
Then I need to have more details about this case.
> When I allow everything except margin, font, color and span, MathML formatting shouldn't be erased by ACF.
How do you know that? Can you explain a little bit wider?

In case that problem is really in ACF, you should be able to reproduce the issue without WIRIS or MathML. How it might be done. Make similar configuration and manually insert those problematic markups in editor source. If ACF works incorrectly, then such content should be filtered out also in inappropriate way. Would it be possible for you to prepare such test case? Where ACF have some configuration and incorrectly filter tags? I'll appreciate some example on codepen.io, jsfiddle.net, or similar page.

**Comment by tutotours** [comment] 2017-09-15 10:47
Actually, when I copy MathML in source or create Maths with WIRIS, ACF is not erasing anything. When I save the editor content, I can see all the MathML formatting. 
But when I reopen the editor to edit this content, all MathML formatting. It's disappearing only on reopening.

I can create a codepen but I don't know if you understand what I mean.

**Comment by msamsel** [comment] 2017-09-15 11:11
Let's try with some code where we could base on.:)
Just prepare some code and give me step by step guide (as detail as you can). And point out what is unwanted behaviour there.

**Comment by tutotours** [comment] 2017-09-16 10:08
I found a way to do what I want by adding this to config.js but it's a little hacky in my opinion : 

        config.extraAllowedContent = 'math[xmlns]; maction; maligngroup; malignmark; menclose; merror; mfenced; mfrac; mglyph; mi;' +
        'mlabeledtr; mlogdiv; mmultiscripts; mn; mo; mover; mpadded; mphantom; mroot; mrow; ms; mscarries; mscarry;' +
        'msgroup; mstack; msline; mspace; msqrt; msrow; mstack; mstyle; msub; msup; msubsup; mtable; mtd; mtext; mtr;' +
        'munder; munderover; semantics; annotation; annotation-xml;';

**Comment by msamsel** [comment] 2017-09-22 07:18
@tutotours your code require 3rd party plugins not supported by CKEditor team. I cannot help with them.
Please provide steps to reproduce problem without 3rd party plugins. If it's really ACF issue, then it should be possible to repeat problem without those plugins.

**Comment by msamsel** [comment] 2017-10-17 07:41
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-10-17 07:41 UTC
Labels: status:pending
