### ISSUE TITLE
Korean letters are not properly transformed inside tables

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1848] opened 2018-03-27 14:47 UTC
## Are you reporting a feature request or a bug?

BUG

## Provide detailed reproduction steps (if any)
You need to have Korean keyboard - I've used `2-set Korean` layout

1. Open editor: https://cdn.ckeditor.com/4.9.0/full-all/samples/
2. Insert table with at least 2 columns
3. Put cursor in 2nd column.
4. Start typing with Korean keyboard letters: `ㅎ` `ㅏ` `ㄴ` (g, k, s - on US layout) it should generate sign `한` 

![mar-27-2018 16-43-13](https://user-images.githubusercontent.com/9017322/37974910-5c8c1e72-31de-11e8-82bc-3c71e2d65ff8.gif)

### Expected result
`한` is always generated when `ㅎ` `ㅏ` `ㄴ`  are typed in editor

### Actual result
`ㅎ` `ㅏ` `ㄴ` remain not transformed

## Other details

* Browser: Chrome
* OS: MacOS
* CKEditor version: 4.9.0
* Installed CKEditor plugins: full-all

original issue: https://github.com/ckeditor/ckeditor-releases/issues/78

**Comment by engineering-this** [comment] 2018-03-28 12:17
Duplicate of #1799

**Closed by engineering-this** 2018-03-28 12:17 UTC
Labels: status:confirmed, target:minor, type:bug
