### ISSUE TITLE
Balloon Toolbar tests are failing in small browser window

### ISSUE THREAD

**Issue by wojtekw92** [ckeditor/ckeditor-dev#1076] opened 2017-10-23 14:40 UTC
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Open unit test http://tests.ckeditor.test:1030/tests/plugins/balloontoolbar/positioning.
2. Resize window to height ~300-400px.
3. Run tests.

### Expected result

All test should be passed.

### Actual result

Teat are failing on `top align`.

## Other details

* Browser: Windows, MacOS
* OS: all
* CKEditor version: 4.7.3
* Installed CKEditor plugins: inlinetoolbar

**Comment by mlewand** [comment] 2017-12-15 16:20
Corrected test URL. However I can't reproduce this issue on Win10 (Chrome, Firefox, IE11, Edge). @msamsel  @f1ames @Comandeer can any of you reproduce it?

**Comment by msamsel** [comment] 2017-12-18 07:08
@mlewand during 4.8.0 testing some positioning tests were ignored. It seems to be a reason why now tests are not failing. https://github.com/ckeditor/ckeditor-dev/pull/1307

**Comment by Comandeer** [comment] 2018-12-12 15:17
Merged into 4.11.2.

**Comment by mlewand** [comment] 2019-01-07 14:19
Looks like #2663 did not cut it. Scheduling for next minor release.

**Comment by engineering-this** [comment] 2019-02-18 16:11
Finally tracked source of iOS Safari issue. This isn't just failing test. Balloon toolbar might be wrongly positioned, that is because getting rect of an iframe returns rect of it's content doc instead of the actual rect on mobile Safari.

**Comment by f1ames** [comment] 2019-03-25 16:52
Closed with https://github.com/ckeditor/ckeditor-dev/commit/3c4e2a3eb7883fe053c99bd4214637cdecea4058.

**Closed by f1ames** 2019-03-25 16:52 UTC
Labels: plugin:balloontoolbar, status:confirmed, target:minor, type:failingtest
