### ISSUE TITLE
Register command should extend filter rules with allowedContent

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#1103] opened 2017-10-30 08:36 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open link: https://codepen.io/msamsel/pen/EbaZxK?editors=1010
2. Press <kbd>Ctrl</kbd> + <kbd>H</kbd>
3. Check source twice.

### Expected result
Register a command, should be sufficient for extending filtering rules.

### Actual result
Plugin is not working properly, `itemprop` attribute is removed from the editor.

## Other details

* Browser: all
* OS: all
* CKEditor version: 4.7.3
* Installed CKEditor plugins: full-all

**Comment by mlewand** [comment] 2019-01-11 10:14
Duplicate of #678.

**Closed by mlewand** 2019-01-11 10:14 UTC
Labels: status:confirmed, type:bug
