### ISSUE TITLE
Windows xp/windows 7 login with guest account can not paste content form word

### ISSUE THREAD

**Issue by liu2628829** [ckeditor/ckeditor-dev#3082] opened 2019-05-02 03:17 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1.Windows xp/windows 7 login with guest account
2.This machine uses the source code to start the  ckeditor 4  in the IE8/IE9 browser
3. Copy the contents of word2010
4. When pasting into ckeditor, there is no effect (the cursor will flash), ctrl + v shortcut, right-click menu "Paste", the tool "Paste content from MSword" button has no effect
5. But paste the contents of word2010 into Notepad, and paste the contents of Notepad to ckeditor.
6. The security settings of the IE browser have been set, enabling programmatic access to the clipboard, enabling dragging or copying and pasting files

### Expected result

Content from word can be pasted into CKEditor 

### Actual result

Paste has no effect

## Other details

Browser: IE8/IE9
OS:windows xp sp3/windows 7
CKEditor version: CKEditor 4.6
Installed CKEditor plugins: pastefromword

**Comment by jacekbogdanski** [comment] 2019-05-14 07:47
Hello,

I have no issue with pasting from MS Word using our latest CKEditor4. Could you verify if you are able to reproduce the issue with the latest (currently 4.11.4) version? If so, could you provide more details about the issue, so we can reproduce it?

>This machine uses the source code to start the ckeditor 4 in the IE8/IE9 browser

I'm not sure if I understand correctly, is it some kind of test automation?

**Comment by jacekbogdanski** [comment] 2019-06-05 09:22
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2019-06-05 09:22 UTC
Labels: status:pending, type:bug

**Comment by liu2628829** [comment] 2020-04-06 02:37
Thank you for your answer. The problem has been solved. The problem is that another program on this computer limits copy and paste functionality
