### ISSUE TITLE
All files have BOM in them

### ISSUE THREAD

**Issue by gemal** [ckeditor/ckeditor-dev#2010] opened 2018-05-25 18:05 UTC
https://en.wikipedia.org/wiki/Byte_order_mark

they should not have this to make them more OS independing

versoin 4.9.2

**Comment by msamsel** [comment] 2018-05-28 07:32
Hi @gemal,

From what I see not all files contains BOM. We're gradually removing BOM from files during bug fixing. I couldn't find any files with BOM during my quick search in repository. That's why please provide list of files which contains BOM it might be helpful in the future.

Please also remember that you can always propose Pull Request which fix all those files with BOM :)
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_contributing.html

**Comment by wwalc** [comment] 2018-06-07 10:52
There is a huge chance that Unicode BOM character is added during the release process. It is done by design since many years due to some issues with IIS in the past, where files without BOM were served with wrong encoding. Keep in mind that both `ckeditor.js` and language files contain translations.

I wouldn't risk removing BOM (unless there is a **very** good reason to do so) because with so many different environments where CKEditor is running there is a chance that it will become broken on some web servers if we remove BOM. 

@gemal are you having any particular issue with the BOM character? Are you reporting it due to  an issue with the source files or the release package? If with source files, did you report it because your editor displays BOM as a weird character or it simply does not match your predefined code style in your project, or was there a different reason?

**Comment by jacekbogdanski** [comment] 2018-06-21 12:40
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-06-21 12:40 UTC
Labels: status:pending
