### ISSUE TITLE
/tests/plugins/balloontoolbar/positioning fails on mobiles

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#2729] opened 2019-01-07 13:07 UTC
## Type of report

Failing tests.

## Provide detailed reproduction steps (if any)

1. Go to `tests/plugins/balloontoolbar/positioning`.

### Expected result

All tests pass.

### Actual result

Two tests fail:
```
/tests/plugins/balloontoolbar/positioning#tests/plugins/balloontoolbar/positioning test panel - out of view - bottom center (editor1)
```
```
http://localhost:1030/tests/plugins/balloontoolbar/positioning#tests/plugins/balloontoolbar/positioning test panel - out of view - hcenter top (editor1)
```

## Other details
Tests fail only if the device is in the vertical orientation. Works fine while in the horizontal orientation.

* Browser: Chrome, Safari
* OS: Android, iOS

**Comment by jacekbogdanski** [comment] 2019-01-07 13:19
I can confirm the issue on iOS 12.1.2.

**Comment by mlewand** [comment] 2019-01-07 14:21
This issue is a duplicate of #1076. Mentioned issue simply didn't fix every case. Lets track it there.

**Closed by mlewand** 2019-01-07 14:21 UTC
Labels: browser:android, browser:ios, status:confirmed, type:failingtest
