### ISSUE TITLE
On backspace hit wrong DOM node deleted 

### ISSUE THREAD

**Issue by IAfanasov** [ckeditor/ckeditor-dev#1643] opened 2018-02-12 03:46 UTC
## Are you reporting a feature request or a bug?

I'm not sure is it CKEditor's bug. Most likely not. I need help to debug it. 

## [Check if the issue is already reported]
Didn't find related

## Provide detailed reproduction steps (if any)

1. Open page with CKEditor
1. Enter some text
1. Select some text among selected
1. Go to other tab
1. Go back to tab from steps 1 and 2
1. Hit Backspace

![repro](https://github.com/IAfanasov/files/blob/master/deletion-demo.gif?raw=true)

### Expected result

in step 6 should be deleted selected in step 3 text

### Actual result

Parent td tag is deleted

## Other details

* Browser: Chrome
* OS: mac os and windows
* CKEditor version: 4.7.3
* Installed CKEditor plugins: lots

Method [getSelectedElement](https://github.com/ckeditor/ckeditor-dev/blob/ae70567ed5995aed43abc605fd5af9afcf1cfc76/core/selection.js) return parent 'td' instead of selected element node.
It's not reproduced in [demos](https://ckeditor.com/ckeditor-4/#document) and our system it reproduced only in all points of CKEditor usage. 
Any ideas why it could happen? Or how to debug it.

**Comment by IAfanasov** [comment] 2018-02-12 06:36
Found "workaround":
`window.addEventListener("focus", function () {
	setTimeout(function () {
		for (var instanceKey in CKEDITOR.instances) {
			CKEDITOR.instances[instanceKey].getSelection().reset()
		}
	}, 10);
});`

**Comment by jacekbogdanski** [comment] 2018-02-13 08:54
Hello,

I tried to reproduce your issue using https://cdn.ckeditor.com/4.7.3/full-all/samples/ but it works fine. Could you provide list of installed plugins? Your fix will probably create more bugs with selection in the future, so it's best to find a real issue.

**Comment by IAfanasov** [comment] 2018-02-13 09:01
Thanks for reply. Hope we will figure it out.
```
Object.keys(CKEDITOR.plugins).sort().join('\n')
```

> _
> basePath
> clipboard
> colordialog
> contextMenu
> copyformatting
> div
> enterkey
> externals
> fileName
> indent
> indentList
> lineutils
> link
> list
> liststyle
> load
> loaded
> notification
> pagebreakCmd
> print
> registered
> removeformat
> scayt
> setLang
> sourcearea
> tabletools
> undo
> widget
> widgetselection

**Comment by IAfanasov** [comment] 2018-02-13 09:44
looking for demo stand to check out widgetselection. sounds suspicious

**Comment by jacekbogdanski** [comment] 2018-03-20 13:29
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-03-20 13:29 UTC
Labels: status:pending
