### ISSUE TITLE
Text Formatting does not work in IE11

### ISSUE THREAD

**Issue by prashu-a** [ckeditor/ckeditor-dev#795] opened 2017-08-17 14:00 UTC
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Create new ASP.NET webform with CKEditor (ASP.net v3.6.6.2 and CKEditor 4.7.1)
2. Sample ASPX code,
<%@ Page Language="VB" AutoEventWireup="false" CodeFile="Default.aspx.vb" Inherits="_Default" %>

<%@ Register Assembly="CKEditor.NET" Namespace="CKEditor.NET" TagPrefix="CKEditor" %>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <CKEditor:CKEditorControl ID="teaEmailMessage" runat="server" Height="450px" Width="100%" BasePath="~/ckeditor">
		
		</CKEditor:CKEditorControl>
    </div>
    </form>
</body>
</html>

3. Build and run in IE 11.
4. Now try clicking on text formatting options. Like, Bold, Italics, create Table ... You will see nothing happens. Shortcut keys work though (ctrl + B for Bold).

### Expected result

I should be able to format text within CKEditor on IE 11.

### Actual result

When you click on format options, nothing happens. No error in IE11 Developer Tools.

## Other details

* Browser: IE11
* OS: Windows 10 / Windows 2008 R2
* CKEditor version: Version 4.7.1 & CKEditor for ASP.NET 3.6.6.2 (15 Jul 2014)

**Comment by mlewand** [comment] 2017-08-17 14:03
Duplicate of #794. Please check mentioned ticket, we actually have problem reproducing this issue. See if on your setup the same problem occurs on our demo page, as reported in #794.

If you have a possibility to compare it with IE11s on non-server Windows, that would be a good check too.

**Closed by mlewand** 2017-08-17 14:03 UTC
