### ISSUE TITLE
ckeditor not rendering image with latest chrome version Version 75.0.3770.90 , but working fine with previous versions of chrome and firefox.

### ISSUE THREAD

**Issue by yravinderkumar33** [ckeditor/ckeditor-dev#3174] opened 2019-06-18 05:59 UTC
## Type of report

Bug
1. Image rendering is not working properly with latest version of chrome (Version 75.0.3770.90).
* Browser: Chrome Version 75.0.3770.90
* OS: Mac
* CKEditor version:5
<img width="1183" alt="Screenshot 2019-06-18 at 11 26 45 AM" src="https://user-images.githubusercontent.com/12777499/59656783-4a6c4700-91bc-11e9-83bf-9de303259c56.png">

**Comment by f1ames** [comment] 2019-06-18 06:04
Hello @yravinderkumar33,

> CKEditor version:5

Does your issue report concerns CKEditor 4 or CKEditor 5 (looking at the stack trace looks like CKE5)? If it's CKEditor 5, please report to https://github.com/ckeditor/ckeditor5. If CKEditor 4, please provide a reproduction steps here.

**Comment by jacekbogdanski** [comment] 2019-07-08 09:05
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2019-07-08 09:05 UTC
Labels: resolution:expired, type:bug
