### ISSUE TITLE
ckeditor walker function selects all traverse element in explorer browser version 11 & traverse elements are highlighted.

### ISSUE THREAD

**Issue by dilipshelake03** [ckeditor/ckeditor-dev#1432] opened 2018-01-10 13:29 UTC
## it's a bug?

I am trying to get the previous element/ node for from current cursor position in ckeditor.

for this i'm using following code.

               var range = editor.getSelection().getRanges()[ 0 ];
                range.collapse( true );
                range.setStartAt( editor.editable(), CKEDITOR.POSITION_AFTER_START );
                // Let's use the walker to find the closes (previous) text node.
                var walker = new CKEDITOR.dom.walker( range ),
                    node;
                var i = 0;
                while ( ( node = walker.previous() ) ) {
                    if (node.type == CKEDITOR.NODE_TEXT ) {
                        if(node.getText().indexOf('/list') !== -1) 
                            vm.closedList.push(i);
                        
                        else if ((node.getText().indexOf(params[0])!=-1 || 
                                node.getText().indexOf(params[1])!=-1) 
                                && (vm.closedList.length > 0)) 
                            vm.closedList.pop();
                        
                         else if (node.getText().indexOf(params[0])!=-1 || 
                            node.getText().indexOf(params[1])!=-1) 
                            return node.getText();
                        
                         else if(node.getText().indexOf(params[2]) !=-1) {
                              vm.foundMetaModel = node.getText();
                              return null;
                         }
                    }
                    i++;
                }

This code works fine on other browsers, but for IE its selects all the traverse elements and show highlighted. and if i try to insert any new element then these highlighted elements/text are replaced by new element.

Please let me know, how can i resolve this issue of Internet explorer browser version 11. 

### Expected result

traverse elements not get selected & not get highlighted

## Other details

* Browser: Internet explorer 11
* OS: window 7
* CKEditor version: 4.7
* Installed CKEditor plugins: …

**Comment by f1ames** [comment] 2018-01-10 14:01
Could you provide full code, so javascript code (e.g. in above sample there are some variables like `vm` not defined in the sample) and the contents of the editor with which the issue could be reproduced? It could be a [codepen](https://codepen.io/) sample.

**Comment by dilipshelake03** [comment] 2018-01-10 15:20
Hi **f1ames**

I have created a codepen for your reference. you can review the sample code from below link.

https://codepen.io/dilipshelake/pen/NXypYV

Steps to reproduce issue
1) click inside then ckeditor on new line. 
2) click on "Get Previous Node" button.
3) select any item from select box.
4) this will remove all the existing ckeditor contents.

I am facing this issue on internet explorer 11.

Please suggest solution for this.

**Comment by dilipshelake03** [comment] 2018-01-11 06:58
Hi **f1ames**

I have tested above sample code (https://codepen.io/dilipshelake/pen/NXypYV )on chrome & firefox. it working well on these browsers.

while testing on IE11 I'm getting following error as, 

SCRIPT5007: Unable to get property 'insertBefore' of undefined or null reference.

Please suggest here.


ckeditor

**Comment by engineering-this** [comment] 2018-07-27 12:09
Hi,

Codepen sample doesn't load for me in IE, so I created local html file.

```
range.setStartAt( editor.editable(), CKEDITOR.POSITION_AFTER_START );
```
At above line you are modifying an existing range. It looks like in IE changes also selection. You should create new range instead.
Calling [`CKEDITOR.editor.insertElement`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#method-insertElement) inserts into current selection, so if you select whole editor content, than it will overwrite it all.


Also there are mistakes in your codes, that might break IE:

```
<div id="editor1" contenteditable="true">
	<p>This is an example CKEditor instance.</p>
</textarea>
```
Wrong tag closed.

And about:
>SCRIPT5007: Unable to get property 'insertBefore' of undefined or null reference.

I don't see this issue. If its still the case could you provide some more informations when it occurs?

**Comment by mlewand** [comment] 2018-08-13 06:54
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-08-13 06:54 UTC
Labels: status:pending
