### ISSUE TITLE
CK Editor - Copy/Paste duplicate text, text repetition after pasting of copied content.

### ISSUE THREAD

**Issue by nikhil-framsikt** [ckeditor/ckeditor-dev#480] opened 2017-06-07 10:04 UTC
When we perform a Copy/Paste from text into the CKEDITOR (4.4.3 version), the text gets copied multiple times.(2-6-8-10 times) and the browser also freezes when this happens. 

But this only happens after long periods of use/ intensive use of ck editor, with a considerable amount of text and it's hard to reproduce.

The text can duplicate to 15 times the text which is pasted. 

So far reported both in Chrome and Firefox

Texts are copied from various sources/apps: word, e-mail, webpages etc.

CK editor version :"4.4.3"

Can you please provide resolution to the same problem  ASAP.

**Comment by mlewand** [comment] 2017-06-08 14:09
Thanks for the report, first of all, can you reproduce this issue on [the latest CKEditor release](http://cdn.ckeditor.com/4.7.0/standard-all/samples/)?

**Comment by nikhil-framsikt** [comment] 2017-06-08 15:13
Thanks a lot for your reply, we would try to implement same and keep you posted on same.

Regards,
Nikhil

**Comment by jswiderski** [comment] 2017-06-13 11:25
Hi Nikhil,

Were you able to reproduce this issue in latest CKEditor version?

**Comment by nikhil-framsikt** [comment] 2017-06-13 11:35
Hi,

Thanks for the query, we have yet to implement the new version of CK Editor in our project. Since its going to impact the whole project, the priority for implementing the same is down the line.

As soon as we implement the same I would post back on the behaviour of the CK-Editor.

Best Regards,
Nikhil Thakur

**Comment by mlewand** [comment] 2017-07-05 11:16
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2017-07-05 11:16 UTC
Labels: status:pending

**Comment by loop-partha** [comment] 2020-01-09 12:47
This issue still exists with ver 4.13.1. Please assist us to fix this. But it is not reproducible but happens. We are using the CKEditor to react.
