### ISSUE TITLE
Table td input error on Korean

### ISSUE THREAD

**Issue by siseon-kim** [ckeditor/ckeditor-dev#1799] opened 2018-03-15 06:08 UTC
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. insert some *korean* text in first table cell
2. insert some *korean* text in second table cell

### Expected result

normal korean text

### Actual result

korean text broken in second table cell

## Other details

I found a problem with Google Chrome web browser when I typed Korean in the table of CKEditor 4.
That is, a bug occurs when CKEditor creates a table and enters Korean in td.

Please refer to the image I uploaded.

한글 is entered in the column, but ㅎㅏㄴ is entered.
Korean characters consist of 2byte, causing problems in input process.

I used CKEditor 4 on Google Chrome Version 65.0.3325.162 (Official Build) (64-bit)
This happened after Google Chrome was updated today.

So, Please check this rapidly.
Because, I think, this issue is happening to all Asian users.

### Screenshot

![screenshot](https://user-images.githubusercontent.com/1546045/37446026-5a726710-285e-11e8-9e3e-28c427cd1dae.png)

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.8.0
* Installed CKEditor plugins:

**Comment by engineering-this** [comment] 2018-03-19 09:57
Hi,

After few tries I can't reproduce your issue. I copied your text `한글` and pasted it into editor table. Also I've tried to change editor language to `kor`. Everything looks ok. Can you confirm if this problem occurs only when typing or when pasting too?

Please try to provide us editor example in which this problem happens. To do so please insert our editor into site like codepen.io or jsfiddle.net.

Here you have minimal setup example that You can fork and change config so it matches yours:
https://codepen.io/engineering-this/pen/NYbLjX

**Comment by sharp7C0000** [comment] 2018-03-20 00:40
@engineering-this 

This problem occurs when typing korean character. Paste is ok.
You can reproduce this bug to change your keyboard language at korean.

Also, I found this bug is not CKEditor's problem. It's chrome's bug.
Latest chrome's contenteditable makes ridiculous bug in td.

For example

```
<div contenteditable="true">
 <table>
  <tr>
     <td>English ok!!</td>
     <td>ㄱ ㅏ나다</td>
  </tr>
</table>
</div>
```

Same problem.. :'(

So, I report this bug at chrome but don't receive proper solution yet.

However.. this code works.
```
<div contenteditable="true">
 <table>
  <tr>
     <td><p>English ok!!</p></td>
     <td><p>가나다</p></td>
  </tr>
</table>
</div>
```

Thank you. Have a nice day.

**Comment by siseon-kim** [comment] 2018-03-20 00:46
@engineering-this 

This problem occurs when typing korean character. Paste is ok.
You can reproduce this bug to change your keyboard language at korean.

Also, I found this bug is not CKEditor's problem. It's chrome's bug.
Latest chrome's contenteditable makes ridiculous bug in td.

For example

```
<div contenteditable="true">
 <table>
  <tr>
     <td>English ok!!</td>
     <td>ㄱ ㅏ나다</td>
  </tr>
</table>
</div>
```

Same problem.. :'(

So, I report this bug at chrome but don't receive proper solution yet.

However.. this code works.
```
<div contenteditable="true">
 <table>
  <tr>
     <td><p>English ok!!</p></td>
     <td><p>가나다</p></td>
  </tr>
</table>
</div>
```

Thank you. Have a nice day.

**Comment by engineering-this** [comment] 2018-03-20 09:59
Thanks for your response. Im closing this issue now as its browser problem not our editor.
Have a nice day too.

**Closed by engineering-this** 2018-03-20 09:59 UTC
Labels: resolution:upstream

**Comment by engineering-this** [comment] 2018-03-28 12:18
I couldn't find anything related to this issue on chromium issue tracker so I've reported it:
https://bugs.chromium.org/p/chromium/issues/detail?id=826686

**Comment by siseon-kim** [comment] 2018-03-29 00:13
Oh thanks. really appreciate 😃
