### ISSUE TITLE
Cannot resize table while in Maximize mode (using TableResize plugin with inline editor)

### ISSUE THREAD

**Issue by soethan** [ckeditor/ckeditor-dev#2309] opened 2018-08-13 04:19 UTC
## Table column resize does not work while the editor is in Maximize mode.

Bug

## Detailed reproduction steps

1. Copy table from Excel
2. Resize columns in normal mode (can resize)
3. Click maximize button on CKEditor toolbar
4. Try to resize table columns (Even though resize cursor is display, it is not able to resize).

### Expected result

*Table columns should be able to resize in maximize mode*

### Actual result

*Table columns are not able to resize in maximize mode*

## Other details

* Browser: all browsers
* OS: all
* CKEditor version: 4+ (4.9.2)
* Installed CKEditor plugins: tableresize, copyfromexcel, etc

**Comment by msamsel** [comment] 2018-08-16 07:56
Hi @soethan,
I'm not able to reproduce the issue. I test it in maximized editor and I was able to resize the table.
You can check it here: http://cdn.ckeditor.com/4.10.0/full-all/samples/old/tableresize/tableresize.html
Excel remain some additional styles which make table's border very narrow, but still it was possible for me to resize it.

**Comment by mlewand** [comment] 2018-08-31 09:52
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-08-31 09:52 UTC
Labels: status:pending
