### ISSUE TITLE
Indent does not get pasted from Word

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#1126] opened 2017-11-06 22:27 UTC
## Are you reporting a feature request or a bug?
Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Copy paste an indented block from word.

### Expected result
Indent does not get pasted

### Actual result
The block should be indented.

## Other details

* Browser: All
* OS: All
* Version: CKEditor 4.7.0
Installed Plugins: Indent block

**Comment by mlewand** [comment] 2017-11-06 22:30
Hi, that's a duplicate of #651. Please subscribe mentioned issue to keep track of any progress.

**Closed by mlewand** 2017-11-06 22:30 UTC
