### ISSUE TITLE
Style combo box scroll not showing when it clicked on second time

### ISSUE THREAD

**Issue by cvak48** [ckeditor/ckeditor-dev#1465] opened 2018-01-17 09:44 UTC
## 📋 Steps to reproduce

1. Click on Style combo drop down menu and look for scroll bars
2. Select any item and repeat Step:1 and look for scroll bars

## ✅ Expected result
Should be same as Step:1
## ❎ Actual result
Scroll disappearing when second time clicks
## 📃 Other details that might be useful
following images may useful
https://drive.google.com/drive/folders/10whbOh4YJQBk2WXKJSXs1s04SAmwALr5?usp=sharing

Edit:
1. Not necessary to select any item. Just open combo twice and scrollbars are gone.
2. It looks fine in Safari and Firefox.

**Comment by engineering-this** [comment] 2018-01-17 10:49
Hello,

I confirmed this problem for Chrome only. Please don't skip information about your OS and Browser when submitting next issues.

**Comment by cvak48** [comment] 2018-01-17 12:16
Sure, but how to override this problem in Chrome Browser, Windows

**Comment by f1ames** [comment] 2018-01-17 12:50
Looks very similar to #774.

**Comment by mlewand** [comment] 2018-01-17 12:55
Duplicate of #774.

**Comment by mlewand** [comment] 2018-01-17 12:55
Please keep track of an upstream issue to get updates. Remember that by staring the upstream issue you increase chances that Chrome team is likely to resolve this issue.

**Closed by mlewand** 2018-01-17 12:55 UTC
Labels: browser:chrome, status:confirmed
