### ISSUE TITLE
SCRIPT5007: Unable to get property 'checkReadOnly' of undefined or null reference

### ISSUE THREAD

**Issue by wizeman1986** [ckeditor/ckeditor-dev#1063] opened 2017-10-17 15:41 UTC
Hi,

I have a page with 3 CK Editors.

The main one, which is the one the user sees when he visits the page when he chooses a document version,  the one in a modal, which shows text differences using another script and an always hidden one which is always the latest version of the document.

This solution works fine in Chrome but in IE i am getting the following bug when I am clicking to open the popup.

"SCRIPT5007: Unable to get property 'checkReadOnly' of undefined or null reference"

So imagine, three instances of CKEDITOR, plus this :

`<script type="text/javascript">
    
    $(function () {
        var dmp = new diff_match_patch();
        $('#trigger').click(function () {
            if (oldHTML == null) {
                var oldHTML = document.getElementById("MainContent").innerHTML;

                var LatestHTML = CKEDITOR.instances['LatestMainContent'].getData();

                var CurrentHTML = CKEDITOR.instances['MainContent'].getData();

                var compareStrings = dmp.diff_main(CurrentHTML, LatestHTML);
                dmp.diff_cleanupSemantic(compareStrings);
                var optimizedResult = dmp.diff_prettyHtml(compareStrings);

                CKEDITOR.instances['ModalContent'].insertHtml(optimizedResult, 'unfiltered_html')

                $('#myModal').modal('show');
            }else
            $('#myModal').modal('show');
         //      return false;
        })

    });

</script>`

My version is 4.7.2

**Comment by msamsel** [comment] 2017-10-18 07:40
Hi @wizeman1986,
your example doesn't show entire situation. I don't know how you implement CKEditor, what configuration do you use, etc. That's why it's hard to analyse this case.
Could you provide some better example on page such as codepen.io, jsfiddle.net, jsbin.com, etc.?

**Comment by wizeman1986** [comment] 2017-10-18 07:53
Hi, 

I don't know if it help as its an asp.net mvc application, but here is a jsfiddle .

https://jsfiddle.net/wizeman1986/36btk8zL/ 

Thanks

**Comment by msamsel** [comment] 2017-10-18 08:15
You have right, it's confusing. :(

What I need is **possibility to reproduce this error**. Without it we don't know what to fix.

That's way I need better example which will provide such possibility.
Unfortunately neither of your codes allow on repeating an error on my side. I don't know how you embed the editors, how you are using them, what kind of configuration do you have, and all other stuff which might be helpful with this situation.

That's why I ask for code where problem will be visible with clear HTML + JS (optionally CSS).

**Comment by msamsel** [comment] 2017-10-26 07:33
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-10-26 07:33 UTC
Labels: status:pending
