### ISSUE TITLE
CKEDITOR.instances.editor.setData doesn't render content when the browser's console opening.

### ISSUE THREAD

**Issue by ke1vin666** [ckeditor/ckeditor-dev#1336] opened 2017-12-11 03:57 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. I open browser's console to debug in dev mode.
2. Set data of editor via ```setData(content)``` 

### Expected result

CKEditor render content normally

### Actual result

CkEditor didn't render content in editor, it is a high probability event.
I tested the demo of CKEditor, it set data normally.
So I think the reason might be the plugins I installed.

## Other details

* Browser: chrome 62.0
* OS: windows10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: 
a11yhelp
basicstyles
bidi
blockquote
button
clipboard
contextmenu
copyformatting
deselect
dialog
dialogui
elementspath
enterkey
entities
fakeobjects
filebrowser
find
floatingspace
floatpanel
font
format
horizontalrule
htmlwriter
image
image2
indent
indentlist
justify
lineutils
link
list
listblock
magicline
maximize
menu
newpage
notification
panel
pastefromword
pastetext
popup
preview
removeformat
resize
richcombo
selectall
selectallcontextmenu
showborders
sourcearea
specialchar
stylescombo
tab
toolbar
undo
widget
widgetselection
wysiwygarea

**Comment by Comandeer** [comment] 2017-12-11 09:40
I can't reproduce this issue on Chrome 63 on Windows 10. Could you provide some demo for it?

**Comment by mlewand** [comment] 2018-01-05 09:04
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-01-05 09:04 UTC
Labels: browser:chrome, status:pending, type:bug
