### ISSUE TITLE
SCRIPT5007: Unable to get property 'collapsed' of undefined or null reference ( link.js (24,160))

### ISSUE THREAD

**Issue by Satishhirpara09** [ckeditor/ckeditor-dev#2436] opened 2018-09-25 11:38 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CK Editor in Microsoft Edge (Version : 42.17134.1.0).
2. Open link popup to add hyper link
3. Now when we add a link and clicks Ok button then it throws above exception.
4. Above mentioned functionality is working fine for chrome and firefox.

* Browser: Microsoft Edge (Version : 42.17134.1.0)
* OS: Windows 10
* CKEditor version: version: "4.4.6",  revision: "08188c4"

**Comment by msamsel** [comment] 2018-09-25 12:02
Hi,

please always check latest version of CKEditor, because we always introduce bug fixes in newer versions. And that's why there always exist a chance that bug is fixed already.

I've checked your bug report on "Microsoft Edge 42.17134.1.0" on those pages:
- http://cdn.ckeditor.com/4.4.6/full-all/samples/replacebycode.html
- cdn.ckeditor.com/4.10.1/full-all/samples/

and I wasn't able to reproduce the bug.
I close the issue for now, if you provide more details how to reproduce the bug case, the I can reopen the issue.

**Closed** 2018-09-25 12:03 UTC
Labels: resolution:cantreproduce
