### ISSUE TITLE
Manually adding hex color in color picker dialog doesn't pre-fill with hashtag

### ISSUE THREAD

**Issue by kd8ssq** [ckeditor/ckeditor-dev#565] opened 2017-06-26 15:04 UTC
## Are you reporting a feature or a bug?

Task

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

None Found

## Provide detailed reproduction steps (if any)

1. In CKeditor, highlight some text
2. In the toolbar, click "Text Color" and then "More Colors..."
3. In the text field above the "Clear" button, enter in any hex color without the preceding hashtag (ex. 333333)
4. Click Ok

### Expected result

Since hex colors need to have the preceding hashtag to render properly, if a hashtag isn't entered, I would assume it would automatically be added.  The editor seems to display the color without the hashtag (sometimes you have to switch in and out of Source mode to get it to show up, but it does), but as soon as you go to view the text on a web page, the color doesn't display properly because the browser cannot render without the hashtag.

### Actual result

No hashtag is added and the browser cannot render the style

## Other details

Tested in Ckeditor Demo with same results

* Browser: Chrome 58.0.3029.110
* OS: Windows 10
* CKEditor version: 4.5.7
* Installed CKEditor plugins: Full package w/ codemirror,codeembed,iframe,saveeditor,canceleditor,sourcedialog,uploadimage

![color picker dialog](https://user-images.githubusercontent.com/6402523/27544863-6606251a-5a5c-11e7-89ff-515b6fb43d6b.PNG)

**Comment by mlewand** [comment] 2017-06-27 14:43
It's not a bug, but sounds like a nice and simple feature request.

The reason why it does not add hash aggresively is that this field accepts any valid CSS value, so you could type `red`, `#f00`, `#ff0000`, `rgb(255,0,0)` etc.

I'd say that it could adding a missing hash **only if** the value matches a regexp allowing only chars `0-9a-f` and with exactly 3 **or** 6 chars. In this case after change it could automatically add a missing `#` char.

**Comment by f1ames** [comment] 2017-07-05 11:57
The fix for `colordialog` landed on `major` (#580). However, due to the fact that `colorbutton` does not utilize `colordialog` API for getting selected color this issue is still not fixed. It will be fixed by #590 (which is about switching to `colordialog` API in `colorbutton`).

**Comment by msamsel** [comment] 2017-07-24 10:44
#590 is marged, so we can close this issue as a done.

**Closed by msamsel** 2017-07-24 10:44 UTC
Labels: easy, status:confirmed, type:feature

**Comment by mlewand** [comment] 2017-08-16 09:33
@f1ames @msamsel I'm a bit lost here, it's my understanding that this issue is a duplicate of #607 - right? If so please, update it with a proper labels and remove from backlog.

**Comment by f1ames** [comment] 2017-08-17 08:02
@mlewand :
#580 was about adding `#` to hex color representation when `colordialog` is closed so every plugin utilising its API will benefit from it.
#590 was about utilizing this `colordialog` API in `colorbutton` as it was not used there.

This two fixes were needed to resolve this issue.

#607 was about changing color/background-color of table cells using color hex representaion without `#`. As it already utilizes `colordialog` API, it benefited from #580. However, this (#565) and #607 are two different issues as one concerns `colorbutton` and the other one `table cell properties` dialog.

I think it should be added to 4.7.2 milestone?

**Comment by brandonfarber** [comment] 2019-04-12 15:44
This issue seems to be present in 4.11.4. I can't find an online build of CKEditor 5 that allows you to choose the font color (i.e. using the color picker) to verify if the issue exists in CKEditor 5 or not.

**Comment by f1ames** [comment] 2019-04-12 16:31
@brandonfarber Can you post reproduction steps? It looks for me that it works fine with `4.11.4`. 

CKEditor 5 doesn't have online builder at the moment. It also doesn't provide color dialog as in CKEditor 4 so this issue will not be present there.

**Comment by brandonfarber** [comment] 2019-04-12 18:31
1. Go here: https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html
2. Select "Apollo 11" in the editor
3. Click the color button
4. Click the "More Colors" link at the bottom
5. In the color field type `FF0000` (no hash tag) and click out of the field. You get this:
![image](https://user-images.githubusercontent.com/10439617/56058402-53114e80-5d2f-11e9-9beb-ec4fb8adef67.png)
6. If you type `#FF0000` instead you get this (note the "Selected Color" field):
![image](https://user-images.githubusercontent.com/10439617/56058470-789e5800-5d2f-11e9-9729-959514cae53c.png)

Upon further testing I do see if you click the "Ok" button the manually typed color code does work and colorizes the selected text, so I guess it's only the "Selected color" field that does not update when the manually supplied color field is blurred when you don't supply a hash tag. Using latest stable Chrome on Windows 10.

**Comment by f1ames** [comment] 2019-04-15 08:17
> Upon further testing I do see if you click the "Ok" button the manually typed color code does work and colorizes the selected text, so I guess it's only the "Selected color" field that does not update when the manually supplied color field is blurred when you don't supply a hash tag.

Yes, that's exactly what happens and this issue was to fix the behavior after pressing `OK`. If you find the behavior with adding hash to manually inserted color on blur, feel free to open a new feature request.
