### ISSUE TITLE
ckeditor 4.7.X is not loading for the first time, Loads fine on Cltr+F5

### ISSUE THREAD

**Issue by cal0064** [ckeditor/ckeditor-dev#1325] opened 2017-12-05 04:55 UTC
We are using CKEditor in a HTML form that call that populates data from SharePoint List. We are using almost 6 CKEditor editors that are populated using Jquery 
We are seeing issues where the content of the CKEditor does not load abruptly.  But once you do Cltr+F5 the form loads ALL the time without fail.  The issue happens in Edge , IE11 and Chrome as well.

We are including the JS as 
<script src="//cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>
<td><textarea id="txtReqDescrip" name="txtReqDescrip" rows="4" cols="110" style="margin-top:0.25%;margin-bottom:0.25%"></textarea></td>
                                 
Additionally we have put cache clear tags in the HTML body , but that also does not work 
<meta http-equiv="pragma" content="no-cache" />

Request any suggestion to enable this .

**Comment by cal0064** [comment] 2017-12-07 09:43
Please can the community help on this.

**Comment by mlewand** [comment] 2017-12-11 12:46
@cal0064 Are you able to reproduce this issue on any of our example demos? E.g. http://cdn.ckeditor.com/4.7.3/full/samples

Otherwise it does sound more of a integration problem, something that is caused by other code than actually the CKE4 - as CKE4 comes with cache busting that prevents things like this from happening.

**Comment by mlewand** [comment] 2018-01-05 08:53
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-01-05 08:53 UTC
Labels: status:pending
