### ISSUE TITLE
Anchor in table throw an error when is edited

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-dev#496] opened 2017-06-09 14:48 UTC
## Are you reporting a feature or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Open website with CKEditor. It might be sample page.
1. Open browser console.
1. Insert table. It can be default.
1. Insert anchor in table. It's better to put it inside first cell.
1. Select few cells, in a way that anchor will be in the first one. (Example below)
![screenshot-localhost-8080-2017-06-09-16-42-05](https://user-images.githubusercontent.com/9017322/26980508-b398dc0a-4d32-11e7-8cba-687708044c92.png)
1. Press anchor button in toolbar, to edit it.
1. In console will be error: `Uncaught TypeError: Cannot read property 'type' of null` threw from [here](https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/link/dialogs/anchor.js#L38)

### Expected result
No error in console.

### Actual result
There is error.

## Other details
* Browser: Chrome v59
* OS: MacOS
* CKEditor version: full
* Installed CKEditor plugins: default

**Comment by Comandeer** [comment] 2017-06-12 11:37
This issue will be covered by #494.

**Comment by jswiderski** [comment] 2017-06-12 11:43
Problem can be reproduced in all browsers starting from version 4.7.0

Error thrown
File: anchor.js:
Line: 38 "at getSelectedAnchor (anchor.js:38)"
Message: Uncaught TypeError: Cannot read property 'type' of null

**Comment by mlewand** [comment] 2017-06-13 12:56
@Comandeer I see that #494 is resolved. Could you check if this issue got fixed?

**Comment by Comandeer** [comment] 2017-06-13 13:09
Yes, it seems to be fixed. Checked in Chrome, Firefox and Safari

**Closed by Comandeer** 2017-06-13 13:09 UTC
Labels: easy, status:confirmed, type:bug
