### ISSUE TITLE
Change event is not fired when resize the image by using the dragging resize option, drag it as much as possible or smaller than the max/min size allowed. 

### ISSUE THREAD

**Issue by enterentel** [ckeditor/ckeditor-dev#2615] opened 2018-11-21 20:42 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Select an image.
2. Resize the image by using the dragging resize option. 
3. Drag it as much as possible or smaller than the max/min size allowed.

### Expected result

 The change event should be called after resize the image at max/min size allowed.
 CKEDITOR.on('change', function (e) {
                    alter('tets');
    });
### Actual result

The event is fired  at intermediate size allowed, but for max/min size allowed is not fired.

## Other details

* Browser : IE , Edge , Chrome
* OS: Windows 10
* CKEditor version: 4.10
* Installed CKEditor plugins:

**Comment by engineering-this** [comment] 2018-11-23 10:13
Hi,

I can't reproduce your issue. Could you provide your CKEditor config, or even better if you could create sample on page like codepen.io or jsfiddle.net with minimum config that shows the bug? This would help us to inspect what is causing the problem.

**Comment by jacekbogdanski** [comment] 2018-12-12 07:55
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-12-12 07:55 UTC
Labels: resolution:expired
