### ISSUE TITLE
Copy/paste data in read-only mode in IE8-11 results in error

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1184] opened 2017-11-20 12:09 UTC
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

These are not duplicates but very similar issues:
* https://github.com/ckeditor/ckeditor-dev/issues/449
* https://dev.ckeditor.com/ticket/11825
* https://github.com/ckeditor/ckeditor-dev/issues/888

## Provide detailed reproduction steps (if any)

1. Open the read-only sample
2. Make editor read-only 
3. Select some text in editor (after making it read-only)
4. Press Ctrl+V

### Expected result

Nothing happens

### Actual result

After pressing `Ctrl` error is thrown:

**Error:**
Message: Unspecified error
Line: 2185
URI: ckeditor/code/selection.js
Code:
```
// Select the range.
sel.addRange( nativeRange );
```

## Other details

* Browser: IE8-11
* OS: Windows
* CKEditor version: IE11 - 4.7.1; IE8 - 4.7.0
* Installed CKEditor plugins: full preset was used

**Comment by mlewand** [comment] 2018-01-11 09:11
It might be related to #1181.

**Comment by jacekbogdanski** [comment] 2018-03-19 13:35
This bug has been already fixed with #1692. The issue is not related to #1181.

**Closed** 2018-08-10 10:55 UTC
Labels: browser:ie, status:confirmed, support, target:minor, type:bug

**Comment by mlewand** [comment] 2018-08-10 12:03
A fix for this issue is ready and has been merged to our upcoming release. It will be available in 4.10.1.

However you can already see it on [CKEditor preview builds](https://ckeditor4-preview.ckeditor.com/master/samples/).

I have forked the original codepen so that it uses preview CKE4 build here: https://codepen.io/mlewand/pen/rroRGQ
