### ISSUE TITLE
Formatting may be applied to the not selected paragraph

### ISSUE THREAD

**Issue by trypton** [ckeditor/ckeditor-dev#1726] opened 2018-03-01 09:48 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Create two paragraphs. Make sure the first one contains at least two words.
2. Select the whole content of the first paragraph with a triple mouse click.
3. Apply list, or alignment, or any block style.

### Expected result

Formatting is applied only to the first paragraph.

### Actual result

Formatting is applied to the second (not selected) paragraph as well.

## Other details

* Browser: Chrome
* OS: OSX
* CKEditor version: 4.8.0
* Installed CKEditor plugins: n/a

**Comment by jacekbogdanski** [comment] 2018-03-02 10:14
Duplicate of #484

**Closed by jacekbogdanski** 2018-03-02 10:14 UTC
Labels: resolution:duplicate
