### ISSUE TITLE
Cursor jumps to the beginning or end of a paragraph when hitting enter

### ISSUE THREAD

**Issue by wprogLK** [ckeditor/ckeditor-dev#2215] opened 2018-07-11 13:32 UTC
## Type of report

Bug

## Provide detailed reproduction steps 
Unfortunately, I cannot reproduce it. It happens from time to time with different texts.

### Expected result

A new line in the paragraph where I've place the cursor.

### Actual result

Cursor jumps to the top or bottom of the current paragraph and creates there a new line.

## Other details

* Browser: Firefox
* Browser plugin: none
* OS: Windows 10
* CKEditor version: 4.8
* Installed CKEditor plugins: pastefromword, contextmenu, divarea, htmlwriter

**Comment by jacekbogdanski** [comment] 2018-07-12 09:16
Hello,

I believe the issue is already reported #1878 and it's Firefox upstream. Could you check if the linked bug corresponds to your issue?

**Comment by mlewand** [comment] 2018-07-26 09:49
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2018-07-26 09:49 UTC
Labels: status:pending
