### ISSUE TITLE
Color button removes color when selection is collapsed

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#3199] opened 2019-06-19 14:46 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample.
2. Select all
3. Open color dialog and pick any color.
4. Place collapsed selection in the middle of text.
5. Repeat step 3. you can use the same color.

### Expected result

Color applied on step 3. is preserved.

### Actual result

Color applied on step 3. is removed.

## Other details

* Browser: any
* OS: any
* CKEditor version: Found in 4.12.0, reproduced in 4.8.0, didn't check older versions.
* Installed CKEditor plugins: colorbutton

**Comment by Dumluregn** [comment] 2019-06-19 16:39
Duplicate of #2932.

**Closed by Dumluregn** 2019-06-19 16:39 UTC
Labels: plugin:colorbutton, status:confirmed, type:bug
