### ISSUE TITLE
Can't scroll the editor after opening the autocomplete dropdown

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#2171] opened 2018-06-26 07:53 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open the `tests/plugins/autocomplete/manual/viewposition` test.
2. Follow the scenario.

### Expected result

It works as described in `expected` section.

### Actual result

The editor scrolls up after opening the autocomplete dropdown and can't be scrolled down.

## Other details

* Browser: Safari
* OS: iOS 11.4
* CKEditor version: 4.10.0

**Comment by jacekbogdanski** [comment] 2018-06-26 07:54
Duplicate of #1926

**Closed by jacekbogdanski** 2018-06-26 07:54 UTC
Labels: browser:ios, status:confirmed, type:bug
