### ISSUE TITLE
drag image make it disappear

### ISSUE THREAD

**Issue by SilentFlute** [ckeditor/ckeditor-dev#3215] opened 2019-06-26 06:11 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. customized a ckeditor with online builder based on full packages edition, add a html5video plugin in it, I edited `contents.css` as well, add some style rules actually, like `body` 
 tag backgroud color is `#f5f5f5`, and `box-sizing: border-box` in the `.cke_editable`
2. and then create a editor instance with the options below:
```
{
    width:style.width || "100%",
    height:style.height || "200px",
    resize_enabled:false,
    image_previewText:" ",
    filebrowserUploadUrl:"non-empty occupied string",//to make the Upload tab show up at the img/video dialog
    toolbarGroups:[
        //the toolbarGroup configurations
    ],
    removeButtons:"xxx,xxx",
    resize_enabled:false,
    removeDialogTabs:[
        "image:Link",
        "image:advanced",
        "html5video:advanced",
        "link:upload",
        "link:advanced",
        "iframe:advanced"
    ].join(";"),
    extraPlugins:'dropoff',//a custom plugin to prevent drag a img into the editable area make the img uploaded, cause we don't provide img upload function
    forcePasteAsPlainText:true,
    contentsCss:[ //some kind of css files, include the content.css of course ],
    dialog_noConfirmCancel:true
}
```
3. I press the img upload icon at the toolbar, then open the img dialog, at the info tab, I input a img link and press ok, the img insert into the editor, perfect. Then I copy many text contents from a web, only for sample u know, and drag the img between those texts

### Expected result
the img should moved correctly from a place from another place among those texts: I drag and drop, the img anchored where I am droped, and repeat

### Actual result
when I doing drag and drop thing times and times, maybe 10 or 20 times, the img disappeared

## Other details

* Browser: chrome 75.0.3770.100
* OS: macOS Mojave 10.14.4
* CKEditor version: 4.11.4_full packages
* Installed CKEditor plugins: html5video(added this plugin based on 4.11.4_full packages with online builder)

the toolbar looks like:
![image](https://user-images.githubusercontent.com/28900312/60154246-458d4000-9819-11e9-9443-822645b1588a.png)

About the `filebrowserUploadUrl` option, the reason why I use a non-empty occupied string is I only need the Upload tab and I customized a upload button in it to select img/video from our user's account, cause we are a demonstration platform for users where they can upload their productions(imgs/videos) to our platform. And in the rich text editor, they login in and select their productions and insert it into the editor, I hope I explained it clearly… All in all, there is no actually uploading operate, in img/video dialog, user click Upload Tab, and press the upload button that I write(I display: none; other dom eles and append a button into the container), will show a modal dialog, they select a production and press ok button in the modal dialog, at the mean time I use `selectPage`  api to switch the upload tab to info tab and input the link that user selected before into the `txtUrl` input tag, when user press ok button, the img/video will insert into the editor

**Comment by SilentFlute** [comment] 2019-07-02 06:21
is these things too many to read?
in short: i use ckeditor 4.11.4_full packages with html5video plugin, and i insert a img, then typing many texts, the img separate them to 2 parts, then i drag img between each line, drag img many times, 10 or 20 or more, the img will disappear

**Comment by SilentFlute** [comment] 2019-07-02 06:23
hope u guys can give some helps, thx🤣🤣

**Comment by jacekbogdanski** [comment] 2019-07-02 07:09
I'm not able to reproduce the issue using simple CKEditor4 instance with `image2` and `uploadimage` plugins enabled without 3rd party software. Do you use caption with your images? There is an issue which may be related to your bug: https://github.com/ckeditor/ckeditor-dev/issues/3026

Could you check if you are getting any console errors when images disappear?

I see that you are using some 3rd party plugins which may cause the issue. Could you check if the issue is reproducible without any 3rd party plugin? Please, provide in that case a list of used plugins, so we can imitate the same issue environment.

**Comment by SilentFlute** [comment] 2019-07-03 05:04
thx for ur replay, I don't use caption, and there is no error on console dialog when the img is disappear, I even listen the dragstart, dragend, drop event, and I print the event info, as I was seen, there is no different between the last one and the one before the last when this issue happened.
I use `http://cdn.ckeditor.com/4.12.1/full/ckeditor.js` only and without any 3rd plugins try it again, this issue still happened. It happened when the 1st drag…… If it doesn't happen, maybe try many times, but maybe it could not happen at all after many times, it happened casually I think
Speak of caption, when I upload a img, there is no `cke_widget_drag_handler` img tag on the right top corner of the img, like the demo:
![image](https://user-images.githubusercontent.com/28900312/60563943-5a755080-9d90-11e9-9fe1-6fb496ab782f.png)
I use the cdn address above, and open it in sources panel in chrome sources tab, and add a break point at the 1st line which contain `cke_widget_drag_handler`, when I open the img upload dialog, pasted a img address into the url input area, then press the ok button insert the img into the editor, there is no break point dialog show up at all, looks like js doesn't executed that line at all, maybe this is a way out of the img drag issue or some thing?

**Comment by SilentFlute** [comment] 2019-07-05 01:27
@jacekbogdanski 🤣🤣

**Comment by jacekbogdanski** [comment] 2019-07-09 08:29
I still have no luck using our samples e.g. using https://ckeditor.com/docs/ckeditor4/latest/examples/fileupload.html#uploading-dropped-and-pasted-images

@engineering-this could I ask you to check if you are able to reproduce the issue? Maybe you will have better luck with that.

**Comment by engineering-this** [comment] 2019-07-09 09:16
@jacekbogdanski I can't reproduce it, I think we are missing something here.

@SilentFlute can you provide sample on some JS sandbox site like codepen.io or jsfiddle.net, with editor configuration where you can reproduce the issue? In addition gif with screen cast showing actions which leads to the issue could be helpful.

**Comment by SilentFlute** [comment] 2019-07-12 12:56
@jacekbogdanski @engineering-this thank you for u guys reply, here is a codepen's address:
https://codepen.io/Silent_Flute/pen/xoeEML?editors=1000
I only used this: <script src="//cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>
and do some configurations in the page where u guys can see, and this issue reproduced every times……🤣🤣
1. open the codepen
2. copy the img link in the apge(http://pu0cgej6i.bkt.clouddn.com/dceu_cw.jpg, it's a cdn address from a cloud service provider)
3. insert it into editor from the 1st "info" tab of the img dialog  without uploading process
4. drag it
here is a mp4 about the issue:
http://pu0cgej6i.bkt.clouddn.com/drag_image_make_it_disappear.mp4
and the error is not from the ckeditor, warning is about a https site requested a http source
this issue can reproduce at the local development environment

**Comment by SilentFlute** [comment] 2019-07-12 13:05
And I troubleshooting the configuration one by one, I find it's this one's fault:
`forcePasteAsPlainText:true`
When I comment it, every thing goes fine, but I need this config to filter format when user pasted some contents from another web……

**Comment by jacekbogdanski** [comment] 2019-07-15 08:53
Thanks for more information. I was pretty sure you are using Enhanced Image which has its own drag&drop support by drag handler. 

You are right, `forcePasteAsPlainText` causes the issue. However, it's rather expected behavior than the bug. In most use cases you are using `forcePasteAsPlainText` option to invalidate any external formatting which also means that you shouldn't be able to preserve formatting when dropping content. I know that the configuration option name may be a bit misleading, although CKE4 paste mechanism is tightly coupled with drag&drop.

However, I see that there is a small gap in the conception. Some use cases may require only to filter format when paste goes from outside the editor. Internal pasting and d&d should keep its format in that case.

Fortunately, such a use case may be easily detected by using [`dataTransfer.getTransferType`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_clipboard_dataTransfer.html#method-getTransferType). I propose to extend our API with additional configuration option:

```javascript
config.forcePasteAsPlainText = CKEDITOR.DATA_TRANSFER_INTERNAL; // force plain text for internal pasting only
config.forcePasteAsPlainText = CKEDITOR.DATA_TRANSFER_INTERNAL; // force plain text for external pasting only
config.forcePasteAsPlainText = true; // force plain text for any paste
config.forcePasteAsPlainText = false; // disable

config.forcePasteAsPlainText = 'allow-word'; // any paste, keep formatting for Word

// And now goes a hard part with `allow-word` and custom source
config.forcePasteAsPlainText = {
  type: 'allow-word',
  source: CKEDITOR.DATA_TRANSFER_INTERNAL / CKEDITOR.DATA_TRANSFER_EXTERNAL
};
```

Last option seems a bit complicate so we may want to find out a better way for describing additional options, nevertheless I believe you get the point of the enhancement.

@SilentFlute will such feature solve your problem with the issue?

**Comment by SilentFlute** [comment] 2019-07-16 03:01
@jacekbogdanski wow, thx, that's definitely galvanized me when I saw ur replay, then I do these 2 things:
1. `forcePasteAsPlainText:CKEDITOR.DATA_TRANSFER_EXTERNAL`
2. add a listener below to listen the `paste` event, to prevent user pasted a img and it will invoke the `fileUploadRequest`, this process will throw some errors, cause in my project there is no img uploading processor as I mentioned before, they just chose a img from their account, and that img is already a cdn address, then I put it into the `info` tab of the img dialog
```
    editor.on('paste', function(e){
        if(!e.data.dataValue) {
            e.cancel()
        }
    })
```

And those things works very well, img dnd, img won't disappear any more, and when I try to paste a img into the editor, there is no `fileUploadRequest` and no errors, thx again.
One more question: what do u mean, the Enhanced Image, u mean when I insert a img into the editor and it's no `cke_widget_drag_handler` img tag on the left top corner of the img, like the demo:
![image](https://user-images.githubusercontent.com/28900312/61262244-374a9800-a7b7-11e9-93e1-f69d0911ef30.png)
is a Enhanced Image?
And why I insert a img into the editor like the screen record show, there is no widget like the picture show above, and when I `debugger` it in the corresponding code of the source code, looks like it doesn't execute there, but a 3rd plugin: `html5video` does, it does when the video dialog shows up, is this a bug or not, or I do some thing wrong, maybe the image should do a real uploading process through the server or some thing?That's can make the widget shows up

**Comment by SilentFlute** [comment] 2019-07-16 03:09
And speak of `forcePasteAsPlainText`, in the doc, it said:
```
This option accepts the following settings:

true – Pastes all content as plain text.
false – Preserves content formatting.
allow-word – Content pasted from Microsoft Word will keep its formatting while any other content will be pasted as plain text.
```
About the `CKEDITOR.DATA_TRANSFER_INTERNAL || CKEDITOR.DATA_TRANSFER_EXTERNAL` and another value that's shocked me 🤣🤣
I don't find these out before ur reply, thx again ❤️❤️

**Comment by jacekbogdanski** [comment] 2019-07-16 08:22
I'm sorry if I get you on the wrong path - these options for `forcePasteAsPlainText` are not available yet, I'm just proposing extending our API with that. Honestly not sure why it started working for you as `CKEDITOR.DATA_TRANSFER_EXTERNAL` results with `3` and the code responsible for your issue only checks for boolean value https://github.com/ckeditor/ckeditor-dev/blob/62dd45df1487f3cda537ea47ccb3253bc26e6028/plugins/pastetext/plugin.js#L71-L79

Nevertheless, it seems like this API change should fix your issue, so I extracted this feature into external ticket https://github.com/ckeditor/ckeditor-dev/issues/3269 - please subscribe it for updates.

> is a Enhanced Image?

Yes, in your sample you are using `image` plugin, the one on the picture is `image2`.

I'm closing this issue for now, as it should be fixed by https://github.com/ckeditor/ckeditor-dev/issues/3269 if we decide to introduce the feature.

**Closed by jacekbogdanski** 2019-07-16 08:22 UTC
Labels: plugin:image, plugin:uploadimage, status:pending, type:bug
