### ISSUE TITLE
'Permission Denied' error in Edge when using mentions plugin

### ISSUE THREAD

**Issue by belev** [ckeditor/ckeditor-dev#2755] opened 2019-01-16 09:41 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Using CKEditor with mentions plugin
2. Type @ to mention someone
3. Permission denied error occurs

### Expected result

To display autocomplete with the returned results of the mention.

### Actual result

Permission denied error occurs

## Other details

* Browser: Edge 44.17763.1.0
* OS: Windows 10
* CKEditor version: 4.11.1
* Installed CKEditor plugins: 'basicstyles', 'blockquote', 'clipboard', 'colorbutton', 'colordialog', 'confighelper', 'contextmenu', 'copyformatting', 'dialogadvtab', 'enterkey', 'entities', 'find', 'font', 'horizontalrule', 'image', 'indentblock', 'indentlist', 'justify', 'link', 'list', 'liststyle', 'magicline', 'maximize', 'mentions', 'menubutton', 'pastefromword', 'pastetext', 'popup', 'print', 'removeformat', 'selectall', 'sourcearea', 'tab', 'table', 'tableselection', 'tabletools', 'toolbar', 'undo', 'wordcount', 'wysiwygarea'

**Comment by jacekbogdanski** [comment] 2019-01-21 10:00
I can't reproduce the issue using our online sample: https://ckeditor.com/docs/ckeditor4/latest/examples/mentions.html
Could you provide more details about your configuration? Maybe some static files like custom profile images are placed on a different domain?

**Comment by belev** [comment] 2019-01-23 09:10
We haven't got any resources on different domain for this case.

This is our configuration for the mentions:
```js
{
            feed: feed, // request to our backend to load the needed data
            minChars: 0,
            throttle: 200,
            itemTemplate: '<li data-id="{id}" class="nowrap"><b>{fullName}</b>  <span class="color-gray-2">&lt;{email}&gt;</span></li>',
            outputTemplate: ' <a style="color: #ed6c45" href="mailto:{email}" title="{fullName} &lt;{email}&gt;">{fullName}</a> '
}
```

We have solved the problem by using the inline version, instead of this with the iframe.

**Comment by jacekbogdanski** [comment] 2019-01-24 10:15
Using inline editor may help, although it doesn't resolve the issue. Unfortunately, I'm not able to reproduce the issue using `fetch` with the data feed even if the data comes from a different domain.

Are you able to provide some more information about data feed which could help to recognize if the issue is caused by editor itself?

**Comment by belev** [comment] 2019-01-24 12:14
I can remember that when using the CKEditor inside iframe with the mentions plugin - it tries to open the autocomplete dropdown list outside of the iframe which was the problem for Edge/IE.

Unfortunately I can't provide more information because this was brought to us by a client which was experiencing the problem.

**Comment by jacekbogdanski** [comment] 2019-07-05 08:02
I still have no luck reproducing the issue. It would be great to get some additional confirmation as the issue seems to occur on some specific editor or browser configuration. @Dumluregn would you like to give a hand with the issue? I'm unable to reproduce the issue on:

```
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
```

**Comment by Dumluregn** [comment] 2019-07-05 08:37
Hi, I also tried to find your bug but unfortunately with no result. I tried to mimic your environment as precisely as I could basing on your description but (un)fortunately everything works just fine. If you still want to dig in this unexpected behavior, you could try to implement [Autocomplete plugin](https://ckeditor.com/cke4/addon/autocomplete), which is more generic than Mentions.

**Comment by jacekbogdanski** [comment] 2019-07-05 08:45
Thanks, @Dumluregn, I'm closing this issue as we are unable to reproduce it. 

However, @belev if you are able to provide more details about the issue and Edge browser version (we have some experience that different Edge browser versions produce unexpected behaviors), please let us know so we can reopen this issue.

**Closed by jacekbogdanski** 2019-07-05 08:45 UTC
Labels: status:pending
