### ISSUE TITLE
setStart TypeError:  Cannot read property 'type' of null

### ISSUE THREAD

**Issue by medinsky** [ckeditor/ckeditor-dev#2863] opened 2019-02-26 08:48 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Try to execute createBookmark method.

TypeError: Cannot read property 'type' of null
  at setStart(../node_modules/ckeditor/ckeditor.js:165:190)
  at trim(../node_modules/ckeditor/ckeditor.js:153:1)
  at insertNode(../node_modules/ckeditor/ckeditor.js:164:174)
  at createBookmark(../node_modules/ckeditor/ckeditor.js:145:197)

![Imgur](https://i.imgur.com/GZVttx7.png) 

### Actual result

Expected that there is no error, when object is null.

## Other details

* Browser: Chrome Version: 72.0.3626
* OS: Windows 10
* CKEditor version: 4.11.2
* Installed CKEditor plugins: Full Build default plugins + textmatch + textwatcher + autocomplete

**Comment by engineering-this** [comment] 2019-02-26 09:00
Hi.

Can you provide more detailed steps or a live demo showing the bug in some JS sandbox (e.g. codepen.io)? To fix an issue we need to reproduce it first, so we can investigate what's wrong.

**Comment by medinsky** [comment] 2019-02-26 09:38
@engineering-this , we cant reproduce this error, it is a strange error, that appears from time to time.
Last time we saw it was Jan 16. 
And then there was another steps that lead to this error

```
TypeError: Cannot read property 'type' of null
  at setStart(../node_modules/ckeditor/ckeditor.js:162:190)
  at setStartAfter(../node_modules/ckeditor/ckeditor.js:163:166)
  at optimize(../node_modules/ckeditor/ckeditor.js:148:124)
  at getEnclosedNode(../node_modules/ckeditor/ckeditor.js:176:221)
  at e(../node_modules/ckeditor/ckeditor.js:399:364)
  at isInTable(../node_modules/ckeditor/ckeditor.js:444:500)
  at d(../node_modules/ckeditor/ckeditor.js:1045:1)
  at call(../node_modules/ckeditor/ckeditor.js:1048:457)
  at call(../node_modules/ckeditor/ckeditor.js:10:57)
  at fire(../node_modules/ckeditor/ckeditor.js:11:421)
  at apply(../node_modules/ckeditor/ckeditor.js:60:399)
```

![Imgur](https://i.imgur.com/mVw9XQW.png)

We have only sentry breadcrumbs, but they are not informative and we cant reproduce this error following ui-steps provided by sentry.

**Comment by medinsky** [comment] 2019-03-06 06:28
any news about it?

**Comment by engineering-this** [comment] 2019-03-06 13:25
We can't fix an issue which we can't reproduce. Your proposed solution would only mask real problem instead of fixing it. Error is a good indication of an issue, silenting it might make harder in future to diagnose the problem once we find some other occurrence of the issue.

For now I'm closing this issue. Still, feel free provide us with reproduction steps, so that we can reopen this issue.

**Closed by engineering-this** 2019-03-06 13:25 UTC
Labels: status:pending

**Comment by IamNeo1** [comment] 2019-07-16 14:09
The problem seems to be the same as what is described here: https://dev.ckeditor.com/ticket/11270
I can reproduce it and it is a problem in FF, Chrome and IE11 in CKEditor Version 4.12.1
![Capture](https://user-images.githubusercontent.com/8747516/61301380-0fbdf480-a7e4-11e9-8ea1-35ec6a4fdd53.PNG)

It is a problem when editing HTML. More precisely, if you edit tables and want to correct text in the columns with backspace.

Please reopen the ticket. Otherwise I will open a new ticket.

**Comment by f1ames** [comment] 2019-07-16 14:24
@IamNeo1 thanks for update on this issue.

The stack trace caused by steps from https://dev.ckeditor.com/ticket/11270 is different than the one initially reported here in https://github.com/ckeditor/ckeditor-dev/issues/2863#issuecomment-46736769, also @uladzimir-miadzinski mentioned creating bookmarks so I assume this is a different issue. However, if you encountered https://dev.ckeditor.com/ticket/11270 feel free to open new issue here referring to the old bug report.

**Comment by IamNeo1** [comment] 2019-07-17 08:16
@f1ames 
Thanks for answering. I opend a new issue: [#3727](https://github.com/ckeditor/ckeditor-dev/issues/3272)
