### ISSUE TITLE
Image width and height missing after .replace()

### ISSUE THREAD

**Issue by EnrikVC** [ckeditor/ckeditor-dev#937] opened 2017-09-19 16:08 UTC
Bug

Hi, this is a bit confusing... I'm using ckeditor in a Zend Framework project. No ck plugins. Then, any image is rendered with the dimension assigned by style, but in edit mode, images are shown in original size.

## Reproduction steps

1. Image (1000x500) upload directly to server, the full url is returned via json
2. insertHtml is fired to create and view the image. Then resized to 400x200 (edit).
3. After saving changes, it renders ok 400x200 (display). The html code is also ok (db PostgreSQL)
4. Finally, I try to edit the content again (CKEDITOR.replace) and...

### Expected result

Edit mode, showing an image in 400x200

### Actual result

Edit mode, showing an image in original size 1000x500

## Other details
If I save again, no styles are applied. So I have to resize the image every time before saving any change.

* Browser: Chrome 60, Firefox 55
* OS: Windows 7 Pro x64
* CKEditor version: 4.7.2 Full
* Installed CKEditor plugins: None

**Comment by msamsel** [comment] 2018-01-05 08:24
Hi @EnrikVC,
I'm a little bit confused with your reproduction steps. It seems like your backend system should rescale the picture? If so then it's not an issue related to CKEditor.

Can you also check this page: https://ckeditor.com/ckeditor-4/ and give an info, if the issue is possibile to reproduce there?

**Comment by jacekbogdanski** [comment] 2018-01-22 08:25
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed** 2018-01-22 08:27 UTC
Labels: resolution:expired
