### ISSUE TITLE
URLs being altered

### ISSUE THREAD

**Issue by stephenl314** [ckeditor/ckeditor-dev#2747] opened 2019-01-11 21:55 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I reported this before but somehow my emails did not reach anyone and the issue was closed.

Go to http://basketbasics.com/gen/

You'll see a field with a ? button after it.

Enter CKEditor and click the button.

It will come back with just the Entry button showing. Click it.

This will take you the record of Test Case.

Click on General Notes. When you click the Done button on the notes it hides the div (closes the notes) and

    Calls  $('#GeneralNotes').val( CKEDITOR.instances.GeneralNotes.getData() )
    For you, it will then pop up an alert so you can see the value

So, you're in General Notes and it's empty. Add a URL (copy and paste the address of the page). Look at the source code to verify it's properly formatted. You'll see the popup that shows it's properly formatted.

Click on Parrish, Denver Forrest. This forces a save to the table and, since it's you, brings you right back to Test Case. (If you get a data error, try again. For some reason I'm having issues connecting to the server. If it connects you'll detect the screen clearing and re-formatting.)

Click on General Notes and look at the source. The weird quotes have been added.

Click Done then on Parrish, Denver Forrest again. A second set of weird quotes has been added. New quotes will be added every time you save the record.

### Expected result

Some way to correct this behavior.

### Actual result

You will see the trashed URLs.

## Other details

* Browser: any
* OS: Windows 7
* CKEditor version: CKEditor 4.7.3 (revision dee99e2)
![capture](https://user-images.githubusercontent.com/6639802/51061512-8d007680-15c1-11e9-96ce-713949118564.JPG)

* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment] 2019-01-23 09:14
Hello,

could you provide simplified reproduction steps? This test case is too dependant on the application you are referencing. Optimally you could provide some code sample using codepen.io or just directly pasting it in this ticket.

**Comment by stephenl314** [comment] 2019-01-25 13:12
Don’t close the ticket. I’m working on this.

**Comment by mlewand** [comment] 2019-02-15 16:12
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2019-02-15 16:12 UTC
Labels: status:pending
