### ISSUE TITLE
Notification when clicking the Paste button appears in wrong emplacement

### ISSUE THREAD

**Issue by sarahl123** [ckeditor/ckeditor-dev#2096] opened 2018-06-17 09:12 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

When using the paste button of ckeditor, a notification appears saying
"Press Ctrl+V to paste. Your browser doesn‘t support pasting with the toolbar button or context menu option."
The problem is that it appears in wrong emplacement (far away from the ckeditor bar)
This bug occurs only the first time I click on the paste button. When clicking again, the notification appears in the right place (close to the ckeditor bar)

### Expected result

When clicking on the paste button in the first time, the notification appears in the right place

### Actual result

When clicking on the paste button in the first time, the notification appears in the wrong place

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by msamsel** [comment] 2018-06-18 07:28
Hi @sarahl123,

could you provide sample where problem occur (some codepen.io, jsfiddle.net, etc.)? I've checked it on our demo here: https://cdn.ckeditor.com/4.9.2/full-all/samples/.

**Comment by jacekbogdanski** [comment] 2018-07-09 08:07
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-07-09 08:07 UTC
Labels: resolution:expired

**Comment by hkakumanu-ttc** [comment] 2018-07-24 18:35
I have the same problem as well.I will try to reproduce this

**Comment by hkakumanu-ttc** [comment] 2018-07-24 18:57
@sarahl123 Did you fix it?

**Comment by hkakumanu-ttc** [comment] 2018-07-25 16:46
I fixed this by updating my skins. My skins folder is out of date.
