### ISSUE TITLE
Output encoding issues 

### ISSUE THREAD

**Issue by mahmoud-abdelmonem** [ckeditor/ckeditor-dev#1694] opened 2018-02-20 10:00 UTC
Description removed.

**Comment by jacekbogdanski** [comment] 2018-02-20 16:17
Thank you for the report. We'll investigate your report.

Meanwhile I'll close this issue, as we're asking for sending security reports through [our contact form](http://cksource.com/contact). Actually information about this was missing in our template, so sorry for that.

Removed original description, the issue is being tracked in our security tracking system.

**Closed** 2018-02-20 16:18 UTC
