### ISSUE TITLE
Some errors logs generated

### ISSUE THREAD

**Issue by seblejeune** [ckeditor/ckeditor-dev#1045] opened 2017-10-13 09:09 UTC
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

I can't reproved easily this bug.

### Expected result

No errors logs

### Actual result

I get this log series, but the ckeditor keeps running
It's possible to disabled this logs ?
* Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 42 is larger than the node's length (0).
* Uncaught IndexSizeError: Failed to execute 'setEnd' on 'Range': The offset 2 is larger than the node's length (0).
* IndexSizeError: Index or size is negative or greater than the allowed amount

## Other details

* Browser: Chrome, Safari, IE, Firefox
* OS: Mac os x, Windows
* CKEditor version: 4.7

**Comment by beatadelura** [comment] 2017-10-16 11:26
@seblejeune I need more information. Could you please provide [codepen](https://codepen.io/), [jsbin](https://jsbin.com/?html,output) or [jsfiddle](https://jsfiddle.net/) example with **configuration** and **exact steps to reproduce**?

**Comment by msamsel** [comment] 2017-11-08 08:24
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-11-08 08:24 UTC
Labels: status:pending
