### ISSUE TITLE
IOS Safari image issue

### ISSUE THREAD

**Issue by OkHyeon** [ckeditor/ckeditor-dev#738] opened 2017-08-08 01:33 UTC
## Are you reporting a feature request or a bug?

When using CKEditor with iOS Safari, when you press enter after attaching an image, the page focus moves up and down.
How can I resolve this?

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: Safari
* OS: iOS 
* CKEditor version: 4
* Installed CKEditor plugins: …

**Comment by msamsel** [comment] 2017-08-08 07:39
Hi,

your problem seems to be similar to issue which is already reported. #498 
I'll close this issue as duplicated one.
If you think it's different issue. Then please provide more details. Some test page would be nice with details how to reproduce the problem.

**Closed by msamsel** 2017-08-08 07:39 UTC
