### ISSUE TITLE
CKEditor 4.8 IE 11 Chinese character input: Html conversion loses the last word in focus in editor

### ISSUE THREAD

**Issue by JohnCSMoodys** [ckeditor/ckeditor-dev#3321] opened 2019-08-08 15:32 UTC
## Type of report

Bug
CKEditor 4.0 IE 11 Chinese character input: Html loses the last word in focus in editor
## Provide detailed reproduction steps (if any)

1. IE 11 Chinese Character Input
2. Stay on the last character of last word
3. Application now takes html content of the editor and saves. We find the last word missing in IE 11 browser. This works fine for English language in IE11. Chrome browser works fine with all languages.

### Expected result
1. Html should not miss any content
*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: IE11
* OS: Windows 10
* CKEditor version: 4.8
* Installed CKEditor plugins: Refer http://ckeditor.com/builder/2bdfbacce18d569288d65af80dfeb520

**Comment by JohnCSMoodys** [comment] 2019-08-08 15:33
![image](https://user-images.githubusercontent.com/36516764/62716521-e69a1980-b9c7-11e9-9371-5e5cb90be302.png)

![image](https://user-images.githubusercontent.com/36516764/62716557-f580cc00-b9c7-11e9-8e6c-1cf2d21131db.png)

**Comment by Comandeer** [comment] 2019-08-09 15:48
I can't reproduce the error. Can you provide some minimal reproduction sample, e.g. on codepen.io?

**Comment by engineering-this** [comment] 2019-08-26 07:40
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by engineering-this** 2019-08-26 07:40 UTC
Labels: status:pending, type:bug

**Comment by JohnCSMoodys** [comment] 2019-10-17 20:52
Let me know if we can have a quick webex to demo the issue.
Is this issue related to this reported issue: https://github.com/ckeditor/ckeditor4/issues/676

**Comment by f1ames** [comment] 2019-10-22 06:55
Hello @JohnCSMoodys,
this is a duplicate of #676, same as #3590.
