### ISSUE TITLE
Couldn't close dialog after uploading img request failed(Blocked a frame with origin "https://xxx" from accessing a frame with origin "null")

### ISSUE THREAD

**Issue by ke1vin666** [ckeditor/ckeditor-dev#1581] opened 2018-02-05 06:51 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. in poor network condition
2. clicked upload img button and chose my picture
3. clicked upload button and send upload request
4. request failed（**essential condition**）
5. couldn't close upload dialog(clicked cancel or close button)

my ckeditor config:
```(javascript)
config: {
   extraPlugins: 'declaration',
   filebrowserImageUploadUrl: '/api/news/news_upload',
   image2_disableResizer: true,
   disallowedContent: 'img[style,height,width]',
   height: 800,
   font_names: '微软雅黑/Microsoft YaHei' + 'Arial/Arial, Helvetica, sans-serif;' +
        'Comic Sans MS/Comic Sans MS, cursive;' +
        'Courier New/Courier New, Courier, monospace;' +
        'Georgia/Georgia, serif;' +
        'Lucida Sans Unicode/Lucida Sans Unicode, Lucida Grande, sans-serif;' +
        'Tahoma/Tahoma, Geneva, sans-serif;' +
        'Times New Roman/Times New Roman, Times, serif;' +
        'Trebuchet MS/Trebuchet MS, Helvetica, sans-serif;' +
        'Verdana/Verdana, Geneva, sans-serif'
 }
```

### Expected result

Although request fail, dialog could close after clicking cancel or close button

### Actual result

Couldn't close dialog，console gave errors as follows:

ckeditor.js:125 Blocked a frame with origin "https://xxxx" from accessing a frame with origin "null".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "chrome-error". Protocols must match.

Uncaught DOMException: Blocked a frame with origin "https://xxxx" from accessing a cross-origin frame.
    &ensp;at CKEDITOR.dom.element.getFrameDocument (https://xxxx/static/ckeditor/ckeditor.js:125:144)
    &ensp;at file.getInputElement (https://xxxx/static/ckeditor/ckeditor.js:558:421)
    &ensp;at file.getValue (https://xxxx/static/ckeditor/ckeditor.js:563:111)
    &ensp;at file.isChanged (https://xxxx/static/ckeditor/ckeditor.js:529:522)
    &ensp;at https://xxxx/static/ckeditor/ckeditor.js:590:85
    &ensp;at t (https://xxxx/static/ckeditor/ckeditor.js:589:312)
    &ensp;at CKEDITOR.dialog.<anonymous> (https://xxxx/static/ckeditor/ckeditor.js:590:66)
    &ensp;at CKEDITOR.dialog.n (https://xxxx/static/ckeditor/ckeditor.js:10:224)
    &ensp;at CKEDITOR.dialog.fire (https://xxxx/static/ckeditor/ckeditor.js:12:47)
    &ensp;at button.onClick (https://xxxx/static/ckeditor/ckeditor.js:613:82)

It seemed that the iframe didn't have origin before http response successfully
## Other details

* Browser: chrome 63.0
* OS: windows10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: 
a11yhelp
basicstyles
bidi
blockquote
button
clipboard
contextmenu
copyformatting
deselect
dialog
dialogui
elementspath
enterkey
entities
fakeobjects
filebrowser
find
floatingspace
floatpanel
font
format
horizontalrule
htmlwriter
image
image2
indent
indentlist
justify
lineutils
link
list
listblock
magicline
maximize
menu
newpage
notification
panel
pastefromword
pastetext
popup
preview
removeformat
resize
richcombo
selectall
selectallcontextmenu
showborders
sourcearea
specialchar
stylescombo
tab
toolbar
undo
widget
widgetselection
wysiwygarea

**Comment by msamsel** [comment] 2018-02-07 08:51
Error which you provide seems to be related to some different [thing](https://stackoverflow.com/questions/25098021/securityerror-blocked-a-frame-with-origin-from-accessing-a-cross-origin-frame).

Does your problem occur **only** with poor internet connection? Is it possible for you to prepare some kind of test page, where I could inspect the problem more precisely? Also could you remove all non-default plugins from the editor to have sure that the issue is not related to any 3rd party plugins included inside editor?

**Comment by msamsel** [comment] 2018-03-05 08:27
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed** 2018-03-05 08:27 UTC
Labels: status:pending
