### ISSUE TITLE
MSIE: Paste from Word has problems with List Indentation in MSIE

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor-dev#840] opened 2017-08-30 08:00 UTC
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

Possibly similar to this one:

* #544

## Provide detailed reproduction steps (if any)

1. Use MS Internet Explorer 11 (could not be reproduced in Chrome, Firefox and Edge)
2. Mark all and copy from the attached word document
3. Paste to CKEditor (e. g. at https://ckeditor.com/)

### Expected result

Both lists end with "Sit" and "Amet" is pasted outside the list into a new paragraph.

### Actual result

The first list is pasted wrong: "Amet" is part of the previous element "Sit" rather than pasted to a new paragraph. The second list pastes well.

The first list is from an existing Word document which I reduced to Lorem Ipsum, just replacing the words, not the format. The second list is how I would create new lists in Word. So there must be something special in the format of the first list.

See also attached screenshot.

## Other details

* Browser: MS Internet Explorer 11 (others not affected)
* OS: Windows 10
* CKEditor version: 4.7.2

**Comment by mmichaelis** [comment] 2017-08-30 08:02
* [CKEditor-Paste-from-Word-Lists-Bug.docx](https://github.com/ckeditor/ckeditor-dev/files/1262791/CKEditor-Paste-from-Word-Lists-Bug.docx)

![2017-08-30 09_53_12-ckeditor com _ the best web text editor for everyone - internet explorer](https://user-images.githubusercontent.com/71911/29861668-41c569c2-8d6a-11e7-82f6-cc78e3f43235.png)

**Comment by msamsel** [comment] 2017-09-01 08:01
I was able to confirm the issue. I wasn't able find out which settings in word file cause the issue. In Wod2016 `Amet` word is not marked as part of the list item, but in IE11 is paste as part of it. Raw clipboard data which receives editor is below: 
```
<font color="#000000" face="Times New Roman" size="3">

</font><p style="margin: 0in 0in 0pt;"><span lang="DE"><font color="#000000" size="3">Lorem Ipsum</font></span></p><font color="#000000" face="Times New Roman" size="3">

</font><ul style="list-style-type: disc; direction: ltr;"><li style="font-weight: normal;"><p style="font-weight: normal; margin-top: 0in; margin-bottom: 0pt; mso-list: l0 level1 lfo1; tab-stops: list .5in;"><span lang="DE">Dolor</span></p></li><li style='color: rgb(0, 0, 0); font-family: "Arial",sans-serif; font-size: 11pt; font-weight: normal;'><p style='color: rgb(0, 0, 0); font-family: "Arial",sans-serif; font-size: 11pt; font-weight: normal; margin-top: 0in; margin-bottom: 0pt; mso-list: l0 level1 lfo1; tab-stops: list .5in;'><span lang="DE">Sit</span></p><p style='color: rgb(0, 0, 0); font-family: "Arial",sans-serif; font-size: 11pt; font-weight: normal; margin-top: 0in; margin-bottom: 0pt;'><span lang="DE">Amet</span></p></li></ul><font color="#000000" face="Times New Roman" size="3">





</font>
```

**Comment by mmichaelis** [comment] 2017-09-01 08:34
Here my result analyzing the clipboard with [Free Clipboard Viewer for Windows](http://www.freeclipboardviewer.com/):

* [CKEditor-840-pastefromword-FreeClipViewer.txt](https://github.com/ckeditor/ckeditor-dev/files/1269632/CKEditor-840-pastefromword-FreeClipViewer.txt)

So while the oldstyle-format (which is broken) uses `p.MsoBodyText` with `style` `mso-list`, the new Word 2016 format (which works) uses `p.MsoListParagraphCxSp*`.

It should be noted that the original document (i. e. the first list) is of unknown source (provided by a customer). It might be an old Word format as well as from some other platform (Mac OS for example).

**Comment by jswiderski** [comment] 2017-10-19 14:48
I have just checked how native IE11 sees HTML pasted from Word (no editor was used):

```
<p style="margin: 0cm 0cm 0pt;"><span lang="DE"><font face="Arial">Lorem Ipsum</font></span></p>

<ul style="list-style-type: disc; direction: ltr;"><li style='color: rgb(0, 0, 0); font-family: "Arial","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal;'><p style='color: rgb(0, 0, 0); font-family: "Arial","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 0pt; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;'><span lang="DE">Dolor</span></p></li><li style='color: rgb(0, 0, 0); font-family: "Arial","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal;'><p style='color: rgb(0, 0, 0); font-family: "Arial","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 0pt; mso-list: l0 level1 lfo1; tab-stops: list 36.0pt;'><span lang="DE">Sit</span></p><p style='color: rgb(0, 0, 0); font-family: "Arial","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 0pt;'><span lang="DE">Amet</span></p></li></ul>

<p style="margin: 0cm 0cm 8pt;"><span lang="DE"><font face="Calibri">&nbsp;</font></span></p>

<p style="margin: 0cm 0cm 8pt;"><span lang="DE"><font face="Calibri">Lorem Ipsum</font></span></p>

<ul style="list-style-type: disc; direction: ltr;"><li style='color: rgb(0, 0, 0); font-family: "Calibri","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal;'><p style='color: rgb(0, 0, 0); font-family: "Calibri","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 0pt; mso-list: l1 level1 lfo2;'><span lang="DE">Dolor</span></p></li><li style='color: rgb(0, 0, 0); font-family: "Calibri","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal;'><p style='color: rgb(0, 0, 0); font-family: "Calibri","sans-serif"; font-size: 11pt; font-style: normal; font-weight: normal; margin-top: 0cm; margin-bottom: 8pt; mso-list: l1 level1 lfo2;'><span lang="DE">Sit</span></p></li></ul>

<p style="margin: 0cm 0cm 8pt;"><span lang="DE"><font face="Calibri">Amet</font></span></p>
```

As you can see the "Amet" word is included in the list, so this is not editor issue but a bug in IE11.  THe problem is that MS team no longer fixes IE11 issues so we cannot even report this. We can only close it and mark it as won't fix.

@mmichaelis CKEditor receives HTML processed by browser. If word "Amet" is included in the list there is no way for the editor to know that it should not be there. I'm sorry but there is nothing we can do here.

**Closed by jswiderski** 2017-10-19 14:48 UTC
Labels: browser:ie11, plugin:pastefromword, status:confirmed, type:bug

**Comment by mmichaelis** [comment] 2017-10-21 15:46
@jswiderski Thanks for investigating!
