### ISSUE TITLE
You can paste easyimage widget inside another easyimage caption

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-dev#1645] opened 2018-02-12 09:41 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open sample with easyimage widget. 
http://ckeditor.test/plugins/easyimage/samples/easyimage.html
2. Select and copy one of widgets.
3. Paste into another widgets caption.

### Expected result

Nothing happens.

### Actual result
![1](https://user-images.githubusercontent.com/23366849/36090568-216a9a54-0fe1-11e8-8a38-30c180e68bc7.gif)
![2](https://user-images.githubusercontent.com/23366849/36090571-23804ea6-0fe1-11e8-82ba-e50307bd23e0.gif)

If you paste into widget with empty captions widget caption cant be focused or showed.
If you paste it into widget with caption than widget is pasted inside caption.

## Other details

* Browser: Any

**Comment by mlewand** [comment] 2018-02-12 09:45
Duplicate of #1468.

**Closed by mlewand** 2018-02-12 09:45 UTC
Labels: plugin:easyimage, type:bug
