### ISSUE TITLE
Bug with the Russian version of the image loader

### ISSUE THREAD

**Issue by Brud0** [ckeditor/ckeditor-dev#692] opened 2017-07-28 09:58 UTC
## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

Bug with the Russian version of the image loader.

## Provide detailed reproduction steps (if any)

1. I click on the "Image" button in the editor
2. Turn to the second tab "Download file"

### Expected result

Good layout.

### Actual result

![clip2net_170727174416](https://user-images.githubusercontent.com/30524138/28712595-62ed334a-7394-11e7-96e0-0024d34628ef.png)
I see the crooked layout

## Other details

* Browser: Google Chrome  56.0.2924.76 (64-bit)
* OS: Windows 7
* CKEditor version: CKEditor 4.7.0 (Standard) (revision 320013d56)
![image](https://user-images.githubusercontent.com/30524138/28712257-3fdc1ba6-7393-11e7-8389-a135f3bf57ee.png)

* Installed CKEditor plugins: justify,image2,youtube

**Comment by beatadelura** [comment] 2017-07-31 08:54
@Brud0  I can't reproduce this issue with CKEditor version 4.7.0 and 4.7.1 on Chrome 59. Could you please provide [codepen](https://codepen.io/), [jsbin](https://jsbin.com/?html,output) or [jsfiddle](https://jsfiddle.net/) example with configuration and exact steps to reproduce? And also please check whether this problem occurs on Chrome 59 and newest.

**Comment by beatadelura** [comment] 2017-08-16 08:56
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by beatadelura** 2017-08-16 08:56 UTC
Labels: status:pending

**Comment by 7iomka** [comment] 2017-10-22 19:11
@Brud0, hello my russian friend! You solved this problem? I'm seeing this problem in the latest versions of ckeditor and chrome (
Thanks!
