### ISSUE TITLE
Pasting as plain text retaining format

### ISSUE THREAD

**Issue by JamesPreston1993** [ckeditor/ckeditor-dev#620] opened 2017-07-07 07:57 UTC
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Create an inline editor instance
2. Set `forcePasteAsPlainText` to `true` in the config
2. Insert formatted text into the editor (e.g. `<strong>Bold</strong> <span>My span</span>`
3. Copy formatted text and paste into the editor (or another instance of an editor)

### Expected result

The pasted text should have all formatting removed and replaced with plain text

### Actual result

The format of the text is retained on paste

## Other details

* Browser: Chrome, Firefox, IE, Safari
* OS: Windows 10
* CKEditor version: 4.7.0
* Installed CKEditor plugins: sharedspaces, font

NOTE:
This was tested in IE but did not occur.
Pasting from external sources (e.g. Word or HTML from a page) does not exhibit the same behaviour

**Comment by mlewand** [comment] 2017-08-28 14:37
@beatadelura is it Chrome only (title, original report) or does it affect any other browser (labels)? In case it does please, update the title / "Other details" section accordingly.

**Comment by beatadelura** [comment] 2017-08-28 15:11
@mlewand It occurs in other browsers as well. Issue updated.

**Comment by kreatIL** [comment] 2017-09-21 07:20
Same problem here. Browsers: Chrome, FF, Safari. Force pasting as plain text is still working in IE only.

**Comment by msamsel** [comment] 2018-03-19 15:35
I wasn't able to reproduce the problem in current editor version (4.9.0).
I test it on MacOS under Chrome, Firefox, Safari and Windows 10 x64 with Edge, Chrome, Firefox.
Each of this browser paste content without formatting.
I've used this page for testing purpose. https://codepen.io/msamsel/pen/zWogdX
@JamesPreston1993, @kreatIL problem seems to be solved. Or do I missed something? If so, please provide more details how to reproduce bug.

**Comment by kreatIL** [comment] 2018-03-19 16:48
After doing the upgrade to 4.9.0 I couldn't reproduce the problem either. I think this issue could be marked as solved.

**Comment by mlewand** [comment] 2018-03-19 17:06
Thanks for help @kreatIL that gives us more confidence.

Let's wait for the OP. If there's no response in our standard 2 weeks we can close the issue.

**Comment by JamesPreston1993** [comment] 2018-03-20 08:09
I can still reproduce it in the scenario it was logged and using the codepen provided by @msamsel 

The steps to reproduce are to format the text in the editor, copy the formatted text from within the editor and paste it into to the same editor instance or a different editor instance

**Comment by msamsel** [comment] 2018-03-20 11:00
@JamesPreston1993 so the issue appears only when you copy content between editors or inside editor? I thought that text came from external place.

I see that wrong behaviour is possible to reproduce in such scenario on both inline and iframe editor.

**Comment by JamesPreston1993** [comment] 2018-03-20 11:12
@msamsel That's correct, it seems to behave as expected when copying from external sources

**Comment by msamsel** [comment] 2018-03-20 11:30
@JamesPreston1993 thank you for the clarification :)

**Comment by Comandeer** [comment] 2018-04-10 16:00
Closed in #1830. Fix will be included in 4.10.0 release.

**Closed by Comandeer** 2018-04-10 16:00 UTC
Labels: browser:chrome, browser:firefox, browser:ie, browser:ios, status:confirmed, type:bug
