### ISSUE TITLE
Scrollbar in drop-down list disappears after initial display

### ISSUE THREAD

**Issue by Yanual** [ckeditor/ckeditor-dev#1390] opened 2018-01-01 06:57 UTC
## Issue is already reported on old issue tracking
see <https://dev.ckeditor.com/ticket/14716>
## Reproduction steps
1. Go to <https://ckeditor.com/ckeditor-4> with **chrome** browser
2. Click on the Styles drop-down in the Toolbar so the list of styles is displayed 
3. Click away so the list of styles is hidden 
4. Click on the Styles drop-down a second time - notice that when the list of styles is re-displayed the vertical scrollbar is now missing. 
### Expected result
Display Scrollbar each time the list is displayed
### Actual result
After initial display the Scrollbar disappears
## Other details
* Browser: Chrome 62.0.3202.75
* CKEditor version: 4.8.1
## Additional Informations
This seems to be a chromium issue, see <https://bugs.chromium.org/p/chromium/issues/detail?id=641881>
### Possible solution
For me the problem appears with the list of font sizes (I do not use styles and formats, incompatible with BBCode).
I made a change in **panel / plugin.js on line 370** that works without disrupting the online menus and the color list.
Replace the code in line 370 (4.8.1 version) with this one :
```JavaScript
// To avoid Chrome issue see https://bugs.chromium.org/p/chromium/issues/detail?id=641881
if ( CKEDITOR.env.chrome && this.attributes.role == 'listbox' && this.element.$.className == 'cke_panel_block' ) {
	this.element.setStyle( 'display', 'inline' );
} else {
	this.element.setStyle( 'display', '' );
}
```

Could you tell me if this is not awkward for other uses of CKEditor and if so it may help other people ?

**Comment by msamsel** [comment] 2018-01-05 08:32
I was able to confirm the issue.

**Comment by mlewand** [comment] 2018-01-05 08:47
@Yanual as you mentioned this is an upstream issue, and all we can do is hack to get a way around it. Please bump the original chromium issue (star it and/or put a comment) so that they see some interest in this issue.

**Comment by Yanual** [comment] 2018-01-05 11:03
I just did it and I asked them why the status of the issue remains **WontFix**

**Comment by mlewand** [comment] 2018-01-05 14:28
They claimed that's no longer reproducible:

> No longer reproduces in 60 or later.

That's why, though my bet is that the tester had used wrong environment where it's not reproducible. AFAIR it's Windows only.

**Comment by Yanual** [comment] 2018-01-05 15:38
Like I said I reproduce it on Browser: Chrome 62.0.3202.75 and on comment #16 he said  -> I can confirm this issue happening in Windows and Linux in Chrome 63. It doesn't happen in MacOS with the "always show scrollbars" setting on.
That's why I'm discussing their analysis of feedback.

**Comment by mlewand** [comment] 2018-01-08 21:37
It looks like it's fixed on Chrome 65. We can already close this issue as it's an upstream. I'm happy to see it's fixed though. [Version 65 is estimated to get stable at the beginning of March](https://www.chromium.org/developers/calendar), so let's keep an eye on that.

**Closed by mlewand** 2018-01-08 21:37 UTC
Labels: browser:chrome, status:confirmed, type:bug

**Comment by williamsherlock** [comment] 2018-02-23 12:11
This solution worked for me:
Go to the ckeditor.js into callFunction and add this line before return.

$(".cke_combopanel").css("width", 'auto');
