### ISSUE TITLE
CkEditor After user has copied the content in the ck editor and user clicks on full screen option the screen display wrong in Mozilla Browser

### ISSUE THREAD

**Issue by trilok2017** [ckeditor/ckeditor-dev#3310] opened 2019-08-02 10:00 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. … copy the content in CKEditor.
2. …Now click on the full-screen icon in the CKeditor.
3. …CKeditor options are not displaying.

### Expected result

*What is the expected result of the above steps?*

### Actual result
After the user has entered the content in the CK editor and the user clicks on the full-screen option the screen should display all the option of CKEditor.

*What is the actual result of the above steps?*

## Other details

* Browser: Mozilla Firefox
* OS: … Windows 10
* CKEditor version: …4
* Installed CKEditor plugins: …

![90c315de-aa19-4aae-921d-72e0afae836e](https://user-images.githubusercontent.com/24887164/62362512-bde2d180-b53a-11e9-8e49-fda854b8cab8.png)

**Comment by f1ames** [comment] 2019-08-02 10:43
Hello @trilok2017,
I'm not able to reproduce reported issue with `4.12.1` version (http://cdn.ckeditor.com/4.12.1/full-all/samples/) on Firefox 68. Can you provide any sample (e.g. codepen) where this issue is reproducible?

**Comment by Dumluregn** [comment] 2019-08-16 15:06
Hi, 
It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2019-08-16 15:06 UTC
Labels: status:pending, type:bug
