### ISSUE TITLE
Inserting an input to selected cells removes the cell

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor-dev#788] opened 2017-08-14 11:25 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Create the 3x2 table.
2. Fill the first row with some text.
3. Select the first row.
4. Insert an input, i.e. `radio button`.

### Expected result

Input should be inserted into the first cell.

### Actual result

The first cell was removed and second cell changed position. 

## GIF
![bug_cke4](https://user-images.githubusercontent.com/20988892/29269764-8b8d9d0a-80f3-11e7-8641-e5dee44b1a19.gif)

## Other details

* Browser: All browsers
* OS: Windows 10
* CKEditor version: 4.7.2

**Comment by mlewand** [comment] 2017-08-14 11:28
Duplicate of #770.

**Closed by mlewand** 2017-08-14 11:28 UTC
Labels: type:bug
