### ISSUE TITLE
Content text - font text color & background color indicator not working

### ISSUE THREAD

**Issue by zachisit** [ckeditor/ckeditor-dev#573] opened 2017-06-28 19:00 UTC
## Are you reporting a feature or a bug?
Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

- type a word
- select the work
- change the color of the text to red
- click on that word and select the font color dropdown
- see that the color choice is not indicated (e.g. shadow around color-in-use tile)

### Expected result
When I highlight the word and go to font color dropdown, I expect to see the selected color for that changed word

*What is the expected result of the above steps?*
When I highlight the word and go to font color dropdown, I expect to see the selected color for that changed word

### Actual result
Nothing is highlighted in the font color dropdown

*What is the actual result of the above steps?*

## Other details

* Browser: …Any
* OS: …Any
* CKEditor version: …Latest
* Installed CKEditor plugins: …N./A

**Comment by beatadelura** [comment] 2017-06-29 07:32
@zachisit I can't reproduce this issue. Could you please give some more information related to this? I checked `4.7.0` and `4.7.1` CKEditor version on Chrome, Safari, Firefox, IE11, Edge, IE10, IE9.

Please look at the demo below:

[color_indicator.zip](https://github.com/ckeditor/ckeditor-dev/files/1111168/color_indicator.zip)

**Comment by beatadelura** [comment] 2017-07-17 07:30
@zachisit It's been a while and we didn't get any information from you so I'm closing this issue.

**Closed by beatadelura** 2017-07-17 07:30 UTC
Labels: status:pending, type:bug
