### ISSUE TITLE
Sourcedialog plugin in Builder doesn't include all files (plugin.js, icons, others)

### ISSUE THREAD

**Issue by trnelson** [ckeditor/ckeditor-dev#990] opened 2017-10-01 08:02 UTC
## Are you reporting a feature request or a bug?

Other (Bug in Builder)

## Provide detailed reproduction steps (if any)

Downloading CKEditor from online builder, including Sourcedialog plugin doesn't include all files. Only the /dialogs directory and files are included. The plugin.js file, icons, etc. are not included. I had to manually download the package and copy it to my plugins directory.

### Expected result

All plugin files should be included.

### Actual result

All plugin files are not included.

## Other details

* Browser: Google Chrome
* OS: OS Sierra
* CKEditor version: 4.7
* Installed CKEditor plugins: ...

**Comment by beatadelura** [comment] 2017-10-02 07:53
@trnelson It's correct that `sourcedialog` plugin is not included in CKEditor online builder by default. This is an additional plugin which if it's needed can be added to the package by clicking `Add to my editor` button [here](https://ckeditor.com/addon/sourcedialog) and then `Build my editor.`

**Comment by mlewand** [comment] 2017-10-02 09:10
@beatadelura I think you've missed the issue. The problem here is that some files are missing in the output build.

@trnelson It's by design that most of these files are missing, that's exactly how building/minification works. plugin.js and lang entries get merged to the ckeditor.js / lang.js respectively. Icons get merged into one bigget icon sprite, so that loading editor requires less HTTP requests thus loading up faster. Some parts are not inlined into plugin.js, e.g. dialogs - that's why you're seeing it in the directory.

Please let us know if it explains your issue.

**Comment by msamsel** [comment] 2017-11-29 09:07
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-11-29 09:07 UTC
Labels: status:pending

**Comment by dryoma** [comment] 2018-08-31 09:18
Hey @mlewand 

I'm not sure if I should create a new Issue. I have the same problem. Not sure about the OP, but in my case it prevents CKEditor from working. It explicitly tries to load the `plugin.js` from the `widget` plugin and some other plugins that are bundled. I assume, it's because I have some custom plugins that have `requires: 'widget';`, but shouldn't this dependencies be resolved by looking inside the ckeditor.js code instead?

CKEditor version is 4.10.0
