### ISSUE TITLE
Styling inline editor nested inside table causes styles leaking

### ISSUE THREAD

**Issue by markussc** [ckeditor/ckeditor-dev#2403] opened 2018-09-12 06:37 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open http://jsfiddle.net/r9bfgwsk.
1. Type foo inside a table cell.
1. Select whole text ( with text selection, not table selection).
1. Mark selected text bold.

### Expected result

The selected text is bold.

### Actual result

The table cell gets a grey background. The css-class "cke_table-faked-selection" is added to the table's td-element

## Other details

* Browser: Firefox 62.0
* OS: Windows 10
* CKEditor version: 4.10.0
* Installed CKEditor plugins: sharedspace,lite,undo

**Comment by jacekbogdanski** [comment] 2018-09-12 08:02
Hello,

I tried to reproduce your issue without success. Could you check if you can still reproduce it with clean CKEditor installation (without external plugins)? You could use https://ckeditor.com/latest/samples/ to check if it works correctly.

**Comment by markussc** [comment] 2018-09-12 11:54
It's a bit weird. When I download https://github.com/ckeditor/ckeditor-releases/archive/4.10.1/4.10.1.zip , the file ckeditor.js contains at lines 1056 / 1057:
`if(p.active&&c&&p.first.getAscendant("table").equals(c.getAscendant("table"))){g=e(p.first,c);if(!p.dirty&&1===g.length&&!a(f.data.getTarget()))return d(b,"mouseup"===f.name);p.dirty=!0;p.last=c;l(b,g)}}function h(a){var b=(a=a.editor||a.sender.editor)&&a.getSelection(),c=b&&b.getRanges()||[],e;if(b&&(d(a),b.isInTable()&&b.isFake)){1===c.length&&c[0]._getTableElement()&&c[0]._getTableElement().is("table")&&(e=c[0]._getTableElement());
e=q(b,e);a.fire("lockSnapshot");for(b=0;b<e.length;b++)e[b].addClass("cke_table-faked-selection");`

The interesting part is the last statement, i.e. adding class "cke_table-faked-selection". This will be added to all ascendant table elements. In my case also the surrounding table. I can fix it if prepending a check like:
`if (!e[b].parent().hasClass("cke_editable") {continue;}`
I don't find this piece of code in the src/ directory anywhere. Where does it come from in the released zip ?

**Comment by jacekbogdanski** [comment] 2018-09-14 09:35
As I understand your issue is about creating table selection when selecting whole text and applying style. If so, this issue is not limited to forms - exists for any element inside table cell:

![tableselection](https://user-images.githubusercontent.com/10279586/45542220-77489380-b811-11e8-8819-a62a80ced5d7.gif)

I agree that selection shouldn't be changed when styling text selection inside a table cell. Please, let us know if I'm wrong about the issue.

About our repositories structure - `ckeditor-dev` is used for development purposes and may be unstable. It's probably best (especially for production) if you stick with `ckeditor-releases`. However if you fine with some possible issues, `ckeditor-dev` gives you bleeding edge CKEditor version.

**Comment by jacekbogdanski** [comment] 2018-09-14 09:40
I updated the title and your reproduction steps to better reflect the issue.

**Comment by sasgeoff** [comment] 2018-09-25 19:57
Also, the darkgray background color remains even after selecting other elements.

**Comment by markussc** [comment] 2018-09-25 20:05
What @jacekbogdanski added in the video above is not exactly what we are experiencing. We have a table where multiple ckeditor fields (and other content) are contained. When we mark text within a ckeditor field and make it bold (for example), the whole td-table element where the ckeditor field is in becomes gray. This means the grey background is not in the ckeditor field, but around it. This false behaviour comes from the code snipped cited above. See my screenshot:
![grafik](https://user-images.githubusercontent.com/6805756/46039553-4d934480-c10e-11e8-8e48-db0e240a14b0.png)

**Comment by jacekbogdanski** [comment] 2018-09-26 21:28
@sasgeoff broken selection responsiveness after toggling styles may be caused by #2419. However, I don't have an issue with remaining cell background color on selection change. Can you provide more details e.g. OS and browser? Are you able to reproduce the issue using https://ckeditor.com/latest/samples/ ? 

@markussc I'm not able to reproduce the issue with a grey background - are you sure that it's not your custom CSS styles for `.cke_table-faked-selection` class? Can you reproduce the same issue using https://ckeditor.com/latest/samples/ ?

**Comment by sasgeoff** [comment] 2018-09-27 16:42
I have reproduced this issue in jsfiddle: 
http://jsfiddle.net/r9bfgwsk

OS: Windows 10,   browser: Chrome,  CKEditor version: 4.10.1

**Comment by markussc** [comment] 2018-09-27 18:05
Thanks @sasgeoff , this corresponds exactly to my issue.

**Comment by jacekbogdanski** [comment] 2018-09-28 07:08
Thanks! Now we are on the same page. I can confirm the issue and I will update the issue description accordingly to new information. Also, I found that the issue with the blue background caused by fake selection is already reported here: #2357, so there is no need for extracting it into a separate ticket.

**Comment by markussc** [comment] 2018-10-04 15:51
@jacekbogdanski : just created a simple fix for it (#2459). Maybe you don't want to merge it like this, but it should give an idea where to start with.

**Comment by jacekbogdanski** [comment] 2018-10-11 13:42
@sasgeoff I'm not able to give you information when the issue will be fixed - currently, we have a lot of work on the table. However, you can give this issue thumbs up :+1: so we will see your interest in fixing it.

@markussc thanks for your input!

**Comment by markussc** [comment] 2018-10-16 14:59
FYI: Bug was introduced in 4.7.0 (last working version is 4.6.2)

**Comment by sasgeoff** [comment] 2018-11-08 15:52
My management is asking me to escalate this issue. They see this as a block that is preventing us from obtaining some very important security updates. This issue breaks our product and so prevents us from moving to the latest version. Please consider this fix with the highest priority. We appreciate your focus on this issue as soon as possible.

**Comment by Comandeer** [comment] 2018-12-05 16:44
Fixed in 4.11.2.

**Closed by Comandeer** 2018-12-05 16:44 UTC
Labels: plugin:tableselection, status:confirmed, support, type:bug

**Comment by lslowikowska** [comment] 2019-01-07 20:53
Hey @sasgeoff, the release is planned for January 9. You can always check the release dates in the [milestones](https://github.com/ckeditor/ckeditor-dev/milestones) 🙂

**Comment by epchristi** [comment] 2020-04-21 01:52
I know this is closed, but I have seen this error reproduce in the latest version.

**Comment by f1ames** [comment] 2020-04-21 05:53
@epchristi if you could provide repro steps, we will be able to investigate this issue.
