### ISSUE TITLE
Pasting empty list and converting it to different list type throws error

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#2438] opened 2018-09-25 13:32 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Paste the below code in Source mode of [full preset sample](https://sdk.ckeditor.com/samples/fullpreset.html).
```
<p><br></p><ul></ul><ul><li><a href="https://powerusers.microsoft.com/plugins/common/feature/oauth2sso/sso_login_redirect?referer=https%3A%2F%2Fpowerusers.microsoft.com%2Ft5%2FPowerApps-Community%2Fct-p%2FPowerApps1">Register</a></li><li><br></li><li>·</li><li><br></li><li><a href="https://powerusers.microsoft.com/plugins/common/feature/oauth2sso/sso_login_redirect?referer=https%3A%2F%2Fpowerusers.microsoft.com%2Ft5%2FPowerApps-Community%2Fct-p%2FPowerApps1">Sign In</a></li><li><br></li><li>·</li><li><br></li><li><a href="https://powerusers.microsoft.com/t5/help/faqpage">Help</a></li></ul><p><br></p>
```
**NOTE:** Starting from CKEditor 4.8 it is enough to paste just the empty list `<ul></ul>` to get the error.

2. Switch to wysiwyg and click inside the editor to focus is
3. Press Ctrl+A to select all content
4. Click on numbered or bulleted list button 

### Expected result

Hard to say because Empty lists is not something standard:
1. Empty `li` element gets created in empty list and it gets converted to different list type in necessary.
2. Empty list gets removed
3. Nothing or `ul` gets converted to empty `ol` if numbered list was pressed

### Actual result

JavaScript error gets thrown:
**Message:** Cannot read property 'listNode' of null
**URI:** /ckeditor-dev/plugins/list/plugin.js
**Line:**  334

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.0+
* Installed CKEditor plugins: List

**Comment by mlewand** [comment] 2018-09-25 14:48
Looks clearly like a duplicate of #2411 to me.

**Comment by msamsel** [comment] 2018-09-26 08:18
I have some prototype of solution for the #2411 and it's fix throwing error in this case too. We could merge those 2 issues together and move any further discussion to that issue.

Approach which I used is just preventing of throwing error. This empty `ul` will remain in markup as user want to paste it.

**Closed by msamsel** 2018-09-26 08:18 UTC
Labels: plugin:list, status:confirmed, support, type:bug
