### ISSUE TITLE
Path for tableselection.css in ckeditor.js includes double-slash, causing 404 when hosting assets in CDN

### ISSUE THREAD

**Issue by trnelson** [ckeditor/ckeditor-dev#793] opened 2017-08-17 03:46 UTC
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

In a quick search, I did not see this issue reported.

## Provide detailed reproduction steps (if any)

1. Create custom package including _tableselection_ plugin. I've included my build-config.js file below, and here is the direct link: http://ckeditor.com/builder/download/838512d45484f864e769d259de4c9403
2. Open the _ckeditor.js_ file in a text editor.
3. Notice around line 1161 this line: `CKEDITOR.document.appendStyleSheet(this.path+"/styles/tableselection.css")}`
4. The actual output of this results in two slashes before `styles` (like `plugins//styles/tableselection.css`)

When hosting these assets in a CDN like Azure, the double slash causes a 404, but IIS is able to handle this without any issue.

### Expected result

CSS file should be found at the output path.

### Actual result

When hosting assets via CDN, the double slash in the CSS URL causes a 404.

## Other details

* Browser: N/A
* OS: Azure CDN
* CKEditor version: 4.7.1
* Installed CKEditor plugins: build-config.js included below

## build-config.js File

```
/**
 * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/**
 * This file was added automatically by CKEditor builder.
 * You may re-use it at any time to build CKEditor again.
 *
 * If you would like to build CKEditor online again
 * (for example to upgrade), visit one the following links:
 *
 * (1) http://ckeditor.com/builder
 *     Visit online builder to build CKEditor from scratch.
 *
 * (2) http://ckeditor.com/builder/838512d45484f864e769d259de4c9403
 *     Visit online builder to build CKEditor, starting with the same setup as before.
 *
 * (3) http://ckeditor.com/builder/download/838512d45484f864e769d259de4c9403
 *     Straight download link to the latest version of CKEditor (Optimized) with the same setup as before.
 *
 * NOTE:
 *    This file is not used by CKEditor, you may remove it.
 *    Changing this file will not change your CKEditor configuration.
 */

var CKBUILDER_CONFIG = {
	skin: 'bootstrapck',
	preset: 'full',
	ignore: [
		'.DS_Store',
		'.bender',
		'.editorconfig',
		'.gitattributes',
		'.gitignore',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'README.md',
		'.travis.yml',
		'bender-err.log',
		'bender-out.log',
		'bender.ci.js',
		'bender.js',
		'dev',
		'gruntfile.js',
		'less',
		'node_modules',
		'package.json',
		'tests'
	],
	plugins : {
		'a11yhelp' : 1,
		'about' : 1,
		'basicstyles' : 1,
		'bidi' : 1,
		'blockquote' : 1,
		'ckeditor-gwf-plugin' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'contextmenu' : 1,
		'copyformatting' : 1,
		'dialogadvtab' : 1,
		'div' : 1,
		'elementspath' : 1,
		'emojione' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'flash' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'format' : 1,
		'forms' : 1,
		'horizontalrule' : 1,
		'html5video' : 1,
		'htmlwriter' : 1,
		'iframe' : 1,
		'image' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'language' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'magicline' : 1,
		'maximize' : 1,
		'newpage' : 1,
		'pagebreak' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'preview' : 1,
		'print' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'save' : 1,
		'scayt' : 1,
		'selectall' : 1,
		'sharedspace' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'smiley' : 1,
		'sourcearea' : 1,
		'sourcedialog' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'tab' : 1,
		'table' : 1,
		'tableselection' : 1,
		'tabletools' : 1,
		'templates' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'widget' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1,
		'youtube' : 1
	},
	languages : {
		'en' : 1
	}
};
```

**Comment by mlewand** [comment] 2017-08-17 08:55
Good news: @mflorea already fixed this in #497, we're unrolling this fix today with the release of 4.7.2. Stay tuned!

Duplicate of #582.

**Closed by mlewand** 2017-08-17 08:55 UTC
