### ISSUE TITLE
unwanted duplicated string —— when using Chinese Pinyin Input Method in ckedit

### ISSUE THREAD

**Issue by whyYuehao** [ckeditor/ckeditor-dev#518] opened 2017-06-16 07:52 UTC
Bug:
After updated with version 4.7, we found the edit canvas of ckedit always repeat keyboard key names before Chinese characters when using Pinying. Surprisingly, it’s back normal when delete all the mixed input Latin characters and Chinese characters.
For example, step1: key in pinying “jintian”, the edit canvas shows “jintian今天”; step2: delete “jintian今天”; step3: key in pinying “jintian” again, the edit canvas shows normal as “今天”.

It’s very urgent for us to adopt the ckedit in our internal project. You are really appreciated that this issue be fixed soon.

![](https://static.dingtalk.com/media/lALO24BGJs0BVc0EBw_1031_341.png_620x10000q90g.jpg)

**Comment by beatadelura** [comment] 2017-07-07 07:36
@whyYuehao Could you please provide more information? E.g. what kind of browser do you use, an operating system and exact steps to reproduce?

**Comment by beatadelura** [comment] 2017-07-24 06:48
@whyYuehao  It's been a while since we asked you for more information. Because there is no answer, I'm closing this issue.

**Closed by beatadelura** 2017-07-24 06:48 UTC
Labels: status:pending
