### ISSUE TITLE
ckeditor toolbar got disabled when copying and pasting multiple time 

### ISSUE THREAD

**Issue by UbaidBinZahid** [ckeditor/ckeditor-dev#1501] opened 2018-01-25 12:34 UTC
## [Check if the issue is already reported](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. …when text is copied and pasted multiple 
2. …ckeditor toolbar got disabled
3. …no buttons are showing

### Expected result
toolbar should not disappear how many times its going to be copied or pasted the text
*What is the expected result of the above steps?*
tool bar disappeared
### Actual result
Toolbar should not disapper
*What is the actual result of the above steps?*

## Other details

* Browser: …Chrome
* OS: …window
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment] 2018-01-26 08:41
Hello,
could you provide more information about the issue? We would like to know your CKEditor version and used plugins. I tried reproduce your issue with minimal configuration but copying and pasting multiple times works fine. You could use codepen.io, jsfiddle.net or any other online editor.

**Comment by jacekbogdanski** [comment] 2018-02-17 12:17
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-02-17 12:17 UTC
Labels: status:pending
