### ISSUE TITLE
Extra styles with multiple classes need to be sorted alphabetically.

### ISSUE THREAD

**Issue by weseze** [ckeditor/ckeditor-dev#2671] opened 2018-12-12 10:34 UTC
## Type of report

Bug
When adding extra styles with multiple classes, the classes need to be inputted alphabetically. If not the style is not available for the selected elements.

## Provide detailed reproduction steps (if any)

1. Add custom style, example "Icon button" with settings "a.button.button--primary.button--icon" and  "Icon button 2" with settings "a.button.button--icon.button--primary"
2. Create a link, and try to add both styles to it.

### Expected result

Both styles should be available.
Although in this example it doesn't make much sense to have 2 styles that do the same, it is to illustrate the problem. In real world examples you would have styles simply not showing up at all.

### Actual result

Only the "Icon button 2" is available, because the classes for this style are sorted alphabetically.

## Other details

* Browser: all
* OS: all
* CKEditor version: 4.10.1 (as far is I can tell, this was working properly before)
* Installed CKEditor plugins:

**Comment by Comandeer** [comment] 2018-12-14 09:14
Seems to be a duplicate of #2578.

**Closed by Comandeer** 2018-12-14 09:14 UTC
