### ISSUE TITLE
CKEditor 4.6.2 slows down our page

### ISSUE THREAD

**Issue by rickwschneider** [ckeditor/ckeditor-dev#571] opened 2017-06-28 15:06 UTC
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Navigate to page where CKEditor is implemented
2. Spend some time writing a new story
3. Click the create button

### Expected result

The expected result is that it would submit data from the text fields to the next page without hesitation.  When we updated to CKEditor 4.6.2, it started hesitating for a long period of time (5-10 seconds) before acknowledging that you clicked on a button on the page.  

Note that this did not happen in the old version of CKEditor that we migrated from (v3.5.3).  

## Other details

* Browser: IE, Chrome, Firefox
* OS: Windows, Mac
* CKEditor version: 4.6.2
* Installed CKEditor plugins: removeformat,notification,toolbar,button,find

Thanks in advance!

**Comment by mlewand** [comment] 2017-06-28 15:09
We need more information to reproduce this case. If you test [latest CKEditor](http://cdn.ckeditor.com/4.7.1/standard-all/samples/) it works very fast. It seems that you have some particular use where it could slow down.

Create a full demo where that can be reproduced, only with this information we'll be able to help you.

**Comment by rickwschneider** [comment] 2017-06-29 14:45
Thanks for the quick response.  I spent some time reading the release notes for the 4.7.0 and 4.7.1 versions, but did not see anything regarding performance improvements.  Were there any notable performance improvements in the 4.7.x version over 4.6.2?

Thanks!

**Comment by mlewand** [comment] 2017-06-29 19:32
There were no tickets dedicated for performance, but as always there might be a case that some newer browser APIs are which helps.

Also keep in mind that we're waiting for steps to reproduce the issue:

> We need more information to reproduce this case. If you test latest CKEditor it works very fast. It seems that you have some particular use where it could slow down.
> 
> Create a full demo where that can be reproduced, only with this information we'll be able to help you.

**Comment by beatadelura** [comment] 2017-07-19 06:53
@rickwschneider It's been a while since we asked you for more information. Because there is no answer, I'm closing this issue.

**Closed by beatadelura** 2017-07-19 06:53 UTC
Labels: status:pending
