### ISSUE TITLE
Bug - List elements are reversed with deep lists

### ISSUE THREAD

**Issue by Risord** [ckeditor/ckeditor-dev#487] opened 2017-06-08 08:13 UTC
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Put code to editor (standard demo is fine)
```
<ol>
	<li>x: press delete there -&gt;
	<ol>
		<li>&lt;- y: or backspace there
		<ol>
			<li>A</li>
			<li>B</li>
		</ol>
		</li>
	</ol>
	</li>
</ol>
```
2. Remove one list level by pressing delete at the end of x line or backspace at begin of y line.

### Expected result

<ol>
	<li>x: press delete there -&gt;&lt;- y: or backspace there
	<ol>
		<li>A</li>
		<li>B</li>
	</ol>
	</li>
</ol>

### Actual result

Deepest list is reversed.

<ol>
	<li>x: press delete there -&gt;&lt;- y: or backspace there
	<ol>
		<li>B</li>
		<li>A</li>
	</ol>
	</li>
</ol>

## Other details

* Browser: Chrome 58, Firefox 53, Edge 14
* OS: Windows 10 64
* CKEditor version: 4.5.9, 4.7.0, nightly
* Installed CKEditor plugins: Just standard set

**Comment by beatadelura** [comment] 2017-06-12 12:03
The issue can be reproduced in all browsers starting from 4.3.0 version.

**Comment by engineering-this** [comment] 2019-01-09 11:36
There is duplicate of this issue, but as discussion is there I will close this one just to continue work there. So whoever is interested on updates please check #2721.

**Closed by engineering-this** 2019-01-09 11:36 UTC
Labels: browser:chrome, browser:edge, browser:firefox, browser:ie11, status:confirmed, type:bug
