### ISSUE TITLE
Table resize does not work on few tables

### ISSUE THREAD

**Issue by zoarif** [ckeditor/ckeditor-dev#1188] opened 2017-11-21 00:47 UTC
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Paste a table in ckeditor.
2. Table drag handles that come with table resize plugin don't work
 I have seen it happening on tables that are populated and have long display text for links

### Expected result

Table drag handles should resize the table

### Actual result

Table drag handles that come with table resize plugin don't work sometimes on few tables

## Other details

* Browser:All
* OS:All
* CKEditor version: ckeditor 4.7.*
* Installed CKEditor plugins: Table resize
[sample table.docx](https://github.com/ckeditor/ckeditor-dev/files/1489606/sample.table.docx)

**Comment by msamsel** [comment] 2017-11-23 08:41
I'm able to resize attached table. I used this page for testing: http://cdn.ckeditor.com/4.7.3/full-all/samples/old/tableresize/tableresize.html
Can you check if your bug exists on this page? If yes, then could you describe how it might be reproduced?

**Comment by mlewand** [comment] 2017-12-19 17:16
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2017-12-19 17:16 UTC
Labels: status:pending
