### ISSUE TITLE
Want to avoid adding extra space between css class declaration by using ckeditor

### ISSUE THREAD

**Issue by decentplusd** [ckeditor/ckeditor-dev#955] opened 2017-09-21 20:52 UTC
## Are you reporting a feature request or a bug?
Bug

Editor is adding extra spaces between css class declaration for example
`<div align="center" class="sidebar-nav  ">`

https://stackoverflow.com/questions/27304714/want-to-avoid-adding-extra-space-between-css-class-declaration-by-using-ckeditor/27304772

## Provide detailed reproduction steps (if any)

1. Try the code snippet and put it into editor mode
2. …
3. …

### Expected result

*What is the expected result of the above steps?*
`<div align="center" class="sidebar-nav">`
### Actual result

*What is the actual result of the above steps?*
`<div align="center" class="sidebar-nav  ">`
## Other details

* Browser: Google Chrome
* OS: Windows 10
* CKEditor version:4.7.3
* Installed CKEditor plugins:Yes

**Comment by beatadelura** [comment] 2017-09-25 07:52
@decentplusd  Could you please provide [codepen](https://codepen.io/), [jsbin](https://jsbin.com/?html,output) or [jsfiddle](https://jsfiddle.net/) example with configuration and exact steps to reproduce?

**Comment by beatadelura** [comment] 2017-10-11 06:59
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by beatadelura** 2017-10-11 06:59 UTC
Labels: status:pending
