### ISSUE TITLE
Unspecified error in IE11 when space bar is pressed over read only CKEditor

### ISSUE THREAD

**Issue by AnusreeKoottungal** [ckeditor/ckeditor-dev#2082] opened 2018-06-13 13:26 UTC
Issue is reproducible in IE, but not in Chrome.

When you set the CK Editor to Read only and click on the editor and the press space bar, an error occurs in the browser console: 
SCRIPT16389: Unspecified error.
ckeditor.js (443,345)

1. In IE 11, open a web page containing a CK Editor which can be set to read only. You can use the read only demo provided in the CK Editor documentation : https://sdk.ckeditor.com/samples/readonly.html
2. Open the IE developer tools
3. Make the CK Editor readonly.
4. Click on the CK Editor
5. Press space bar

### Expected result
No error should be present in the console

### Actual result
The following error occurs in console: 
SCRIPT16389: Unspecified error.
ckeditor.js (443,345)

## Other details
* Browser: IE11
* OS: Windows 10
* CKEditor version: 4.9.2

**Comment by jacekbogdanski** [comment] 2018-06-14 08:06
Duplicate of #1184

**Closed by jacekbogdanski** 2018-06-14 08:06 UTC
