### ISSUE TITLE
[Placeholder plugin] Chrome tab crashes when user highlights span element. 

### ISSUE THREAD

**Issue by spotoczny** [ckeditor/ckeditor-dev#2329] opened 2018-08-20 09:33 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

This issue occurs on our production env but it is easily replicable on CKE editor website. 
1. Open CKE Editor 4 https://ckeditor.com/ckeditor-4/ with **placeholder plugin**
2. Add an empty paragraph at the end of the document (click enter at the end of the documnet)
3. Open Chrome devtools
4. Inspect added empty paragraph ```<p>```
5. Edit as HTML paragraph ```<p>``` and replace with:

```
<span tabindex="-1" contenteditable="false" data-cke-widget-wrapper="1" data-cke-filter="off" class="cke_widget_inline" >span text</span>

```

6. Try to highlight span element **right to left** (there is no space after span element)

### Expected result

Element text is highlighted and chrome tab do not crash

### Actual result

Tab crashes after highlighting the element on the page. Chrome v.68

## Other details

* Browser: Chrome 66, 67, 68
* OS: Mac
* CKEditor version: 4
* Installed CKEditor plugins: Placeholder plugin

**Comment by engineering-this** [comment] 2018-08-21 08:41
Hi

Closing as duplicate of #2166 

This is an known upstream bug reported on chromium issue tracker:
https://bugs.chromium.org/p/chromium/issues/detail?id=859098

According to comment this is already fixed in upcoming release.

**Closed by engineering-this** 2018-08-21 08:41 UTC
Labels: resolution:duplicate, support
