### ISSUE TITLE
Span and P tags removed when pastefromword

### ISSUE THREAD

**Issue by britishmonkey** [ckeditor/ckeditor-dev#1011] opened 2017-10-05 12:02 UTC
## Provide detailed reproduction steps (if any)

Pasting formatted text from word into editor.
config.js contains the config.allowedContent = true; so this ought to simply be enough.

### Expected result

Correctly formatted text appears in editor

### Actual result

All <span> tags are removed, leaving only the span inner text. Therefore there is also no way to retain the styles/classes for these spans since the spans are no longer there.

## Other details

* Browser: IE11
* OS: Win7
* CKEditor version: 4.5.7
* Installed CKEditor plugins: doksoft,onclick

**Comment by msamsel** [comment] 2017-10-06 07:52
Hi @britishmonkey ,
Does you problem occur also on the actual version of CKEditor? (You can test it [here](https://cdn.ckeditor.com/4.7.3/full-all/samples/))
If problem is reproduced with current version of editor, then please provide details what kind of text do you copy (It would be helpful to attach example word document to the issue).

**Comment by britishmonkey** [comment] 2017-10-06 09:15
Similar issue on your version.

I type some text and add Marker style which creates a span with a class. I copy that and paste into Word - it keeps the style. I then copy the word text and use 'paste from word' to paste back into editor. All classes are lost on the span BUT your version does actually retain the span tags although they are altered to the following and the text is not showing in Marker style.

<p><span style="font-size:8pt"><span style="color:#333333"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Some text</span></span></span></p>

My version would just have 'Some text' as plain text with no <p> or <span> tags at all..

**Comment by britishmonkey** [comment] 2017-10-06 09:17
ok so these comments also edit tags out......

your editor converts to the following.

``<p><span style="font-size:8pt"><span style="color:#333333"><span style="font-family:&quot;Arial&quot;,&quot;sans-serif&quot;">Span test 2</span></span></span></p>``

**Comment by msamsel** [comment] 2017-10-10 07:27
@britishmonkey I'm not sure that Word will preserve html classes when you paste content to it. So most probably you loose information about class name in a moment when paste content to the Word.
From your comment I see that styles are copied from word and embedded as span styles. Or is there some problem which I cannot still see?

**Comment by britishmonkey** [comment] 2017-10-10 08:35
When I  paste into Word the text appears exactly as on the editor (ie color/size) but now I can't see the styles in the dropdown so maybe Word will note styles but not classes. If I just simply Ctrl+V the text into editor it retains (to an extent) the style though adds usual horrendous Word html and alters the text style to default Word text. Using PasteFromWord button it strips everything from styles/classes completely.

**Comment by msamsel** [comment] 2017-10-11 07:32
@britishmonkey I still have problem with understanding what you consider as an issue. Could you summarise what problem you detect, how I can reproduce it, and what is, according to you, expected result?
From your description I can see that you paste something, but I don't know what. And you get some html markup which you don't like, but I don't know what html markup you expect to have. Please provide more details.

**Comment by britishmonkey** [comment] 2017-10-12 07:12
Ok I thought was fairly clear. What I expect is to copy from editor, paste to word, copy from word, paste to editor and end up with the same thing as I started.

I do not.

I have a span in editor - simply that and nothing else. `<span class='update'>Some text</span>`. This is created by typing the text then adding a class from the Styles dropmenu. I copy that span output and paste in Word. I see the span output the same as it outputs in the editor. So, whether using class or styles (I've no idea how the paste in Word knows how to display the text), Word has all the information it needs to display the style correctly. All good so far.

I copy that same span output in Word - nothing added, no new Word output or any other Word text, just simply exactly what I pasted into Word earlier. I paste back into the editor. I expect, reasonably, that the editor will show it as it did before but it does not. It simply shows as `Some text`. No span tags like before, no style additions with the class styles in place of the actual class attribute - nothing.

I have allowedContent = true in config so I don't expect the editor to remove anything it finds.

Now in your latest version it adds a load of Word p and span tags that have nothing to do with the correct style of the copied class. It still does not retain the class and it doesn't convert that class to the correct styles.

The steps you need to follow on your editor.

1. Type something into editor.
2. Highlight it and give it a class from the Styles dropmenu.
3. Highlight it and copy it
4. Paste it into Word keeping source formatting.
5. Copy the text in Word.
6. Use Paste From Word button to paste back into editor.
7. Note the wrong formatting of the text.

Thanks.

**Comment by msamsel** [comment] 2017-10-17 08:01
I've made some simple test with using our `marker` style on our [sample](https://cdn.ckeditor.com/4.7.3/full-all/samples/). This style provides span with `class="marker"` to editor.
This style is not copied to Word. I don't know why claim that class are copied to Word, but it's not the usual thing. Maybe your case is somehow special. From what I know, Word doesn't keep the class information. So when you copy element with class to Word, then automatically you should loose this class. And class should be converted by the Word to inline styles.
Which later are embed as spans in editor when you copy it from  Word.

**Comment by msamsel** [comment] 2017-11-29 09:07
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-11-29 09:07 UTC
Labels: status:pending
