### ISSUE TITLE
Font size issue on iPad

### ISSUE THREAD

**Issue by akashbiz** [ckeditor/ckeditor-dev#1899] opened 2018-04-18 11:52 UTC
## Are you reporting a feature request or a bug?

Bug
## Provide detailed reproduction steps (if any)

1. Create a ckeditor instance with font size plugin with size options 8 to 72px
2. Open CKEditor in **iPad Safari** and try giving any particular size to text till 24 it get applied but now try giving font size greater than 24
3. Observe that font size above 25 are not applied.
4. If I try to apply bigger font size, dropdown scroll get freeze and not able scroll within size dropdown anymore.

### Expected result

*What is the expected result of the above steps?*
Any font size should work on iPad just like any other device
### Actual result
Font size dropdown freeze if font size greater than 24 is applied

***What is the actual result of the above steps?***
font size above 24 didn't work and font size dropdown is no more scroll-able!
## Other details

* Browser: iPad Safari
* OS: IOS 10.3.3
* CKEditor version: 4.7.2
* Installed CKEditor plugins: font

**Comment by engineering-this** [comment] 2018-04-19 08:12
Hello

I've tried to reproduce your bug on 4.9.2 and on 4.7.2 with no success. Although I used iPad with iOS 11.3. Could you try to reproduce this bug on newest iOS? And if you do, then please give more detailed information on your editor setup. If you can prepare sample in which you can reproduce this bug it would help us a lot to track and fix this. You can use codepen.io or similar site to store this sample.

**Comment by mlewand** [comment] 2018-05-10 10:07
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by Menthuss** [comment] 2018-08-16 08:55
I'm running into this issue as well on iOS 11.4.1. When I try to set the font size to anything above 18, the dropdown scrolls back up to the top, loses focus and freezes. The selected font size isn't applied either.

**Comment by engineering-this** [comment] 2018-10-10 07:12
@Menthuss I can't reproduce your issue. Font size dropdown works fine for me. It looks like third party software you mentioned might be responsible for problem. 

I'm closing this as an upstream issue. Although if you find way to reproduce issue without any third party software please let us know. Sample editor configured in js sandbox like codepen.io or jsfiddle.net would be optimal.

**Closed by engineering-this** 2018-10-10 07:12 UTC

**Comment by Menthuss** [comment] 2018-10-10 07:34
@engineering-this I've found out that this bug originates from Apple's Webkit. See the following bug report:
https://bugs.webkit.org/show_bug.cgi?id=139694
