### ISSUE TITLE
CKeditor truncating aria attributes of the anchor tag present in the content

### ISSUE THREAD

**Issue by pkabadeI** [ckeditor/ckeditor-dev#3171] opened 2019-06-17 09:57 UTC
## Type of report
Accessibility Insights tool Bug: ] Links must have discernible text 

## Provide detailed reproduction steps (if any)

1. <CKEditor... content={this.props.emailbody} .. /> 
Emailbody has code "<a style="text-decoration:none;" href="[[SurveyLink]]" target="_blank" rel="noopener noreferrer" data-cke-saved-href="[[SurveyLink]]" aria-labelledby="surveylink"><span style="color:white">START SURVEY</span> </a>"
2. After body is rendered the aria-labelledby attribute is lost from anchor tag. 
Note: Label with "surveylink" ID is present in the body string

### Expected result

*What is the expected result of the above steps?*
Aria atributes should be allowed on the link control

### Actual result

*What is the actual result of the above steps?*
Aria attributes are lost after render
## Other details

* OS:OS Build: Version 1809 (OS build 17763.292
* Browser: Microsoft Edge 42.15063,Chrome
* CKEditor version: 4.10.0
* Installed CKEditor plugins: NA

**Comment by jacekbogdanski** [comment] 2019-07-09 08:58
I see that you are using some kind of frontend framework (`<CKEditor... content={this.props.emailbody} .. />`). Isn't the issue related to this library itself? We are not using Accessibility Insights to validate CKEditor4 itself, so it would be nice if you could provide more information about the issue, reproduction steps, etc.

Also, you can configure our [Content Filtering (ACF)](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) feature to enable chosen attributes.

**Comment by Dumluregn** [comment] 2019-07-23 17:09
Hi @pkabadeI, it's been a while since we last heard from you. We hope that tips provided to you by @jacekbogdanski helped you and we're closing this issue for now. Still, feel free to provide us requested feedback, so that we can reopen this issue.

**Closed by Dumluregn** 2019-07-23 17:09 UTC
Labels: status:pending, type:bug
