### ISSUE TITLE
Table classes unable to be retained with pastefromword

### ISSUE THREAD

**Issue by britishmonkey** [ckeditor/ckeditor-dev#1012] opened 2017-10-05 12:07 UTC
## Provide detailed reproduction steps (if any)

Pasting formatted text from word into editor.
config.js contains the config.allowedContent = true; 

### Expected result

Table class is retained after pasting into editor. If I try to add a 'table:' function into getRules in filter/default.js the editor fails. I can add a tbody function to hack in a hard-coded class to the tbody ok but the original class is on the table tag so would be good to retain it there.

### Actual result

Class attribute disappears..

## Other details

* Browser: IE11
* OS: Win7
* CKEditor version: 4.5.7
* Installed CKEditor plugins: doksoft,onclick

**Comment by msamsel** [comment] 2017-10-11 07:23
Hi,

please check your issue with the current version of the editor test page [here](https://cdn.ckeditor.com/4.7.3/full-all/samples/). If problem is possible to reproduce on current version of the editor, please provide reproduction steps which allows on repeating issue on my side. It would be nice to get also problematic word document.

**Comment by britishmonkey** [comment] 2017-10-12 06:51
Hi.

On current version,  I create a table using the table button and add a class 'myclass' using the advanced tab. The source code produced is as follows.
`<table border="1" cellpadding="1" cellspacing="1" class="myclass" style="width:500px">`

If I copy that table (not the source) into Word, then copy from word and use Pastefromword back into the editor the code is as follows.
`<table style="border-image:none; border:#000000; width:375pt"></table>`

The class is gone and the style is different anyway.

It would be good if it retained the class (or even converted it correctly into styles) but, for my purposes at least, it would suffice to even be able to force a class for a table via filter/default.js but seems that only the tbody can be dealt with there.

Thanks.

**Comment by msamsel** [comment] 2017-10-19 15:29
It's the same case here as in #1011. There is no `class` in clipboard taken from Word.

**Comment by msamsel** [comment] 2017-11-29 09:08
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-11-29 09:08 UTC
Labels: status:pending
