### ISSUE TITLE
The emoji matching should be improved

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-dev#2182] opened 2018-06-27 11:30 UTC
Right now if you type `:smile` you get something like this:

<img width="269" alt="screen shot 2018-06-27 at 13 28 16" src="https://user-images.githubusercontent.com/545175/41971269-17bd0266-7a0e-11e8-9f46-6b1f07bb6495.png">

While the reality is that you are looking most likely for some of these:

<img width="625" alt="screen shot 2018-06-27 at 13 28 30" src="https://user-images.githubusercontent.com/545175/41971262-13b88a82-7a0e-11e8-9c8d-fad1d3a9f37e.png">

What we should do is to start using "Other Keywords" and give them the highest priority:

http://www.unicode.org/emoji/charts-11.0/emoji-list.html

**Comment by mlewand** [comment] 2018-06-27 11:31
Duplicate of #2181 😉

**Closed by mlewand** 2018-06-27 11:31 UTC

**Comment by wwalc** [comment] 2018-06-27 11:34
C'mon 😛
