### ISSUE TITLE
Paste paragraph from word problem

### ISSUE THREAD

**Issue by fikoborquez** [ckeditor/ckeditor-dev#1868] opened 2018-04-06 20:21 UTC
## Are you reporting a feature request or a bug?
bug, maybe other.

## Provide detailed reproduction steps (if any)

1. Copy text from partial paragraph from Word document and paste it into CKEditor.

[Image](https://i.imgur.com/hyA8CtN.jpg)

### Expected result

[https://i.imgur.com/8iScxxn.jpg](https://i.imgur.com/8iScxxn.jpg)

### Actual result

[https://i.imgur.com/oJtHkfV.jpg](https://i.imgur.com/oJtHkfV.jpg)

## Other details

* Browser: Firefox 59.0.2
* OS: Windows 8.1
* CKEditor version: 4.8
* Installed CKEditor plugins:

	plugins : {
		'a11yhelp' : 1,
		'about' : 1,
		'basicstyles' : 1,
		'bidi' : 1,
		'blockquote' : 1,
		'clipboard' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'contextmenu' : 1,
		'copyformatting' : 1,
		'dialogadvtab' : 1,
		'div' : 1,
		'elementspath' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'flash' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'format' : 1,
		'forms' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'iframe' : 1,
		'image' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'language' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'magicline' : 1,
		'maximize' : 1,
		'newpage' : 1,
		'pagebreak' : 1,
		'pastefromword' : 1,
		'pastetext' : 1,
		'preview' : 1,
		'print' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'save' : 1,
		'scayt' : 1,
		'selectall' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'smiley' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'tab' : 1,
		'table' : 1,
		'tableselection' : 1,
		'tabletools' : 1,
		'templates' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'uploadimage' : 1,
		'wsc' : 1,
		'wysiwygarea' : 1
	},

**Comment by jacekbogdanski** [comment] 2018-04-09 06:50
Duplicate of #651

**Closed by jacekbogdanski** 2018-04-09 06:50 UTC
