### ISSUE TITLE
Pasting table data into inline editor not working properly when inline editor contained in a table

### ISSUE THREAD

**Issue by lkues** [ckeditor/ckeditor-dev#2514] opened 2018-10-24 13:07 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create an inline editor that is contained in a table.
2. Copy some table data.
3. Paste the data into the inline editor.

### Expected result

Table content is pasted into the inline editor.

### Actual result

Table content is pasted outside of the inline editor.   See below.

![table-paste](https://user-images.githubusercontent.com/34172584/47432422-185d2f00-d76c-11e8-81f5-50e18a1a1c89.png)

## Other details

* Browser: All
* CKEditor version: 4.7.2
* Installed CKEditor plugins: tableselection

**Comment by jacekbogdanski** [comment] 2018-10-24 17:34
Hello,

I'm able to reproduce the issue. It seems to be the same bug which is causing https://github.com/ckeditor/ckeditor-dev/issues/2403. I already prepared PR (https://github.com/ckeditor/ckeditor-dev/pull/2476) for the mentioned issue so I will update it accordingly to include this case.

**Comment by Comandeer** [comment] 2018-12-05 16:43
Fixed in 4.11.2.

**Closed by Comandeer** 2018-12-05 16:43 UTC
Labels: plugin:tableselection, status:confirmed, type:bug
