### ISSUE TITLE
first time dialog not properly loaded from\

### ISSUE THREAD

**Issue by jagdpenta** [ckeditor/ckeditor-dev#3172] opened 2019-06-17 10:46 UTC
## Type of report

Bug Angular 6 with Ck-editor implemented, once we click on Ck-editor image, table or any button for first time it will not load dialog properly. 

## Provide detailed reproduction steps (if any)

1. … while clicking on image button/table or any other button which is open a dialog window
2. …this was only happend first time after load, after refresh it will work as usual.
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: … Chrome version : 74.03
* OS: … Windows 10
CKEditor version: … 4
* Installed CKEditor plugins: …
![image](https://user-images.githubusercontent.com/25173/59598690-71723c80-911a-11e9-9433-45166081feb6.png)

**Comment by jacekbogdanski** [comment] 2019-06-24 07:44
The issue is not reproducible with 4.11.4, so I suppose it's caused by your application implementation. Are you able to give us some code sample without using 3rd party software to reproduce the issue?

Additionally, you may want to take a look at our [Angular integration](https://github.com/ckeditor/ckeditor4-angular) for better integration out of the box.

**Comment by jacekbogdanski** [comment] 2019-07-08 09:04
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2019-07-08 09:04 UTC
Labels: status:pending, type:bug
