### ISSUE TITLE
IE9-11 & Edge - setting editor to readOnly and pressing Ctrl+C removes selection.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor-dev#1982] opened 2018-05-17 10:49 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open this [codePen](https://codepen.io/j_swiderski/pen/XqVRxG) and run it in IE9-11 or Edge browser
2. Select any part of text and press `Ctrl+C`

### Expected result

It is possible to copy text.

### Actual result

Selection dissapears.

Edge does that gracefully and throws:
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_errors.html#range-startcontainer
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_errors.html#range-endcontainer
https://docs.ckeditor.com/ckeditor4/latest/guide/dev_errors.html#selection-fake-reset

IE throws Unspecified error `selection.js` in line 2202. Code throwing error is `sel.addRange( nativeRange );`

## Other details

**Please note this is the same ticket as #1916 I have decided to report a new one because it also has more visual impact on Edge.**

**Comment by mlewand** [comment] 2018-05-18 09:15
@jswiderski could you check if it's also a regression from 4.7.0?

@Comandeer could you investigate what's causing the issue?

**Comment by jswiderski** [comment] 2018-05-18 09:54
@mlewand I must have removed bottom of template by mistake. Yes, problem can be reproduced from CKE 4.7.0 in IE9-11 and Edge.

**Comment by Comandeer** [comment] 2018-05-18 09:57
Isn't it a duplicate of https://github.com/ckeditor/ckeditor-dev/issues/1184? We have already PR for it https://github.com/ckeditor/ckeditor-dev/pull/1692/ – however it only eliminates thrown error, disabling key handling at the same time.

**Comment by mlewand** [comment] 2018-08-09 13:44
Duplicate of #1916.

**Closed by mlewand** 2018-08-09 13:44 UTC
Labels: browser:edge, browser:ie10, browser:ie11, browser:ie9, status:confirmed, support, type:bug

**Comment by mlewand** [comment] 2018-08-10 12:04
A fix for this issue is ready and has been merged to our upcoming release. It will be available in 4.10.1.

However you can already see it on [CKEditor preview builds](https://ckeditor4-preview.ckeditor.com/master/samples/).

I have forked the original codepen so that it uses preview CKE4 build here: https://codepen.io/mlewand/pen/rroRGQ
