### ISSUE TITLE
White Space is removed in Chrome

### ISSUE THREAD

**Issue by ved54321** [ckeditor/ckeditor-dev#477] opened 2017-06-07 06:33 UTC
### Steps to reproduce:

   1. Write any text in editor in chrome with space e.g. Hello
    2. Copy paste the same in Editor eg. Hello Hello Hello
    3. After saving it removes the space eg. HelloHelloHello 

### Expected result

Hello Hello Hello 

### Actual result

HelloHelloHello

## Other details

* Browser: …  Chrome (Version 58.0.3029.110 (64-bit)) 
* OS: … Windows
* CKEditor version: … 3

Let me know if you need more details

**Comment by mlewand** [comment] 2017-06-08 09:10
@ved54321 Can you reproduce it on [our nightly build](http://nightly.ckeditor.com/latest/standard/ckeditor/samples/)? Space is handled correctly.

It does sound a bit like a backend problem. Also we do not provide support for CKEditor at verison 3.

**Comment by mlewand** [comment] 2017-06-27 14:55
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2017-06-27 14:55 UTC
Labels: status:pending
