### ISSUE TITLE
sub bullets point are lost while paste using ctr + v or paste from word 

### ISSUE THREAD

**Issue by rj0512** [ckeditor/ckeditor-dev#1875] opened 2018-04-10 07:24 UTC
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1.copy paste below data to CKEditor using ctr + v or paste from word option

Test Items
1.1 first bullet point
1.2 Second bullet point

### Expected result
Pasted Item should look like this:
Test Items
1.1 first bullet point
1.2 Second bullet point

### Actual result
Pasted Item is look like:
![image](https://user-images.githubusercontent.com/38240902/38541966-47ad6b2e-3cbe-11e8-88d8-c1335e75adad.png)

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by engineering-this** [comment] 2018-04-11 06:03
Duplicate of #1844

**Closed by engineering-this** 2018-04-11 06:03 UTC

**Comment by rj0512** [comment] 2018-04-13 12:32
Kajetan Litwinowicz
Is it working in any previous version of ck editor?
