### ISSUE TITLE
Destroy on CK-Instance does not destroy the inline toolbar

### ISSUE THREAD

**Issue by bnarula** [ckeditor/ckeditor-dev#2180] opened 2018-06-27 10:29 UTC
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create an Inline CKEditor on any div
    
`ckInstance = CKEditor.inline(that.container.getElement('#' + this.ckViewId), this.ckEConfig);`

2. Call destroy on the same instance

   `this.ckInstance.destroy();`

3. Check for the toolbar div with id = cke_{instanceId} 
![image](https://user-images.githubusercontent.com/31417517/41968734-e5944c26-7a22-11e8-9424-8b231f4b5cf0.png)

### Expected result

The div in step 3 should be destroyed

### Actual result

The div is still present in the DOM, this creates multiple copies of the div if I re-render the component which uses CKEditor. 

## Other details
* CKEditor version: … 4

Also, please guide me any API method that gets me the instance of the above mentioned toolbar, I could not find any with CKEDITOR.instance.

**Comment by fasihi01** [comment] 2018-06-28 12:11
We've had this issue too, resolved it by calling 
```
ckInstance.focusManager.blur(true);
ckInstance.removeAllListeners();
ckInstance.destroy();
```

**Comment by jacekbogdanski** [comment] 2018-07-04 07:47
Hello,

I wasn't able to reproduce your issue. Could you check if this issue exists with our latest CKEditor release (`4.10.0`) and give us feedback? Also, show us please minimal configuration causing the issue.

**Comment by jacekbogdanski** [comment] 2018-07-24 10:22
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by jacekbogdanski** 2018-07-24 10:22 UTC
Labels: status:pending
