### ISSUE TITLE
Suggestion Tab not being placed correctly when CKEditor instance is used for Japanese entry

### ISSUE THREAD

**Issue by mcstoufer** [ckeditor/ckeditor-dev#1101] opened 2017-10-27 16:51 UTC
## Are you reporting a feature request or a bug?
Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Load long HTML file with multiple CKEditor instances.
2. Use Apple Smart Keyboard attached and change device Language to Japanese
3. Start text entry in a CKEditor instance. Entry works just fine, but notice location of suggestion tab bar (Screenshots attached). Scroll up, and up, and up. The tab bar will scroll out of the WKWEbView context and over our native layout. Scroll enough and the tab bar completely goes off screen.
4. Now select a CKEditor instance that is far enough down the page that you need to scroll a few full screen heights to get to it. Tap editor and start entry. Notice the tab bar is nowhere to be seen. If you're lucky, you can scroll up enough and it will now be visible.

### Expected result

The suggestion tab bar stay local to the entry field in focus.

### Actual result

The suggestion tab bar appears to be pinned to some phantom location farther up the layout and scrolls relative to that position.

## Other details

Please let me know if this some arcane iOS issue instead. Not sure if there is an issue with the iFrame location and the tab bar is just finding that as the anchor point.

* Browser: WKWebView
* OS: 10.3 / 11.1
* CKEditor version: 4.5.9
* Installed CKEditor plugins: None

![screen shot 2017-10-27 at 9 38 26 am](https://user-images.githubusercontent.com/2081083/32115346-518103da-bafb-11e7-980d-e175d9e90864.png)
![screen shot 2017-10-27 at 9 38 12 am](https://user-images.githubusercontent.com/2081083/32115347-519e4526-bafb-11e7-9565-ef2990ef0277.png)

**Comment by msamsel** [comment] 2017-11-20 09:06
Hi,
does the problem occur on the actual version of CKEditor (4.7.3)? If so, then could you prepare test page on some codepen.io, jsfiddle.net, etc. and explain what to do to reproduce the error?

From your screenshot I'm not sure it's a feature of CKEditor, it looks more like browser issue, but I cannot test it without proper example.

**Comment by mlewand** [comment] 2017-12-19 17:15
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by mlewand** 2017-12-19 17:15 UTC
Labels: status:pending
