### ISSUE TITLE
Language Plugin Problems with Typo3

### ISSUE THREAD

**Issue by thofi88** [ckeditor/ckeditor-dev#2511] opened 2018-10-24 12:25 UTC
Hallo,

i hope you can help me. And sorry for my englich, but it´s not my native language.

I want to install the language plugin in CKEditor in Typo3-system v_9.5.0.
So and don´t can find the mistake. The other plugins works perfectly.

Here is the console.log:

ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:5359 Uncaught TypeError: e.toLowerCase is not a function
    at Object.detect (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:5359)
    at Object.load (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:5348)
    at m (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:5721)
    at ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:5716
    at b (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:10439)
    at Object.loadPart (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:10471)
    at h (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:5715)
    at a.<anonymous> (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:5708)
    at a.h (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:126)
    at a.<anonymous> (ckeditor.js?bust=363f71688fb78dbd83ee249022bc5c67145df294:186)

## Other details

* Browser: Chrome
* OS: Linux
* CKEditor version: 4.10.1
* Installed CKEditor plugins: 
typo3link: 
    showbrokenlinks: 
    abbr: 
    insertpre: 
    balloonpanel:
    a11ychecker:
    bidi: 
    panel: 
    floatpanel:
    menu: 
    button:
    menubutton: 
    language:
    quicktable: 
    autolinking: 
    softhyphen:

**Comment by jacekbogdanski** [comment] 2018-10-24 14:07
Hello,

unfortunately, we are not able to help you with the configuration of the external CMS which code is not maintained by us. Your issue is probably caused by `typo3link` - if you check our online samples, the editor with `language` plugin [works like a charm](https://ckeditor.com/latest/samples/). 

You should report the issue on TYPO3 issue tracker: https://forge.typo3.org/projects/typo3cms-core/issues or check stackoverflow.com - it may be already resolved by a community.

**Closed by jacekbogdanski** 2018-10-24 14:07 UTC

**Comment by dogawaf** [comment] 2019-05-14 17:01
See the related issue on TYPO3 bugtracker: https://forge.typo3.org/issues/88302
