### ISSUE TITLE
"removePlugins": "toolbar" seemingly has stopped working in v4.7

### ISSUE THREAD

**Issue by jonnott** [ckeditor/ckeditor-dev#516] opened 2017-06-15 09:26 UTC
Prior to v4.7, this config would show a 'read-only' CKEditor, without a toolbar.

		{
			"readOnly": true,
			"allowedContent": true,
			"removePlugins": "toolbar,elementspath"
		}

..but since v4.7, it now shows the toolbar :(

**Comment by jonnott** [comment] 2017-06-15 09:32
Related? https://github.com/ckeditor/ckeditor-dev/issues/491

**Comment by mlewand** [comment] 2017-06-16 09:30
This is a duplicate of #491.

**Closed by mlewand** 2017-06-16 09:30 UTC
Labels: resolution:duplicate
