### ISSUE TITLE
Table Editing: Trapped in Table after pressing Backspace

### ISSUE THREAD

**Issue by mmichaelis** [ckeditor/ckeditor-dev#843] opened 2017-08-30 12:13 UTC
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

_none found_

## Provide detailed reproduction steps (if any)

1. Have an empty document.
2. Create a table with default settings (3x2 etc. at https://ckeditor.com/)
3. Place cursor outside the table (at the end of the document)
4. Press Backspace.
5. The cursor jumps into the last cell of the table.
6. Try to leave the table with cursor keys or clicks.

### Expected result

You can get outside the table somehow to write text in front and/or behind the table.

### Actual result

There is no way to escape the table anymore. Neither with cursor keys nor with clicks.

In Chrome you can always leave the table (although it is not visible at ckeditor.com) and start typing.

## Other details

* Browser: MSIE 11, Edge 40, Firefox 55 (works in Chrome 60)
* OS: Windows 10
* CKEditor version: 4.7.2 (at https://ckeditor.com/)

**Comment by beatadelura** [comment] 2017-08-31 07:15
@mmichaelis There is a possibility to navigate between table and content outside the table by using arrow keys. I checked it on Chrome 60, Firefox 55, IE11 and Edge with CKEditor version 4.7.2. 

Please follow the steps:

1. Go to https://ckeditor.com/.
2. At the end of the document create a table.
3. Put the caret in the last cell.
4. Press right arrow key (notice, at the bottom of the editor there is an element path).
5. Start typing any text.

Maybe, the problem is that the caret is not visible after pressing arrow key?

**Comment by mmichaelis** [comment] 2017-08-31 08:35
Steps to reproduce:

1. Go to https://ckeditor.com/.
2. At the end of the document create a table.
3. Put the caret at the end of the text (there will be an empty p tag).
4. Press Backspace - the caret will move into the last cell of the table
5. Press right arrow key - nothing happens despite in Chrome
6. Start typing any text - it will be added inside the last table cell

So the important thing is to delete the "end" of the document, i. e. the p tag at the end. Inspecting the DOM you will notice the following structure after pressing backspace:

```xml
<body>
    <table> ... </table>
</body>
```

This is the same in all browsers. But only Chrome allows to move the cursor between `</table>` and `</body>` and writing new text there will add a paragraph.

**Comment by beatadelura** [comment] 2017-08-31 13:34
Thanks for more details. Now I see the problem :)

**Comment by jswiderski** [comment] 2017-10-19 14:36
@mmichaelis we had many such issues in CKEditor 3 and to get rid of them we have created magicline plugin in CKEditor 4. Please go to add-ons page and add it to your editor  -https://ckeditor.com/cke4/addon/magicline. 

IMHO this ticket should be closed as it touches browser behavior and there is a solution for it in form of a dedicated plugin.

**Comment by mlewand** [comment] 2017-10-20 09:17
Correct, just as @jswiderski says we created magicline plugin just for that. Note that it features mouse handling (you can click it) as well as hotkeys (see [Writing section in Keyboard Shortcuts guide](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_shortcuts-section-writing)).

**Comment by jswiderski** [comment] 2017-10-20 09:42
@mmichaelis please give magic line w try - you will notice how easy it is to insert new lines after, before and between tags like tables, divs etc.

**Closed by jswiderski** 2017-10-20 09:42 UTC
Labels: browser:edge, browser:firefox, browser:ie11, resolution:wontfix, status:confirmed, type:bug

**Comment by mmichaelis** [comment] 2017-10-21 15:45
@jswiderski Thanks for the hint. I'll try.
