### ISSUE TITLE
baseHref is still ignored in inline editor

### ISSUE THREAD

**Issue by Quix0r** [ckeditor/ckeditor-dev#896] opened 2017-09-12 13:40 UTC
## Are you reporting a feature request or a bug?

It is a long-term unfixed bug.

## Links
* Only old ticket for 4.0: https://dev.ckeditor.com/ticket/12574

## Provide detailed reproduction steps (if any)

1. Create a valid (x)HTML page with `<div id="content"></div>`
2. Register the CKEditor on it: `CKEDITOR.inline("content");`
3. Put that page on a sub-folder on your server.

### Expected result

The `baseHref` option is honored and all editor's images are loaded properly.

### Actual result

The `baseHref` is ignored and some URLs are not loaded when `base` tag is set to sub-folder.

## Other details

* Browser: Firefox 55.0.3 (64-bit)
* OS: Windozer 10
* CKEditor version: 4.7.2 (custom build)
* Installed CKEditor plugins: _see below_

`build-config.js`:
````
/**
 * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see LICENSE.md or http://ckeditor.com/license
 */

/**
 * This file was added automatically by CKEditor builder.
 * You may re-use it at any time to build CKEditor again.
 *
 * If you would like to build CKEditor online again
 * (for example to upgrade), visit one the following links:
 *
 * (1) http://ckeditor.com/builder
 *     Visit online builder to build CKEditor from scratch.
 *
 * (2) http://ckeditor.com/builder/febfc1ff860c1628e1ec0f76a83ffe62
 *     Visit online builder to build CKEditor, starting with the same setup as before.
 *
 * (3) http://ckeditor.com/builder/download/febfc1ff860c1628e1ec0f76a83ffe62
 *     Straight download link to the latest version of CKEditor (Optimized) with the same setup as before.
 *
 * NOTE:
 *    This file is not used by CKEditor, you may remove it.
 *    Changing this file will not change your CKEditor configuration.
 */

var CKBUILDER_CONFIG = {
	skin: 'moono-lisa',
	preset: 'full',
	ignore: [
		'.DS_Store',
		'.bender',
		'.editorconfig',
		'.gitattributes',
		'.gitignore',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'.travis.yml',
		'bender-err.log',
		'bender-out.log',
		'bender.ci.js',
		'bender.js',
		'dev',
		'gruntfile.js',
		'less',
		'node_modules',
		'package.json',
		'tests'
	],
	plugins : {
		'a11ychecker' : 1,
		'a11yhelp' : 1,
		'about' : 1,
		'basicstyles' : 1,
		'clipboard' : 1,
		'enterkey' : 1,
		'entities' : 1,
		'find' : 1,
		'floatingspace' : 1,
		'glyphicons' : 1,
		'image' : 1,
		'indentlist' : 1,
		'link' : 1,
		'list' : 1,
		'magicline' : 1,
		'removeformat' : 1,
		'scayt' : 1,
		'sourcearea' : 1,
		'specialchar' : 1,
		'symbol' : 1,
		'tabletools' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'wysiwygarea' : 1
	},
	languages : {
		'de' : 1,
		'en' : 1
	}
};
````

And besides, `Underline` and `Strike(through?)` are not showing up (both from `basicstyles` plugin). Will open another ticket for this.

[Screenshot showing custom inline editor](https://cloud.mxchange.org/index.php/s/VmzqGESTV1rE041)

The missing buttons are: 
* `Save`
* `Cancel`
* `RedMarker`
* `GreenMarker`

All are causing 404 errors on webserver as they reference absolutely:

````
<span class="cke_button_icon cke_button__save_icon"
 style="background-image:url('/media/img/document-save.png?t=H7HD');background-position:0 undefinedpx;background-size:16px;">
&nbsp;
</span>
````
Also the `undefined` is indicating another bug.

**Comment by msamsel** [comment] 2017-09-15 07:35
Hi,
could you prepare example page where problem is visible? I have problem with reproducing this error on my computer.

**Comment by msamsel** [comment] 2017-10-17 07:41
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Closed by msamsel** 2017-10-17 07:41 UTC
Labels: status:pending
